using Avalonia;
using Avalonia.Controls;
using Avalonia.Input;
using Avalonia.Layout;
using Avalonia.Media;
using System.Text;
using Accyourate.App.AssetManagement.Models;
using Accyourate.App.AssetManagement.Services;
using Accyourate.App.UIFramework.Tokens;

namespace Accyourate.App.AssetManagement;

public sealed class LocationStocktakeView : UserControl
{
    private readonly LocationStocktakeRepository _repository=new();private readonly SparePartLocationsRepository _locations=new();private readonly SparePartsInventoryRepository _inventory=new();
    private readonly StackPanel _rows=new();private readonly TextBlock _message=new();
    public LocationStocktakeView(){Background=UiTokens.Brush(UiTokens.Background);_locations.EnsureInitialAllocations(_inventory.GetItems());Content=Build();Load();}
    private Control Build(){var root=new DockPanel();var header=new Grid{ColumnDefinitions=new ColumnDefinitions("*,Auto"),Margin=new Thickness(24,20,24,12)};header.Children.Add(new StackPanel{Spacing=4,Children={new TextBlock{Text="Inventario per Ubicazione",FontSize=30,FontWeight=FontWeight.Bold},new TextBlock{Text="Conteggio locale tramite QR ubicazione e ricambio.",Foreground=UiTokens.Brush(UiTokens.TextSecondary)}}});var create=Button("Nuova sessione",NewSession,true);Grid.SetColumn(create,1);header.Children.Add(create);DockPanel.SetDock(header,Dock.Top);root.Children.Add(header);_message.Margin=new Thickness(24,0,24,8);DockPanel.SetDock(_message,Dock.Top);root.Children.Add(_message);root.Children.Add(new ScrollViewer{Content=_rows,Margin=new Thickness(24),HorizontalScrollBarVisibility=Avalonia.Controls.Primitives.ScrollBarVisibility.Auto,VerticalScrollBarVisibility=Avalonia.Controls.Primitives.ScrollBarVisibility.Auto});return root;}
    private void Load(){try{var locations=_locations.GetLocations().ToDictionary(x=>x.Id);var sessions=_repository.GetAll();_rows.Children.Clear();_rows.MinWidth=980;_rows.Children.Add(Header());for(var i=0;i<sessions.Count;i++){locations.TryGetValue(sessions[i].LocationId,out var location);_rows.Children.Add(Row(sessions[i],location,i));}}catch(Exception ex){Show($"Errore inventario ubicazioni: {ex.Message}",true);}}
    private async void NewSession(){var owner=TopLevel.GetTopLevel(this) as Window;if(owner is null)return;var locations=_locations.GetLocations().Where(x=>x.IsActive).ToList();if(locations.Count==0){Show("Crea prima un'ubicazione.",true);return;}var location=await new SelectStocktakeLocationDialog(locations).ShowDialog<SparePartWarehouseLocation?>(owner);if(location is null)return;try{_repository.Create(location.Id,Environment.UserName,_locations.GetBalances(),_inventory.GetItems().ToDictionary(x=>x.Id));Show("Sessione locale creata.");Load();}catch(Exception ex){Show($"Sessione non creata: {ex.Message}",true);}}
    private async void Open(LocationStocktake session){var owner=TopLevel.GetTopLevel(this) as Window;if(owner is null)return;await new LocationStocktakeSessionWindow(_repository,_locations,_inventory,session.Id).ShowDialog(owner);Load();}
    private void Export(LocationStocktake session){try{session=_repository.Get(session.Id);var folder=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData),"Accyourate Enterprise X","exports");Directory.CreateDirectory(folder);var path=Path.Combine(folder,$"inventario_ubicazione_{session.SessionNumber}_{DateTime.Now:yyyyMMdd_HHmmss}.csv");var lines=new List<string>{"Codice;Descrizione;Registrata;Contata;Differenza;Valore differenza;Note"};foreach(var x in session.Lines)lines.Add($"{Csv(x.PartCode)};{Csv(x.Description)};{x.ExpectedQuantity:0.00};{x.CountedQuantity:0.00};{x.Difference:0.00};{x.DifferenceValue:0.00};{Csv(x.Notes)}");File.WriteAllLines(path,lines,new UTF8Encoding(true));Show($"Report creato: {path}");}catch(Exception ex){Show($"Export non riuscito: {ex.Message}",true);}}
    private Control Header(){var g=GridRow();foreach(var x in new[]{("Sessione",0),("Ubicazione",1),("Stato",2),("Operatore",3),("Data",4),("Conteggi",5),("Differenze",6),("Azioni",7)})AddText(g,x.Item1,x.Item2,true);return new Border{Background=UiTokens.Brush(UiTokens.SurfaceAlt),Padding=new Thickness(9),Child=g};}
    private Control Row(LocationStocktake s,SparePartWarehouseLocation? l,int i){var g=GridRow();AddText(g,s.SessionNumber,0,true);AddText(g,l?.DisplayName??$"#{s.LocationId}",1);AddText(g,s.Status,2,true);AddText(g,s.OperatorName,3);AddText(g,Date(s.CreatedAt),4);AddText(g,$"{s.CountedLines}/{s.Lines.Count}",5);AddText(g,s.DifferenceLines.ToString(),6,false,s.DifferenceLines>0);var a=new StackPanel{Orientation=Orientation.Horizontal,Spacing=4};a.Children.Add(Button(s.Status==StocktakeStatus.Closed?"Consulta":"Conta",()=>Open(s)));a.Children.Add(Button("CSV",()=>Export(s)));Grid.SetColumn(a,7);g.Children.Add(a);return new Border{Background=UiTokens.Brush(i%2==0?UiTokens.Surface:UiTokens.SurfaceAlt),BorderBrush=UiTokens.Brush(UiTokens.Border),BorderThickness=new Thickness(0,0,0,1),Padding=new Thickness(9,7),Child=g};}
    private static Grid GridRow()=>new(){ColumnDefinitions=new ColumnDefinitions("165,200,110,120,140,90,100,150")};private static string Date(string x)=>DateTime.TryParse(x,out var d)?d.ToString("dd/MM/yyyy HH:mm"):x;private static string Csv(string x)=>$"\"{(x??"").Replace("\"","\"\"")}\"";
    private static Button Button(string t,Action a,bool primary=false){var b=new Button{Content=t,MinHeight=34,Margin=new Thickness(3),Background=UiTokens.Brush(primary?UiTokens.BrandBlue:UiTokens.SurfaceAlt),Foreground=primary?Brushes.White:UiTokens.Brush(UiTokens.TextPrimary)};b.Click+=(_,_)=>a();return b;}private static void AddText(Grid g,string t,int c,bool strong=false,bool danger=false){var x=new TextBlock{Text=string.IsNullOrWhiteSpace(t)?"—":t,FontWeight=strong?FontWeight.SemiBold:FontWeight.Normal,Foreground=UiTokens.Brush(danger?UiTokens.Danger:strong?UiTokens.TextPrimary:UiTokens.TextSecondary),VerticalAlignment=VerticalAlignment.Center,Margin=new Thickness(3),TextTrimming=TextTrimming.CharacterEllipsis};Grid.SetColumn(x,c);g.Children.Add(x);}private void Show(string t,bool e=false){_message.Text=t;_message.Foreground=UiTokens.Brush(e?UiTokens.Danger:UiTokens.Success);}
}

public sealed class SelectStocktakeLocationDialog : Window
{
    private readonly IReadOnlyList<SparePartWarehouseLocation> _locations;private readonly ComboBox _location=new();private readonly TextBox _scan=new(){Watermark="AXLOC:codice"};private readonly TextBlock _message=new();
    public SelectStocktakeLocationDialog(IReadOnlyList<SparePartWarehouseLocation> locations){_locations=locations;Title="Seleziona ubicazione";Width=500;Height=300;WindowStartupLocation=WindowStartupLocation.CenterOwner;_location.ItemsSource=locations.Select(x=>x.DisplayName).ToList();_location.SelectedIndex=0;_scan.KeyDown+=(_,e)=>{if(e.Key!=Key.Enter)return;e.Handled=true;var code=Normalize(_scan.Text);var index=locations.ToList().FindIndex(x=>string.Equals(x.Code,code,StringComparison.OrdinalIgnoreCase));if(index<0){_message.Text=$"Ubicazione non riconosciuta: {code}";return;}_location.SelectedIndex=index;};var create=new Button{Content="Crea sessione",Height=40};create.Click+=(_,_)=>{if(_location.SelectedIndex>=0)Close(_locations[_location.SelectedIndex]);};Content=new StackPanel{Margin=new Thickness(24),Spacing=10,Children={new TextBlock{Text="Ubicazione da inventariare",FontSize=23,FontWeight=FontWeight.Bold},new TextBlock{Text="Scansiona QR ubicazione"},_scan,new TextBlock{Text="Oppure seleziona"},_location,_message,create}};}
    private static string Normalize(string? x){var t=(x??"").Trim();return t.StartsWith("AXLOC:",StringComparison.OrdinalIgnoreCase)?t[6..].Trim():t;}
}

public sealed class LocationStocktakeSessionWindow : Window
{
    private readonly LocationStocktakeRepository _repository;private readonly SparePartLocationsRepository _locations;private readonly SparePartsInventoryRepository _inventory;private readonly int _id;
    private readonly StackPanel _rows=new();private readonly TextBlock _title=new(),_message=new(),_scanMessage=new();private readonly TextBox _scanner=new(){Watermark="AXPART:codice"};private readonly Dictionary<int,TextBox> _counts=new();private LocationStocktake? _session;
    public LocationStocktakeSessionWindow(LocationStocktakeRepository repository,SparePartLocationsRepository locations,SparePartsInventoryRepository inventory,int id){_repository=repository;_locations=locations;_inventory=inventory;_id=id;Title="Conteggio ubicazione";Width=960;Height=700;WindowStartupLocation=WindowStartupLocation.CenterOwner;_scanner.KeyDown+=Scan;Content=Build();Load();Opened+=(_,_)=>_scanner.Focus();}
    private Control Build(){var root=new DockPanel{Margin=new Thickness(24)};var actions=new StackPanel{Orientation=Orientation.Horizontal,Spacing=5};actions.Children.Add(Button("Salva",Save,true));actions.Children.Add(Button("Chiudi e riconcilia",CloseSession));var h=new Grid{ColumnDefinitions=new ColumnDefinitions("*,Auto"),Margin=new Thickness(0,0,0,10)};h.Children.Add(_title);Grid.SetColumn(actions,1);h.Children.Add(actions);DockPanel.SetDock(h,Dock.Top);root.Children.Add(h);_scanner.Margin=new Thickness(0,0,0,5);DockPanel.SetDock(_scanner,Dock.Top);root.Children.Add(_scanner);DockPanel.SetDock(_scanMessage,Dock.Top);root.Children.Add(_scanMessage);_message.Margin=new Thickness(0,5,0,8);DockPanel.SetDock(_message,Dock.Top);root.Children.Add(_message);root.Children.Add(new ScrollViewer{Content=_rows,VerticalScrollBarVisibility=Avalonia.Controls.Primitives.ScrollBarVisibility.Auto});return root;}
    private void Load(){_session=_repository.Get(_id);var location=_locations.GetLocations().FirstOrDefault(x=>x.Id==_session.LocationId);_title.Text=$"{_session.SessionNumber} · {location?.DisplayName} · contati {_session.CountedLines}/{_session.Lines.Count}";_title.FontSize=20;_title.FontWeight=FontWeight.Bold;_rows.Children.Clear();_counts.Clear();foreach(var line in _session.Lines){var count=new TextBox{Text=line.CountedQuantity?.ToString("N2")??"",Watermark="Da contare",Width=110,Tag=line.Id};count.KeyDown+=(_,e)=>{if(e.Key==Key.Enter){Save();_scanner.Text="";_scanner.Focus();}};_counts[line.Id]=count;_rows.Children.Add(new Border{BorderBrush=UiTokens.Brush(UiTokens.Border),BorderThickness=new Thickness(0,0,0,1),Padding=new Thickness(8),Child=new Grid{ColumnDefinitions=new ColumnDefinitions("130,*,120,120"),Children={Cell(line.PartCode,0,true),Cell(line.Description,1),Cell($"Attesa {line.ExpectedQuantity:N2}",2),count}}});Grid.SetColumn(count,3);}}
    private void Scan(object? sender,KeyEventArgs e){if(e.Key!=Key.Enter||_session is null)return;e.Handled=true;var raw=(_scanner.Text??"").Trim();var code=raw.StartsWith("AXPART:",StringComparison.OrdinalIgnoreCase)?raw[7..].Trim():raw;var line=_session.Lines.FirstOrDefault(x=>string.Equals(x.PartCode,code,StringComparison.OrdinalIgnoreCase));if(line is null){var item=_inventory.GetItems().FirstOrDefault(x=>string.Equals(x.PartCode,code,StringComparison.OrdinalIgnoreCase));if(item is not null){var positions=_locations.GetBalances().Where(x=>x.InventoryItemId==item.Id&&x.Quantity>0).Select(x=>_locations.GetLocations().FirstOrDefault(l=>l.Id==x.LocationId)?.Code).Where(x=>x is not null);Status($"Ricambio presente in altra ubicazione: {string.Join(", ",positions)}. Trasferimento suggerito.",true);}else Status($"Codice sconosciuto: {code}",true);_scanner.SelectAll();return;}var box=_counts[line.Id];if(!string.IsNullOrWhiteSpace(box.Text))Status("Ricambio già contato: verifica prima di modificare.",true);else Status($"{line.PartCode} trovato. Inserisci la quantità.",false);box.Focus();box.SelectAll();}
    private void Save(){try{if(_session is null)return;foreach(var line in _session.Lines){line.CountedQuantity=decimal.TryParse(_counts[line.Id].Text,out var q)&&q>=0?q:null;}_repository.SaveCounts(_id,_session.Lines);Status("Conteggi salvati.",false);Load();}catch(Exception ex){Status($"Errore salvataggio: {ex.Message}",true);}}
    private void CloseSession(){try{Save();_repository.Close(_id,_locations,_inventory);Status("Sessione chiusa e ubicazione riconciliata.",false);Load();}catch(Exception ex){Status($"Chiusura non eseguita: {ex.Message}",true);}}
    private static TextBlock Cell(string t,int c,bool strong=false){var x=new TextBlock{Text=t,FontWeight=strong?FontWeight.SemiBold:FontWeight.Normal,VerticalAlignment=VerticalAlignment.Center,Margin=new Thickness(3)};Grid.SetColumn(x,c);return x;}private static Button Button(string t,Action a,bool p=false){var b=new Button{Content=t,MinHeight=36,Background=UiTokens.Brush(p?UiTokens.BrandBlue:UiTokens.SurfaceAlt),Foreground=p?Brushes.White:UiTokens.Brush(UiTokens.TextPrimary)};b.Click+=(_,_)=>a();return b;}private void Status(string t,bool e){_scanMessage.Text=t;_scanMessage.Foreground=UiTokens.Brush(e?UiTokens.Danger:UiTokens.Success);}
}
