using System.Diagnostics;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Layout;
using Avalonia.Media;
using Accyourate.App.AssetManagement.Models;
using Accyourate.App.AssetManagement.Services;
using Accyourate.App.UIFramework.Tokens;

namespace Accyourate.App.AssetManagement;

public sealed class SparePartRmaWindow : Window
{
    private readonly SparePartRmaRepository _repository=new();private readonly SparePartsInventoryRepository _inventory=new();private readonly SparePartQuarantineRepository _quarantine=new();private readonly SparePartLocationsRepository _locations=new();private readonly MaintenancePurchasingRepository _purchasing=new();private readonly SupplierRmaValidationService _validation=new();
    private readonly StackPanel _rows=new(),_kpis=new(){Orientation=Orientation.Horizontal,Spacing=10};private readonly TextBlock _message=new(),_summary=new();private readonly TextBox _search=new(){Watermark="Cerca RMA, ricambio, tracking..."};private readonly ComboBox _status=new(),_deadline=new();
    public SparePartRmaWindow(){Title="RMA e resi ai fornitori";Width=1460;Height=780;MinWidth=1080;MinHeight=600;WindowStartupLocation=WindowStartupLocation.CenterOwner;_status.ItemsSource=new[]{"Tutti gli stati",SparePartRmaStatus.Open,SparePartRmaStatus.Authorized,SparePartRmaStatus.Shipped,SparePartRmaStatus.Resolved,SparePartRmaStatus.Closed,SparePartRmaStatus.Cancelled};_status.SelectedIndex=0;_deadline.ItemsSource=new[]{"Tutte le scadenze","In scadenza (7 gg)","Scadute","Spedite senza esito"};_deadline.SelectedIndex=0;_search.TextChanged+=(_,_)=>Load();_status.SelectionChanged+=(_,_)=>Load();_deadline.SelectionChanged+=(_,_)=>Load();Content=Build();new SparePartRmaReminderService().PublishDueNotifications();Load();}
    private Control Build(){var root=new DockPanel{Margin=new Thickness(24)};var head=new Grid{ColumnDefinitions=new ColumnDefinitions("*,Auto"),Margin=new Thickness(0,0,0,12)};Add(head,new StackPanel{Spacing=3,Children={new TextBlock{Text="RMA e resi ai fornitori",FontSize=28,FontWeight=FontWeight.Bold},new TextBlock{Text="Autorizzazioni, spedizioni, tracking, scadenze ed esiti.",Foreground=UiTokens.Brush(UiTokens.TextSecondary)}}},0);var headActions=new StackPanel{Orientation=Orientation.Horizontal,Spacing=8};headActions.Children.Add(Button("Dashboard audit",()=>new SupplierRmaAuditDashboardWindow().Show()));headActions.Children.Add(Button("Registro validazioni",()=>new SupplierRmaValidationRegisterWindow().Show()));headActions.Children.Add(Button("Nuova pratica",Create,true));Add(head,headActions,1);DockPanel.SetDock(head,Dock.Top);root.Children.Add(head);_kpis.Margin=new Thickness(0,0,0,10);DockPanel.SetDock(_kpis,Dock.Top);root.Children.Add(_kpis);var filters=new Grid{ColumnDefinitions=new ColumnDefinitions("*,210,210"),Margin=new Thickness(0,0,0,8)};Add(filters,_search,0);Add(filters,_status,1);Add(filters,_deadline,2);DockPanel.SetDock(filters,Dock.Top);root.Children.Add(filters);DockPanel.SetDock(_message,Dock.Top);root.Children.Add(_message);_summary.Margin=new Thickness(0,5,0,8);_summary.Foreground=UiTokens.Brush(UiTokens.TextSecondary);DockPanel.SetDock(_summary,Dock.Top);root.Children.Add(_summary);root.Children.Add(new ScrollViewer{Content=_rows,HorizontalScrollBarVisibility=Avalonia.Controls.Primitives.ScrollBarVisibility.Auto,VerticalScrollBarVisibility=Avalonia.Controls.Primitives.ScrollBarVisibility.Auto});return root;}
    private void Load(){try{var items=_inventory.GetItems().ToDictionary(x=>x.Id);var suppliers=_purchasing.GetSuppliers().ToDictionary(x=>x.Id);var selected=_status.SelectedItem?.ToString()??"Tutti gli stati";var deadline=_deadline.SelectedItem?.ToString()??"Tutte le scadenze";var q=(_search.Text??"").Trim();var all=_repository.GetAll();UpdateKpis(all);var values=all.Where(x=>selected=="Tutti gli stati"||x.Status==selected).Where(x=>MatchesDeadline(x,deadline)).Where(x=>{items.TryGetValue(x.InventoryItemId,out var i);suppliers.TryGetValue(x.SupplierId,out var s);return q.Length==0||$"{x.CaseNumber} {i?.PartCode} {i?.Description} {s?.Name} {x.TrackingNumber}".Contains(q,StringComparison.OrdinalIgnoreCase);}).ToList();_summary.Text=$"{values.Count} pratiche visualizzate · {values.Count(IsDueSoon)} in scadenza · {values.Count(IsOverdue)} scadute · costi EUR {values.Sum(x=>x.ShippingCost+x.ResolutionCost):N2}";_rows.Children.Clear();_rows.MinWidth=1340;_rows.Children.Add(Header());for(var i=0;i<values.Count;i++)_rows.Children.Add(Row(values[i],items,suppliers,i));}catch(Exception ex){Status(ex.Message,true);}}
    private Control Header(){var g=GridRow();var names=new[]{"Pratica","Ricambio","Fornitore","Qtà","Stato","Scadenza","Tracking","Esito","Costi","Azioni"};for(var i=0;i<names.Length;i++)Text(g,names[i],i,true);return new Border{Background=UiTokens.Brush(UiTokens.SurfaceAlt),Padding=new Thickness(8),Child=g};}
    private Control Row(SparePartRmaCase x,IReadOnlyDictionary<int,SparePartInventoryItem> items,IReadOnlyDictionary<int,MaintenanceSupplier> suppliers,int index){items.TryGetValue(x.InventoryItemId,out var item);suppliers.TryGetValue(x.SupplierId,out var supplier);var g=GridRow();Text(g,x.CaseNumber,0,true);Text(g,item is null?$"#{x.InventoryItemId}":$"{item.PartCode} · {item.Description}",1);Text(g,supplier?.Name??"—",2);Text(g,x.Quantity.ToString("N2"),3,true);Add(g,Badge(x.Status,IsOverdue(x)),4);Text(g,Date(x.DueDate),5);Text(g,string.IsNullOrWhiteSpace(x.TrackingNumber)?"—":x.TrackingNumber,6);Text(g,string.IsNullOrWhiteSpace(x.Outcome)?"—":x.Outcome,7);Text(g,$"EUR {x.ShippingCost+x.ResolutionCost:N2}",8);var actions=new StackPanel{Orientation=Orientation.Horizontal,Spacing=3};if(x.Status==SparePartRmaStatus.Open)actions.Children.Add(Button("Autorizza",()=>Authorize(x)));if(x.Status==SparePartRmaStatus.Authorized)actions.Children.Add(Button("Spedisci",()=>Ship(x)));if(x.Status==SparePartRmaStatus.Shipped)actions.Children.Add(Button("Esito",()=>Resolve(x)));if(x.Status==SparePartRmaStatus.Resolved)actions.Children.Add(Button(x.Outcome==SparePartRmaOutcome.Refund?"Chiudi":"Ricevi",()=>Close(x),true));if(x.SupplierId>0)actions.Children.Add(Button("Portale",()=>new SupplierRmaPortalWindow(x.SupplierId,x.Id).Show()));actions.Children.Add(Button("PDF",()=>Pdf(x,item,supplier)));actions.Children.Add(Button("Fascicolo",()=>Dossier(x,item,supplier),true));actions.Children.Add(Button("Valida",()=>ValidateDossier(x,item,supplier)));Add(g,actions,9);return new Border{Background=UiTokens.Brush(index%2==0?UiTokens.Surface:UiTokens.SurfaceAlt),BorderBrush=UiTokens.Brush(UiTokens.Border),BorderThickness=new Thickness(0,0,0,1),Padding=new Thickness(8,6),Child=g};}
    private async void Create(){var eligible=_quarantine.GetAll().Where(x=>x.Status==SparePartQuarantineStatus.SupplierReturn).ToList();if(eligible.Count==0){Status("Nessun materiale valutato come reso al fornitore.",true);return;}var items=_inventory.GetItems().ToDictionary(x=>x.Id);var suppliers=_purchasing.GetSuppliers();var owner=TopLevel.GetTopLevel(this) as Window;if(owner is null)return;var r=await new RmaCreateDialog(eligible,items,suppliers).ShowDialog<(SparePartQuarantineItem Item,int SupplierId,string Notes)?>(owner);if(r is null)return;Run(()=>_repository.Create(r.Value.Item.Id,r.Value.Item.InventoryItemId,r.Value.Item.Quantity,r.Value.SupplierId,r.Value.Notes),"Pratica RMA creata.");}
    private async void Authorize(SparePartRmaCase x){var suppliers=_purchasing.GetSuppliers();var r=await Dialog("Autorizza RMA",suppliers,true,false,false);if(r is null)return;Run(()=>_repository.Authorize(x.Id,r.Value.SupplierId,r.Value.First,r.Value.Date,r.Value.Notes),"RMA autorizzata.");}
    private async void Ship(SparePartRmaCase x){var r=await Dialog("Registra spedizione",Array.Empty<MaintenanceSupplier>(),false,true,false);if(r is null)return;Run(()=>_repository.Ship(x.Id,r.Value.First,r.Value.Second,r.Value.Cost),"Spedizione registrata.");}
    private async void Resolve(SparePartRmaCase x){var r=await Dialog("Registra esito",Array.Empty<MaintenanceSupplier>(),false,false,true);if(r is null)return;Run(()=>_repository.Resolve(x.Id,r.Value.First,r.Value.Cost,r.Value.Notes),"Esito registrato.");}
    private async void Close(SparePartRmaCase x){var locations=_locations.GetLocations().Where(y=>y.IsActive).ToList();var owner=TopLevel.GetTopLevel(this) as Window;if(owner is null)return;var r=await new RmaCloseDialog(x,locations).ShowDialog<(int LocationId,string Notes)?>(owner);if(r is null)return;Run(()=>_repository.Close(x.Id,r.Value.LocationId,r.Value.Notes,Environment.UserName),"Pratica RMA chiusa.");}
    private async Task<(int SupplierId,string First,string Second,string Date,decimal Cost,string Notes)?> Dialog(string title,IReadOnlyList<MaintenanceSupplier> suppliers,bool auth,bool shipping,bool outcome){var owner=TopLevel.GetTopLevel(this) as Window;return owner is null?null:await new RmaActionDialog(title,suppliers,auth,shipping,outcome).ShowDialog<(int,string,string,string,decimal,string)?>(owner);}
    private void Pdf(SparePartRmaCase x,SparePartInventoryItem? item,MaintenanceSupplier? supplier){try{if(item is null)throw new InvalidOperationException("Ricambio non trovato.");var path=new SparePartRmaPdfService().Generate(x,item,supplier);Process.Start(new ProcessStartInfo{FileName=path,UseShellExecute=true});Status($"PDF creato: {path}",false);}catch(Exception ex){Status(ex.Message,true);}}
    private void Dossier(SparePartRmaCase x,SparePartInventoryItem? item,MaintenanceSupplier? supplier){try{if(item is null)throw new InvalidOperationException("Ricambio non trovato.");var path=new SupplierRmaDossierService().Generate(x,item,supplier);Process.Start(new ProcessStartInfo{FileName=path,UseShellExecute=true});Status($"Fascicolo creato: {path}",false);}catch(Exception ex){Status($"Fascicolo non creato: {ex.Message}",true);}}
    private async void ValidateDossier(SparePartRmaCase x,SparePartInventoryItem? item,MaintenanceSupplier? supplier){try{var result=_validation.Validate(x,item,supplier);var owner=TopLevel.GetTopLevel(this) as Window;if(owner is null)return;var notes=await new RmaValidationDialog(x,result).ShowDialog<string?>(owner);if(notes is null)return;_validation.RecordClosure(x,result,notes,Environment.UserName);if(item is not null)new SupplierRmaDossierService().Generate(x,item,supplier);Status("Fascicolo validato, chiusura registrata e archivio definitivo rigenerato.",false);}catch(Exception ex){Status($"Validazione non completata: {ex.Message}",true);}}
    private void Run(Func<int> action,string success){try{action();Status(success,false);Load();}catch(Exception ex){Status(ex.Message,true);}}private void Run(Action action,string success){try{action();Status(success,false);Load();}catch(Exception ex){Status(ex.Message,true);}}
    private void UpdateKpis(IReadOnlyList<SparePartRmaCase> values){_kpis.Children.Clear();_kpis.Children.Add(Kpi("Pratiche aperte",values.Count(IsOpenCase),UiTokens.BrandBlue));_kpis.Children.Add(Kpi("In scadenza",values.Count(IsDueSoon),UiTokens.Warning));_kpis.Children.Add(Kpi("Scadute",values.Count(IsOverdue),UiTokens.Danger));_kpis.Children.Add(Kpi("Spedite senza esito",values.Count(x=>x.Status==SparePartRmaStatus.Shipped),UiTokens.Warning));}
    private static Control Kpi(string label,int value,string color)=>new Border{Width=205,Padding=new Thickness(14,10),Background=UiTokens.Brush(UiTokens.Surface),BorderBrush=UiTokens.Brush(UiTokens.Border),BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(12),Child=new StackPanel{Spacing=2,Children={new TextBlock{Text=value.ToString(),FontSize=24,FontWeight=FontWeight.Bold,Foreground=UiTokens.Brush(color)},new TextBlock{Text=label,Foreground=UiTokens.Brush(UiTokens.TextSecondary)}}}};
    private static bool MatchesDeadline(SparePartRmaCase item,string filter)=>filter switch{"In scadenza (7 gg)"=>IsDueSoon(item),"Scadute"=>IsOverdue(item),"Spedite senza esito"=>item.Status==SparePartRmaStatus.Shipped,_=>true};
    private static bool IsOpenCase(SparePartRmaCase item)=>item.Status is not (SparePartRmaStatus.Closed or SparePartRmaStatus.Cancelled);
    private static bool IsDueSoon(SparePartRmaCase item)=>IsOpenCase(item)&&DateTime.TryParse(item.DueDate,out var due)&&(due.Date-DateTime.Today).Days is >=0 and <=7;
    private static bool IsOverdue(SparePartRmaCase x)=>x.Status is not (SparePartRmaStatus.Closed or SparePartRmaStatus.Cancelled)&&DateTime.TryParse(x.DueDate,out var d)&&d.Date<DateTime.Today;
    private static string Date(string value)=>DateTime.TryParse(value,out var d)?d.ToString("dd/MM/yyyy"):"—";private static Grid GridRow()=>new(){ColumnDefinitions=new ColumnDefinitions("145,220,160,65,120,100,145,115,100,440")};
    private static Control Badge(string status,bool overdue){var color=overdue?UiTokens.Danger:status switch{SparePartRmaStatus.Closed=>UiTokens.Success,SparePartRmaStatus.Shipped=>UiTokens.Warning,SparePartRmaStatus.Cancelled=>UiTokens.Danger,_=>UiTokens.BrandBlue};return new Border{BorderBrush=UiTokens.Brush(color),BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(8),Padding=new Thickness(5,3),Child=new TextBlock{Text=overdue?"SCADUTA":status,Foreground=UiTokens.Brush(color),HorizontalAlignment=HorizontalAlignment.Center,FontWeight=FontWeight.SemiBold}};}
    private static Button Button(string text,Action action,bool primary=false){var b=new Button{Content=text,MinHeight=34,Background=UiTokens.Brush(primary?UiTokens.BrandBlue:UiTokens.SurfaceAlt),Foreground=primary?Brushes.White:UiTokens.Brush(UiTokens.TextPrimary)};b.Click+=(_,_)=>action();return b;}private static void Text(Grid g,string v,int c,bool strong=false)=>Add(g,new TextBlock{Text=string.IsNullOrWhiteSpace(v)?"—":v,FontWeight=strong?FontWeight.SemiBold:FontWeight.Normal,VerticalAlignment=VerticalAlignment.Center,TextTrimming=TextTrimming.CharacterEllipsis,Margin=new Thickness(3)},c);private static void Add(Grid g,Control c,int col){c.Margin=new Thickness(0,0,6,0);Grid.SetColumn(c,col);g.Children.Add(c);}private void Status(string text,bool error){_message.Text=text;_message.Foreground=UiTokens.Brush(error?UiTokens.Danger:UiTokens.Success);}
}

internal sealed class RmaCreateDialog:Window{private readonly IReadOnlyList<SparePartQuarantineItem> _cases;private readonly IReadOnlyList<MaintenanceSupplier> _suppliers;private readonly ComboBox _case=new(),_supplier=new();private readonly TextBox _notes=new();public RmaCreateDialog(IReadOnlyList<SparePartQuarantineItem> cases,IReadOnlyDictionary<int,SparePartInventoryItem> items,IReadOnlyList<MaintenanceSupplier> suppliers){_cases=cases;_suppliers=suppliers;Title="Nuova pratica RMA";Width=560;Height=360;WindowStartupLocation=WindowStartupLocation.CenterOwner;_case.ItemsSource=cases.Select(x=>items.TryGetValue(x.InventoryItemId,out var i)?$"{x.CaseNumber} · {i.PartCode} · {x.Quantity:N2}":x.CaseNumber).ToList();_supplier.ItemsSource=suppliers.Select(x=>x.Name).ToList();_case.SelectedIndex=0;_supplier.SelectedIndex=suppliers.Count>0?0:-1;Content=Form("Nuova pratica RMA",("Materiale",_case),("Fornitore",_supplier),("Note",_notes),Save);}private void Save(){if(_case.SelectedIndex<0||_supplier.SelectedIndex<0)return;Close((_cases[_case.SelectedIndex],_suppliers[_supplier.SelectedIndex].Id,_notes.Text??""));}internal static Control Form(string title,(string,Control) a,(string,Control) b,(string,Control) c,Action save){var p=new StackPanel{Margin=new Thickness(24),Spacing=9,Children={new TextBlock{Text=title,FontSize=24,FontWeight=FontWeight.Bold}}};foreach(var x in new[]{a,b,c})p.Children.Add(new StackPanel{Spacing=3,Children={new TextBlock{Text=x.Item1,FontWeight=FontWeight.SemiBold},x.Item2}});p.Children.Add(SparePartRmaWindowButton("Conferma",save));return p;}internal static Button SparePartRmaWindowButton(string t,Action a){var b=new Button{Content=t,Height=40};b.Click+=(_,_)=>a();return b;}}
internal sealed class RmaActionDialog:Window{private readonly IReadOnlyList<MaintenanceSupplier> _suppliers;private readonly ComboBox _supplier=new(),_outcome=new(){ItemsSource=new[]{SparePartRmaOutcome.Repair,SparePartRmaOutcome.Replacement,SparePartRmaOutcome.Refund},SelectedIndex=0};private readonly TextBox _first=new(),_second=new(),_date=new(){Text=DateTime.Today.AddDays(30).ToString("yyyy-MM-dd")},_cost=new(){Text="0"},_notes=new();private readonly bool _auth,_shipping,_result;public RmaActionDialog(string title,IReadOnlyList<MaintenanceSupplier> suppliers,bool auth,bool shipping,bool result){_suppliers=suppliers;_auth=auth;_shipping=shipping;_result=result;Title=title;Width=540;Height=520;WindowStartupLocation=WindowStartupLocation.CenterOwner;_supplier.ItemsSource=suppliers.Select(x=>x.Name).ToList();_supplier.SelectedIndex=suppliers.Count>0?0:-1;var p=new StackPanel{Margin=new Thickness(24),Spacing=8,Children={new TextBlock{Text=title,FontSize=24,FontWeight=FontWeight.Bold}}};if(auth){Field(p,"Fornitore",_supplier);Field(p,"Numero autorizzazione",_first);Field(p,"Scadenza (AAAA-MM-GG)",_date);}if(shipping){Field(p,"Corriere",_first);Field(p,"Tracking",_second);Field(p,"Costo spedizione",_cost);}if(result){Field(p,"Esito",_outcome);Field(p,"Costo risoluzione",_cost);}Field(p,"Note",_notes);p.Children.Add(RmaCreateDialog.SparePartRmaWindowButton("Conferma",Save));Content=new ScrollViewer{Content=p};}private void Save(){if(!decimal.TryParse(_cost.Text,out var cost))cost=0;var first=_result?_outcome.SelectedItem?.ToString()??SparePartRmaOutcome.Repair:_first.Text??"";Close((_supplier.SelectedIndex>=0?_suppliers[_supplier.SelectedIndex].Id:0,first,_second.Text??"",_date.Text??"",cost,_notes.Text??""));}private static void Field(StackPanel p,string name,Control c)=>p.Children.Add(new StackPanel{Spacing=3,Children={new TextBlock{Text=name,FontWeight=FontWeight.SemiBold},c}});}
internal sealed class RmaCloseDialog:Window{private readonly SparePartRmaCase _case;private readonly IReadOnlyList<SparePartWarehouseLocation> _locations;private readonly ComboBox _location=new();private readonly TextBox _notes=new();public RmaCloseDialog(SparePartRmaCase value,IReadOnlyList<SparePartWarehouseLocation> locations){_case=value;_locations=locations;Title="Chiudi pratica RMA";Width=520;Height=330;WindowStartupLocation=WindowStartupLocation.CenterOwner;_location.ItemsSource=locations.Select(x=>x.DisplayName).ToList();_location.SelectedIndex=locations.Count>0?0:-1;_location.IsEnabled=value.Outcome!=SparePartRmaOutcome.Refund;Content=RmaCreateDialog.Form("Ricezione ed esito",("Esito",new TextBlock{Text=value.Outcome}), ("Ubicazione ricezione",_location),("Note chiusura",_notes),Save);}private void Save(){var location=_case.Outcome==SparePartRmaOutcome.Refund?0:_location.SelectedIndex>=0?_locations[_location.SelectedIndex].Id:0;Close((location,_notes.Text??""));}}

internal sealed class RmaValidationDialog : Window
{
    private readonly SupplierRmaValidationResult _result;
    private readonly TextBox _notes = new() { AcceptsReturn = true, TextWrapping = TextWrapping.Wrap, MinHeight = 80 };

    public RmaValidationDialog(SparePartRmaCase rma, SupplierRmaValidationResult result)
    {
        _result = result;
        Title = "Validazione fascicolo RMA";
        Width = 720; Height = 720; MinWidth = 620; MinHeight = 560;
        WindowStartupLocation = WindowStartupLocation.CenterOwner;
        var root = new StackPanel { Margin = new Thickness(24), Spacing = 12 };
        root.Children.Add(new TextBlock { Text = $"Validazione · {rma.CaseNumber}", FontSize = 25, FontWeight = FontWeight.Bold });
        var statusColor = result.CanClose ? UiTokens.Success : UiTokens.Warning;
        root.Children.Add(new Border { Background = UiTokens.Brush(UiTokens.SurfaceAlt), BorderBrush = UiTokens.Brush(statusColor), BorderThickness = new Thickness(1), CornerRadius = new CornerRadius(10), Padding = new Thickness(12), Child = new TextBlock { Text = $"Esito: {result.Status}", Foreground = UiTokens.Brush(statusColor), FontWeight = FontWeight.Bold } });
        var rows = new StackPanel { Spacing = 5 };
        foreach (var item in result.Items)
        {
            var grid = new Grid { ColumnDefinitions = new ColumnDefinitions("34,190,*,90") };
            Add(grid, new TextBlock { Text = item.IsValid ? "✓" : "!", Foreground = UiTokens.Brush(item.IsValid ? UiTokens.Success : UiTokens.Danger), FontWeight = FontWeight.Bold, VerticalAlignment = VerticalAlignment.Center }, 0);
            Add(grid, new TextBlock { Text = item.Label, FontWeight = FontWeight.SemiBold, VerticalAlignment = VerticalAlignment.Center }, 1);
            Add(grid, new TextBlock { Text = item.Detail, TextWrapping = TextWrapping.Wrap, Foreground = UiTokens.Brush(UiTokens.TextSecondary), VerticalAlignment = VerticalAlignment.Center }, 2);
            Add(grid, new TextBlock { Text = item.IsRequired ? "Obbligatorio" : "Consigliato", FontSize = 11, Foreground = UiTokens.Brush(UiTokens.TextSecondary), VerticalAlignment = VerticalAlignment.Center }, 3);
            rows.Children.Add(new Border { Padding = new Thickness(8), Background = UiTokens.Brush(UiTokens.Surface), BorderBrush = UiTokens.Brush(UiTokens.Border), BorderThickness = new Thickness(0, 0, 0, 1), Child = grid });
        }
        root.Children.Add(new ScrollViewer { Content = rows, MaxHeight = 390, VerticalScrollBarVisibility = Avalonia.Controls.Primitives.ScrollBarVisibility.Auto });
        root.Children.Add(new TextBlock { Text = "Note di validazione", FontWeight = FontWeight.SemiBold });
        root.Children.Add(_notes);
        if (!result.CanClose) root.Children.Add(new TextBlock { Text = "Completa gli elementi obbligatori indicati prima di registrare la chiusura del fascicolo.", TextWrapping = TextWrapping.Wrap, Foreground = UiTokens.Brush(UiTokens.Danger) });
        var actions = new StackPanel { Orientation = Orientation.Horizontal, Spacing = 8, HorizontalAlignment = HorizontalAlignment.Right };
        var cancel = new Button { Content = "Chiudi", MinWidth = 100 }; cancel.Click += (_, _) => Close(null);
        var save = new Button { Content = "Registra chiusura", MinWidth = 150, IsEnabled = result.CanClose, Background = UiTokens.Brush(UiTokens.BrandBlue), Foreground = Brushes.White }; save.Click += (_, _) => Close(_notes.Text ?? "");
        actions.Children.Add(cancel); actions.Children.Add(save); root.Children.Add(actions);
        Content = root;
    }

    private static void Add(Grid grid, Control control, int column) { Grid.SetColumn(control, column); control.Margin = new Thickness(0, 0, 8, 0); grid.Children.Add(control); }
}
