using System.Diagnostics;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Layout;
using Avalonia.Media;
using Accyourate.App.AssetManagement.Models;
using Accyourate.App.AssetManagement.Services;
using Accyourate.App.UIFramework.Tokens;

namespace Accyourate.App.AssetManagement;

public sealed class SupplierRmaDetailWindow:Window
{
    private readonly int _supplierId;private readonly SparePartRmaAnalyticsService _analytics=new();private readonly SupplierRmaEvaluationRepository _evaluations=new();private readonly StackPanel _content=new();private readonly ComboBox _rating=new(){ItemsSource=new[]{"1 - Insufficiente","2 - Debole","3 - Adeguato","4 - Buono","5 - Eccellente"}};private readonly TextBox _notes=new(){AcceptsReturn=true,MinHeight=90,TextWrapping=TextWrapping.Wrap};private readonly TextBlock _message=new();
    public SupplierRmaDetailWindow(int supplierId){_supplierId=supplierId;Title="Dettaglio fornitore RMA";Width=1100;Height=780;MinWidth=900;MinHeight=600;WindowStartupLocation=WindowStartupLocation.CenterOwner;Content=new ScrollViewer{Content=_content,VerticalScrollBarVisibility=Avalonia.Controls.Primitives.ScrollBarVisibility.Auto};Load();}
    private void Load(){_content.Children.Clear();_content.Margin=new Thickness(24);_content.Spacing=12;var performance=_analytics.GetPerformance().FirstOrDefault(x=>x.SupplierId==_supplierId);var supplier=_analytics.GetSupplier(_supplierId);if(performance is null||supplier is null){_content.Children.Add(new TextBlock{Text="Fornitore non disponibile."});return;}_rating.SelectedIndex=performance.ManualRating>0?performance.ManualRating-1:-1;_notes.Text=performance.ManualNotes;var header=new Grid{ColumnDefinitions=new ColumnDefinitions("*,Auto")};Add(header,new StackPanel{Spacing=3,Children={new TextBlock{Text=supplier.Name,FontSize=28,FontWeight=FontWeight.Bold},new TextBlock{Text=$"{supplier.ContactPerson} · {supplier.Email} · {supplier.Phone}",Foreground=UiTokens.Brush(UiTokens.TextSecondary)}}},0);var actions=new StackPanel{Orientation=Orientation.Horizontal,Spacing=8};actions.Children.Add(Button("PDF",()=>Pdf(supplier,performance)));actions.Children.Add(Button("Salva valutazione",Save,true));Add(header,actions,1);_content.Children.Add(header);var kpis=new StackPanel{Orientation=Orientation.Horizontal,Spacing=10};kpis.Children.Add(Kpi("Affidabilità",$"{performance.ReliabilityScore:N0}/100",UiTokens.BrandBlue));kpis.Children.Add(Kpi("SLA",performance.EvaluatedSlaCases==0?"—":$"{performance.SlaCompliancePercent:N0}%",UiTokens.Success));kpis.Children.Add(Kpi("Tempo medio",performance.ClosedCases==0?"—":$"{performance.AverageResolutionDays:N1} gg",UiTokens.Warning));kpis.Children.Add(Kpi("Costi",$"EUR {performance.TotalCost:N2}",UiTokens.Warning));_content.Children.Add(kpis);_content.Children.Add(Section("Valutazione manuale",new Grid{ColumnDefinitions=new ColumnDefinitions("220,*"),Children={Wrap("Valutazione 1-5",_rating,0),Wrap("Note del responsabile acquisti",_notes,1)}}));_content.Children.Add(_message);_content.Children.Add(Section("Andamento e risultati",new TextBlock{Text=$"Pratiche: {performance.TotalCases} · Aperte: {performance.ActiveCases} · Scadute: {performance.OverdueCases}\nRiparazioni: {performance.RepairCases} · Sostituzioni: {performance.ReplacementCases} · Rimborsi: {performance.RefundCases}\nPunteggio combinato: {performance.CombinedScore:N0}/100",TextWrapping=TextWrapping.Wrap}));_content.Children.Add(History(_analytics.GetSupplierCases(_supplierId)));}
    private Control History(IReadOnlyList<SparePartRmaCase> cases){var rows=new StackPanel{Spacing=0};var header=new Grid{ColumnDefinitions=new ColumnDefinitions("150,110,120,120,*,120")};foreach(var x in new[]{("Pratica",0),("Apertura",1),("Stato",2),("Esito",3),("Tracking",4),("Costo",5)})Text(header,x.Item1,x.Item2,true);rows.Children.Add(new Border{Background=UiTokens.Brush(UiTokens.SurfaceAlt),Padding=new Thickness(8),Child=header});for(var i=0;i<cases.Count;i++){var x=cases[i];var row=new Grid{ColumnDefinitions=new ColumnDefinitions("150,110,120,120,*,120")};Text(row,x.CaseNumber,0,true);Text(row,Date(x.CreatedAt),1);Text(row,x.Status,2);Text(row,Dash(x.Outcome),3);Text(row,Dash(x.TrackingNumber),4);Text(row,$"EUR {x.ShippingCost+x.ResolutionCost:N2}",5);rows.Children.Add(new Border{Background=UiTokens.Brush(i%2==0?UiTokens.Surface:UiTokens.SurfaceAlt),BorderBrush=UiTokens.Brush(UiTokens.Border),BorderThickness=new Thickness(0,0,0,1),Padding=new Thickness(8),Child=row});}return Section("Storico pratiche RMA",rows);}
    private void Save(){try{if(_rating.SelectedIndex<0)throw new InvalidOperationException("Seleziona una valutazione da 1 a 5.");_evaluations.Save(_supplierId,_rating.SelectedIndex+1,_notes.Text??"",Environment.UserName);_message.Text="Valutazione salvata.";_message.Foreground=UiTokens.Brush(UiTokens.Success);Load();}catch(Exception ex){_message.Text=ex.Message;_message.Foreground=UiTokens.Brush(UiTokens.Danger);}}
    private void Pdf(MaintenanceSupplier supplier,SupplierRmaPerformance performance){try{var path=new SupplierRmaReportPdfService().Generate(supplier,performance,_analytics.GetSupplierCases(_supplierId));Process.Start(new ProcessStartInfo{FileName=path,UseShellExecute=true});_message.Text=$"Report creato: {path}";_message.Foreground=UiTokens.Brush(UiTokens.Success);}catch(Exception ex){_message.Text=ex.Message;_message.Foreground=UiTokens.Brush(UiTokens.Danger);}}
    private static Control Section(string title,Control content)=>new Border{Padding=new Thickness(14),Background=UiTokens.Brush(UiTokens.Surface),BorderBrush=UiTokens.Brush(UiTokens.Border),BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(12),Child=new StackPanel{Spacing=8,Children={new TextBlock{Text=title,FontSize=17,FontWeight=FontWeight.Bold},content}}};private static Control Kpi(string label,string value,string color)=>new Border{Width=230,Padding=new Thickness(12),Background=UiTokens.Brush(UiTokens.Surface),BorderBrush=UiTokens.Brush(UiTokens.Border),BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(12),Child=new StackPanel{Children={new TextBlock{Text=value,FontSize=22,FontWeight=FontWeight.Bold,Foreground=UiTokens.Brush(color)},new TextBlock{Text=label,Foreground=UiTokens.Brush(UiTokens.TextSecondary)}}}};
    private static Control Wrap(string label,Control control,int col){var panel=new StackPanel{Spacing=3,Margin=new Thickness(0,0,10,0),Children={new TextBlock{Text=label,FontWeight=FontWeight.SemiBold},control}};Grid.SetColumn(panel,col);return panel;}private static Button Button(string text,Action action,bool primary=false){var b=new Button{Content=text,Padding=new Thickness(12,8),Background=UiTokens.Brush(primary?UiTokens.BrandBlue:UiTokens.SurfaceAlt),Foreground=primary?Brushes.White:UiTokens.Brush(UiTokens.TextPrimary)};b.Click+=(_,_)=>action();return b;}private static string Dash(string value)=>string.IsNullOrWhiteSpace(value)?"—":value;private static string Date(string value)=>DateTime.TryParse(value,out var d)?d.ToString("dd/MM/yyyy"):value;private static void Text(Grid g,string value,int col,bool strong=false)=>Add(g,new TextBlock{Text=value,FontWeight=strong?FontWeight.SemiBold:FontWeight.Normal,VerticalAlignment=VerticalAlignment.Center,TextTrimming=TextTrimming.CharacterEllipsis},col);private static void Add(Grid g,Control c,int col){c.Margin=new Thickness(0,0,8,0);Grid.SetColumn(c,col);g.Children.Add(c);}
}
