using System.Diagnostics;
using System.IO.Compression;
using System.Text;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Layout;
using Avalonia.Media;
using Avalonia.Platform.Storage;
using Accyourate.App.AssetManagement.Models;
using Accyourate.App.AssetManagement.Services;
using Accyourate.App.UIFramework.Tokens;

namespace Accyourate.App.AssetManagement;

public sealed class SupplierCommunicationArchiveWindow:Window
{
    private readonly SupplierPortalInteraction _interaction;private readonly SupplierRmaPortalRepository _repository;private readonly TextBox _search=new(){Watermark="Cerca nome file, categoria o note..."};private readonly ComboBox _category=new(){ItemsSource=new[]{"Tutte le categorie","Documento","E-mail","Conferma fornitore","Documento RMA","Fattura / nota credito","Altro"},SelectedIndex=0};private readonly StackPanel _rows=new();private readonly TextBlock _summary=new();
    public SupplierCommunicationArchiveWindow(SupplierPortalInteraction interaction,SupplierRmaPortalRepository repository){_interaction=interaction;_repository=repository;Title="Fascicolo comunicazione";Width=1050;Height=700;WindowStartupLocation=WindowStartupLocation.CenterOwner;Content=Build();_search.TextChanged+=(_,_)=>Refresh();_category.SelectionChanged+=(_,_)=>Refresh();Refresh();}
    private Control Build(){var root=new StackPanel{Margin=new Thickness(24),Spacing=12};var head=new Grid{ColumnDefinitions=new ColumnDefinitions("*,Auto")};head.Children.Add(new StackPanel{Spacing=3,Children={new TextBlock{Text="Fascicolo comunicazione",FontSize=27,FontWeight=FontWeight.Bold},new TextBlock{Text=$"{_interaction.SupplierName} · {_interaction.Subject}",Foreground=UiTokens.Brush(UiTokens.TextSecondary),TextWrapping=TextWrapping.Wrap}}});var actions=new StackPanel{Orientation=Orientation.Horizontal,Spacing=8};actions.Children.Add(Button("Aggiungi file",AddFiles,true));actions.Children.Add(Button("Esporta fascicolo",Export));Grid.SetColumn(actions,1);head.Children.Add(actions);root.Children.Add(head);var filters=new Grid{ColumnDefinitions=new ColumnDefinitions("*,230")};Add(filters,_search,0);Add(filters,_category,1);root.Children.Add(filters);root.Children.Add(_summary);root.Children.Add(new ScrollViewer{Content=_rows,HorizontalScrollBarVisibility=Avalonia.Controls.Primitives.ScrollBarVisibility.Auto});return new ScrollViewer{Content=root,VerticalScrollBarVisibility=Avalonia.Controls.Primitives.ScrollBarVisibility.Auto};}
    private IReadOnlyList<SupplierPortalAttachment> Values(){var q=(_search.Text??"").Trim();var category=_category.SelectedItem?.ToString()??"Tutte le categorie";return _repository.GetAttachments(_interaction.SupplierId).Where(x=>x.InteractionId==_interaction.Id||(_interaction.RmaId>0&&x.RmaId==_interaction.RmaId)).Where(x=>q.Length==0||$"{x.FileName} {x.Category} {x.Notes}".Contains(q,StringComparison.OrdinalIgnoreCase)).Where(x=>category=="Tutte le categorie"||x.Category==category).ToList();}
    private void Refresh(){var values=Values();_summary.Text=$"{values.Count} file · {values.Count(x=>!x.IsAvailable)} mancanti";_summary.Foreground=UiTokens.Brush(values.Any(x=>!x.IsAvailable)?UiTokens.Danger:UiTokens.TextSecondary);_rows.Children.Clear();var h=GridRow();Text(h,"Categoria",0,true);Text(h,"File",1,true);Text(h,"Note",2,true);Text(h,"Data",3,true);Text(h,"Stato",4,true);Text(h,"Azioni",5,true);_rows.Children.Add(new Border{Padding=new Thickness(8),Background=UiTokens.Brush(UiTokens.SurfaceAlt),Child=h});for(var i=0;i<values.Count;i++){var x=values[i];var g=GridRow();Text(g,x.Category,0,true);Text(g,x.FileName,1,true);Text(g,x.Notes,2);Text(g,Date(x.CreatedAt),3);Text(g,x.IsAvailable?"Disponibile":"File mancante",4,!x.IsAvailable);var open=Button("Apri",()=>Open(x.StoredPath),true);open.IsEnabled=x.IsAvailable;Add(g,open,5);_rows.Children.Add(new Border{Padding=new Thickness(8,7),Background=UiTokens.Brush(i%2==0?UiTokens.Surface:UiTokens.SurfaceAlt),BorderBrush=UiTokens.Brush(UiTokens.Border),BorderThickness=new Thickness(0,0,0,1),Child=g});}if(values.Count==0)_rows.Children.Add(new TextBlock{Text="Nessun allegato nel fascicolo.",Margin=new Thickness(12),Foreground=UiTokens.Brush(UiTokens.TextSecondary)});}
    private async void AddFiles(){var files=await StorageProvider.OpenFilePickerAsync(new FilePickerOpenOptions{Title="Seleziona uno o più allegati",AllowMultiple=true});var paths=files.Select(x=>x.TryGetLocalPath()).Where(x=>!string.IsNullOrWhiteSpace(x)).Cast<string>().ToList();if(paths.Count==0)return;var info=await new SupplierCommunicationAttachmentDialog().ShowDialog<(string Category,string Notes)?>(this);if(info is null)return;_repository.AttachFilesToCommunication(_interaction,paths,info.Value.Category,info.Value.Notes);Refresh();}
    private async void Export(){var values=Values().Where(x=>x.IsAvailable).ToList();var file=await StorageProvider.SaveFilePickerAsync(new FilePickerSaveOptions{Title="Esporta fascicolo comunicazione",SuggestedFileName=$"Fascicolo-{_interaction.SupplierName}-{_interaction.Id}.zip",FileTypeChoices=new[]{new FilePickerFileType("Archivio ZIP"){Patterns=new[]{"*.zip"}}}});var path=file?.TryGetLocalPath();if(string.IsNullOrWhiteSpace(path))return;if(File.Exists(path))File.Delete(path);using var archive=ZipFile.Open(path,ZipArchiveMode.Create);var metadata=new StringBuilder();metadata.AppendLine("Categoria;File;Note;Data");foreach(var x in values){var entryName=$"Allegati/{x.Id}-{Safe(x.FileName)}";archive.CreateEntryFromFile(x.StoredPath,entryName,CompressionLevel.Optimal);metadata.AppendLine(string.Join(";",new[]{x.Category,x.FileName,x.Notes,Date(x.CreatedAt)}.Select(Csv)));}var info=archive.CreateEntry("indice.csv");using var writer=new StreamWriter(info.Open(),new UTF8Encoding(true));writer.Write(metadata.ToString());}
    private static void Open(string path){if(File.Exists(path))Process.Start(new ProcessStartInfo{FileName=path,UseShellExecute=true});}
    private static Grid GridRow()=>new(){MinWidth=940,ColumnDefinitions=new ColumnDefinitions("160,260,*,130,130,100")};private static string Date(string value)=>DateTime.TryParse(value,out var d)?d.ToString("dd/MM/yyyy HH:mm"):"—";private static string Safe(string value)=>string.Concat(value.Select(c=>Path.GetInvalidFileNameChars().Contains(c)?'_':c));private static string Csv(string value)=>$"\"{value.Replace("\"","\"\"").Replace("\r"," ").Replace("\n"," ")}\"";
    private static void Text(Grid g,string value,int col,bool strong=false)=>Add(g,new TextBlock{Text=string.IsNullOrWhiteSpace(value)?"—":value,FontWeight=strong?FontWeight.SemiBold:FontWeight.Normal,TextTrimming=TextTrimming.CharacterEllipsis,VerticalAlignment=VerticalAlignment.Center},col);private static void Add(Grid g,Control c,int col){c.Margin=new Thickness(0,0,8,0);Grid.SetColumn(c,col);g.Children.Add(c);}private static Button Button(string text,Action action,bool primary=false){var b=new Button{Content=text,Padding=new Thickness(9,6),Background=UiTokens.Brush(primary?UiTokens.BrandBlue:UiTokens.SurfaceAlt),Foreground=primary?Brushes.White:UiTokens.Brush(UiTokens.TextPrimary)};b.Click+=(_,_)=>action();return b;}
}

internal sealed class SupplierCommunicationAttachmentDialog:Window
{
    private readonly ComboBox _category=new(){ItemsSource=new[]{"Documento","E-mail","Conferma fornitore","Documento RMA","Fattura / nota credito","Altro"},SelectedIndex=0};private readonly TextBox _notes=new();public SupplierCommunicationAttachmentDialog(){Title="Classifica allegati";Width=520;Height=350;WindowStartupLocation=WindowStartupLocation.CenterOwner;var root=SupplierContactDialog.Panel("Classifica allegati");SupplierContactDialog.Field(root,"Categoria",_category);SupplierContactDialog.Field(root,"Note",_notes);root.Children.Add(SupplierContactDialog.SaveButton("Archivia file",()=>Close((_category.SelectedItem?.ToString()??"Documento",_notes.Text??""))));Content=root;}
}
