using System.Diagnostics;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Layout;
using Avalonia.Media;
using Accyourate.App.AssetManagement.Services;
using Accyourate.App.UIFramework.Tokens;

namespace Accyourate.App.AssetManagement;

public sealed class SupplierRmaCapaDossierRegistryWindow:Window
{
    private readonly SupplierRmaCapaDossierRegistryService _service=new();private readonly StackPanel _rows=new();
    private readonly TextBox _search=new(){Watermark="Cerca pratica, azione, responsabile o archivio..."};
    private readonly ComboBox _outcome=new(){ItemsSource=new[]{"Tutti gli esiti","Creato","Integro","Non conforme"},SelectedIndex=0,MinWidth=160};
    private readonly ComboBox _status=new(){ItemsSource=new[]{"Tutti gli stati","Attivo","Archiviato","Sospeso","Da revisionare"},SelectedIndex=0,MinWidth=170};
    private readonly ComboBox _deadline=new(){ItemsSource=new[]{"Tutte le scadenze","In scadenza","Scaduti","Riesami in scadenza","Riesami scaduti","Documenti mancanti"},SelectedIndex=0,MinWidth=190};private readonly TextBlock _summary=new();
    public SupplierRmaCapaDossierRegistryWindow(){Title="Registro fascicoli CAPA";Width=1450;Height=800;MinWidth=980;MinHeight=580;WindowStartupLocation=WindowStartupLocation.CenterOwner;Content=Build();_search.TextChanged+=(_,_)=>LoadData();_outcome.SelectionChanged+=(_,_)=>LoadData();_status.SelectionChanged+=(_,_)=>LoadData();_deadline.SelectionChanged+=(_,_)=>LoadData();_service.PublishAlerts();LoadData();}
    private Control Build(){var root=new DockPanel{Margin=new Thickness(24)};var head=new Grid{ColumnDefinitions=new ColumnDefinitions("*,Auto"),Margin=new Thickness(0,0,0,14)};var title=new StackPanel{Spacing=3,Children={new TextBlock{Text="Registro fascicoli CAPA",FontSize=28,FontWeight=FontWeight.Bold},new TextBlock{Text="Conservazione, revisioni, responsabilita, scadenze e disponibilita documentale.",Foreground=UiTokens.Brush(UiTokens.TextSecondary)}}};Grid.SetColumn(title,0);head.Children.Add(title);var refresh=SupplierRmaCorrectiveActionsWindow.Button("Aggiorna",Refresh,true);Grid.SetColumn(refresh,1);head.Children.Add(refresh);DockPanel.SetDock(head,Dock.Top);root.Children.Add(head);var filters=new Grid{ColumnDefinitions=new ColumnDefinitions("*,160,170,190"),Margin=new Thickness(0,0,0,8)};Add(filters,_search,0);Add(filters,_outcome,1);Add(filters,_status,2);Add(filters,_deadline,3);DockPanel.SetDock(filters,Dock.Top);root.Children.Add(filters);DockPanel.SetDock(_summary,Dock.Top);root.Children.Add(_summary);root.Children.Add(new ScrollViewer{Content=_rows,HorizontalScrollBarVisibility=Avalonia.Controls.Primitives.ScrollBarVisibility.Auto,VerticalScrollBarVisibility=Avalonia.Controls.Primitives.ScrollBarVisibility.Auto});return root;}
    private void Refresh(){_service.PublishAlerts();LoadData();}
    private void LoadData(){try{var all=_service.GetAll();var query=(_search.Text??"").Trim();var outcome=_outcome.SelectedItem?.ToString()??"Tutti gli esiti";var status=_status.SelectedItem?.ToString()??"Tutti gli stati";var deadline=_deadline.SelectedItem?.ToString()??"Tutte le scadenze";var values=all.Where(x=>outcome=="Tutti gli esiti"||x.Outcome==outcome).Where(x=>status=="Tutti gli stati"||x.DocumentStatus==status).Where(x=>deadline switch{"In scadenza"=>x.IsDueSoon,"Scaduti"=>x.IsExpired,"Riesami in scadenza"=>x.IsReviewDueSoon,"Riesami scaduti"=>x.IsReviewOverdue,"Documenti mancanti"=>x.MissingDocuments,_=>true}).Where(x=>query.Length==0||$"{x.CaseNumber} {x.ActionTitle} {x.CreatedBy} {x.Custodian} {x.ArchivePath}".Contains(query,StringComparison.OrdinalIgnoreCase)).ToList();_rows.Children.Clear();_rows.MinWidth=1800;_rows.Children.Add(Header());for(var i=0;i<values.Count;i++)_rows.Children.Add(Row(values[i],i));_summary.Text=$"{values.Count} registrazioni · {all.Count(x=>x.IsReviewDueSoon)} riesami in scadenza · {all.Count(x=>x.IsReviewOverdue)} riesami scaduti · {all.Count(x=>x.MissingDocuments)} documenti mancanti";_summary.Foreground=UiTokens.Brush(UiTokens.TextSecondary);_summary.Margin=new Thickness(0,0,0,8);}catch(Exception ex){_summary.Text=$"Registro non caricato: {ex.Message}";_summary.Foreground=UiTokens.Brush(UiTokens.Danger);}}
    private Control Header(){var grid=GridRow();var labels=new[]{"Data","Pratica","Operazione","Esito","Stato doc.","Responsabile","Rev.","Conservazione","Prossimo riesame","Approvazione","Disponibilita","Comandi"};for(var i=0;i<labels.Length;i++)Cell(grid,labels[i],i,true);return new Border{Padding=new Thickness(9),Background=UiTokens.Brush(UiTokens.SurfaceAlt),Child=grid};}
    private Control Row(SupplierRmaCapaDossierRegistryRecord item,int index){var grid=GridRow();Cell(grid,DateTimeValue(item.CreatedAt),0);Cell(grid,item.CaseNumber,1,true);Cell(grid,item.Operation,2);Add(grid,Badge(item.Outcome),3);Add(grid,StatusBadge(item),4);Cell(grid,item.Custodian,5);Cell(grid,item.Revision,6,true);Cell(grid,DateValue(item.RetentionUntil),7,item.IsExpired);Cell(grid,DateValue(item.ReviewDueDate),8,item.IsReviewOverdue);Add(grid,ApprovalBadge(item.ApprovalStatus),9);Cell(grid,item.MissingDocuments?"Mancanti":"Disponibili",10,item.MissingDocuments);var actions=new StackPanel{Orientation=Orientation.Horizontal,Spacing=5};actions.Children.Add(SupplierRmaCorrectiveActionsWindow.Button("Approva",()=>new SupplierRmaCapaDossierApprovalDialog(item,_service,LoadData).Show(this),true));var review=SupplierRmaCorrectiveActionsWindow.Button("Riesame",()=>new SupplierRmaCapaDossierReviewDialog(item,_service,LoadData).Show(this));review.IsEnabled=!item.IsLocked;actions.Children.Add(review);actions.Children.Add(SupplierRmaCorrectiveActionsWindow.Button("Storico",()=>new SupplierRmaCapaDossierControlHistoryWindow(item,_service).Show(this)));Add(grid,actions,11);return new Border{Padding=new Thickness(9,7),Background=UiTokens.Brush(index%2==0?UiTokens.Surface:UiTokens.SurfaceAlt),BorderBrush=UiTokens.Brush(UiTokens.Border),BorderThickness=new Thickness(0,0,0,1),Child=grid};}
    private static Grid GridRow()=>new(){ColumnDefinitions=new ColumnDefinitions("135,145,105,120,125,145,60,115,120,125,110,290")};
    private static Border ApprovalBadge(string value){var color=value switch{"Approvato"=>UiTokens.Success,"Rifiutato"=>UiTokens.Danger,"In approvazione"=>UiTokens.Warning,_=>UiTokens.TextSecondary};return Badge(value,color);}
    private static Border Badge(string value){var color=value switch{"Integro"=>UiTokens.Success,"Non conforme"=>UiTokens.Danger,_=>UiTokens.BrandBlue};return Badge(value,color);}
    private static Border StatusBadge(SupplierRmaCapaDossierRegistryRecord item){var color=item.MissingDocuments||item.IsExpired?UiTokens.Danger:item.IsDueSoon||item.DocumentStatus=="Da revisionare"?UiTokens.Warning:item.DocumentStatus=="Attivo"?UiTokens.Success:UiTokens.TextSecondary;return Badge(item.DocumentStatus,color);}
    private static Border Badge(string text,string color)=>new(){BorderBrush=UiTokens.Brush(color),BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(8),Padding=new Thickness(7,3),Child=new TextBlock{Text=text,Foreground=UiTokens.Brush(color),HorizontalAlignment=HorizontalAlignment.Center,FontWeight=FontWeight.SemiBold}};
    private static void Open(string path){if(File.Exists(path))Process.Start(new ProcessStartInfo{FileName=path,UseShellExecute=true});}private static string DateTimeValue(string value)=>DateTime.TryParse(value,out var date)?date.ToString("dd/MM/yyyy HH:mm"):value;private static string DateValue(string value)=>DateTime.TryParse(value,out var date)?date.ToString("dd/MM/yyyy"):value;private static void Cell(Grid grid,string value,int column,bool strong=false)=>Add(grid,new TextBlock{Text=string.IsNullOrWhiteSpace(value)?"—":value,FontWeight=strong?FontWeight.SemiBold:FontWeight.Normal,TextTrimming=TextTrimming.CharacterEllipsis,VerticalAlignment=VerticalAlignment.Center},column);private static void Add(Grid grid,Control control,int column){control.Margin=new Thickness(0,0,8,0);Grid.SetColumn(control,column);grid.Children.Add(control);}
}

internal sealed class SupplierRmaCapaDossierControlDialog:Window
{
    private readonly SupplierRmaCapaDossierRegistryRecord _record;private readonly SupplierRmaCapaDossierRegistryService _service;private readonly Action _saved;private readonly ComboBox _status=new(){ItemsSource=new[]{"Attivo","Archiviato","Sospeso","Da revisionare"}};private readonly TextBox _custodian=new(),_revision=new(),_retention=new(),_notes=new(){AcceptsReturn=true,TextWrapping=TextWrapping.Wrap,MinHeight=100};private readonly TextBlock _message=new();
    public SupplierRmaCapaDossierControlDialog(SupplierRmaCapaDossierRegistryRecord record,SupplierRmaCapaDossierRegistryService service,Action saved){_record=record;_service=service;_saved=saved;Title="Controllo documentale fascicolo CAPA";Width=650;Height=650;WindowStartupLocation=WindowStartupLocation.CenterOwner;_status.SelectedItem=record.DocumentStatus;_custodian.Text=string.IsNullOrWhiteSpace(record.Custodian)?Environment.UserName:record.Custodian;_revision.Text=record.Revision;_retention.Text=DateTime.TryParse(record.RetentionUntil,out var date)?date.ToString("yyyy-MM-dd"):DateTime.Today.AddYears(10).ToString("yyyy-MM-dd");_notes.Text=record.ControlNotes;var root=new StackPanel{Margin=new Thickness(24),Spacing=9,Children={new TextBlock{Text="Controllo documentale",FontSize=25,FontWeight=FontWeight.Bold},new TextBlock{Text=$"{record.CaseNumber} · {record.ActionTitle}",TextWrapping=TextWrapping.Wrap},new TextBlock{Text=record.MissingDocuments?"Attenzione: archivio o verbale non disponibile.":"Archivio e verbale disponibili.",Foreground=UiTokens.Brush(record.MissingDocuments?UiTokens.Danger:UiTokens.Success),FontWeight=FontWeight.SemiBold}}};Field(root,"Stato",_status);Field(root,"Responsabile della conservazione",_custodian);Field(root,"Revisione",_revision);Field(root,"Conservare fino al (AAAA-MM-GG)",_retention);Field(root,"Note di controllo",_notes);root.Children.Add(_message);root.Children.Add(SupplierRmaCorrectiveActionsWindow.Button("Salva controllo",Save,true));Content=new ScrollViewer{Content=root};}
    private void Save(){try{_service.UpdateControl(_record.Id,_status.SelectedItem?.ToString()??"Attivo",_custodian.Text??"",_revision.Text??"",_retention.Text??"",_notes.Text??"",Environment.UserName);_saved();Close();}catch(Exception ex){_message.Text=ex.Message;_message.Foreground=UiTokens.Brush(UiTokens.Danger);}}
    private static void Field(StackPanel root,string label,Control control)=>root.Children.Add(new StackPanel{Spacing=3,Children={new TextBlock{Text=label,FontWeight=FontWeight.SemiBold},control}});
}

internal sealed class SupplierRmaCapaDossierApprovalDialog:Window
{
    private readonly SupplierRmaCapaDossierRegistryRecord _item;private readonly SupplierRmaCapaDossierRegistryService _service;private readonly Action _saved;private readonly TextBox _approver=new(){Text=Environment.UserName},_notes=new(){AcceptsReturn=true,TextWrapping=TextWrapping.Wrap,MinHeight=100};private readonly TextBlock _message=new();
    public SupplierRmaCapaDossierApprovalDialog(SupplierRmaCapaDossierRegistryRecord item,SupplierRmaCapaDossierRegistryService service,Action saved){_item=item;_service=service;_saved=saved;Title="Approvazione riesame CAPA";Width=620;Height=520;WindowStartupLocation=WindowStartupLocation.CenterOwner;var root=new StackPanel{Margin=new Thickness(24),Spacing=9,Children={new TextBlock{Text="Approvazione riesame",FontSize=25,FontWeight=FontWeight.Bold},new TextBlock{Text=$"{item.CaseNumber} · Stato: {item.ApprovalStatus}",TextWrapping=TextWrapping.Wrap},new TextBlock{Text="Approvatore",FontWeight=FontWeight.SemiBold},_approver,new TextBlock{Text="Motivazione / note",FontWeight=FontWeight.SemiBold},_notes,_message}};var buttons=new StackPanel{Orientation=Orientation.Horizontal,Spacing=8};if(item.ApprovalStatus is "Bozza" or "Rifiutato" or "Riaperto")buttons.Children.Add(SupplierRmaCorrectiveActionsWindow.Button("Invia in approvazione",Submit,true));if(item.ApprovalStatus=="In approvazione"){buttons.Children.Add(SupplierRmaCorrectiveActionsWindow.Button("Approva",()=>Decide(true),true));buttons.Children.Add(SupplierRmaCorrectiveActionsWindow.Button("Rifiuta",()=>Decide(false)));}if(item.ApprovalStatus=="Approvato")buttons.Children.Add(SupplierRmaCorrectiveActionsWindow.Button("Riapri",Reopen));root.Children.Add(buttons);Content=root;}
    private void Submit()=>Run(()=>_service.SubmitForApproval(_item.Id,_approver.Text??"",Environment.UserName));private void Decide(bool approved)=>Run(()=>_service.DecideApproval(_item.Id,approved,_notes.Text??"",Environment.UserName));private void Reopen()=>Run(()=>_service.ReopenApproval(_item.Id,_notes.Text??"",Environment.UserName));private void Run(Action action){try{action();_saved();Close();}catch(Exception ex){_message.Text=ex.Message;_message.Foreground=UiTokens.Brush(UiTokens.Danger);}}
}

internal sealed class SupplierRmaCapaDossierReviewDialog:Window
{
    private readonly SupplierRmaCapaDossierRegistryRecord _record;private readonly SupplierRmaCapaDossierRegistryService _service;private readonly Action _saved;private readonly ComboBox _outcome=new(){ItemsSource=new[]{"Confermato","Da aggiornare","Non conforme"},SelectedIndex=0};private readonly TextBox _custodian=new(),_nextReview=new(),_retention=new(),_notes=new(){AcceptsReturn=true,TextWrapping=TextWrapping.Wrap,MinHeight=120};private readonly CheckBox _openRevision=new(){Content="Apri automaticamente una nuova revisione"};private readonly TextBlock _message=new();
    public SupplierRmaCapaDossierReviewDialog(SupplierRmaCapaDossierRegistryRecord record,SupplierRmaCapaDossierRegistryService service,Action saved){_record=record;_service=service;_saved=saved;Title="Riesame periodico fascicolo CAPA";Width=680;Height=690;WindowStartupLocation=WindowStartupLocation.CenterOwner;_custodian.Text=string.IsNullOrWhiteSpace(record.Custodian)?Environment.UserName:record.Custodian;_nextReview.Text=DateTime.Today.AddYears(1).ToString("yyyy-MM-dd");_retention.Text=DateTime.TryParse(record.RetentionUntil,out var retention)?retention.ToString("yyyy-MM-dd"):DateTime.Today.AddYears(10).ToString("yyyy-MM-dd");var root=new StackPanel{Margin=new Thickness(24),Spacing=9,Children={new TextBlock{Text="Riesame periodico",FontSize=25,FontWeight=FontWeight.Bold},new TextBlock{Text=$"{record.CaseNumber} · revisione {record.Revision}",TextWrapping=TextWrapping.Wrap},new TextBlock{Text=$"Ultimo esito: {record.ReviewOutcome} · prossimo riesame {Format(record.ReviewDueDate)}",Foreground=UiTokens.Brush(UiTokens.TextSecondary)}}};Field(root,"Esito del riesame",_outcome);Field(root,"Responsabile confermato o aggiornato",_custodian);Field(root,"Prossimo riesame (AAAA-MM-GG)",_nextReview);Field(root,"Conservare fino al (AAAA-MM-GG)",_retention);Field(root,"Evidenze e note del riesame",_notes);root.Children.Add(_openRevision);root.Children.Add(_message);root.Children.Add(SupplierRmaCorrectiveActionsWindow.Button("Registra riesame",Save,true));Content=new ScrollViewer{Content=root};}
    private void Save(){try{_service.CompleteReview(_record.Id,_outcome.SelectedItem?.ToString()??"Confermato",_custodian.Text??"",_nextReview.Text??"",_retention.Text??"",_notes.Text??"",_openRevision.IsChecked==true,Environment.UserName);_saved();Close();}catch(Exception ex){_message.Text=ex.Message;_message.Foreground=UiTokens.Brush(UiTokens.Danger);}}
    private static string Format(string value)=>DateTime.TryParse(value,out var date)?date.ToString("dd/MM/yyyy"):"Non pianificato";private static void Field(StackPanel root,string label,Control control)=>root.Children.Add(new StackPanel{Spacing=3,Children={new TextBlock{Text=label,FontWeight=FontWeight.SemiBold},control}});
}

internal sealed class SupplierRmaCapaDossierControlHistoryWindow:Window
{
    public SupplierRmaCapaDossierControlHistoryWindow(SupplierRmaCapaDossierRegistryRecord record,SupplierRmaCapaDossierRegistryService service){Title="Storico controllo documentale";Width=920;Height=650;WindowStartupLocation=WindowStartupLocation.CenterOwner;var root=new StackPanel{Margin=new Thickness(24),Spacing=8,Children={new TextBlock{Text="Audit trail fascicolo CAPA",FontSize=25,FontWeight=FontWeight.Bold},new TextBlock{Text=$"{record.CaseNumber} · {record.ActionTitle}",TextWrapping=TextWrapping.Wrap}}};var values=service.GetHistory(record.Id);if(values.Count==0)root.Children.Add(new TextBlock{Text="Nessuna modifica registrata.",Foreground=UiTokens.Brush(UiTokens.TextSecondary)});foreach(var item in values)root.Children.Add(new Border{Padding=new Thickness(10),BorderBrush=UiTokens.Brush(UiTokens.Border),BorderThickness=new Thickness(0,0,0,1),Child=new StackPanel{Spacing=3,Children={new TextBlock{Text=$"{item.EventType} · {Format(item.CreatedAt)}",FontWeight=FontWeight.Bold},new TextBlock{Text=$"{item.OldValue} → {item.NewValue}",TextWrapping=TextWrapping.Wrap,Foreground=UiTokens.Brush(UiTokens.BrandBlue)},new TextBlock{Text=item.Notes,TextWrapping=TextWrapping.Wrap,IsVisible=!string.IsNullOrWhiteSpace(item.Notes)},new TextBlock{Text=$"Operatore: {item.CreatedBy}",Foreground=UiTokens.Brush(UiTokens.TextSecondary)}}}});Content=new ScrollViewer{Content=root};}
    private static string Format(string value)=>DateTime.TryParse(value,out var date)?date.ToString("dd/MM/yyyy HH:mm"):value;
}
