using System.Diagnostics;using Avalonia;using Avalonia.Controls;using Avalonia.Layout;using Avalonia.Media;using Accyourate.App.AssetManagement.Services;using Accyourate.App.UIFramework.Tokens;
namespace Accyourate.App.AssetManagement;
public sealed class SupplierRmaCapaAttestationRegistryWindow:Window
{
 private readonly SupplierRmaCapaAttestationService _service=new();private readonly StackPanel _rows=new();private readonly TextBox _search=new(){Watermark="Cerca pratica, approvatore, ruolo..."};private readonly ComboBox _status=new(){ItemsSource=new[]{"Tutti gli stati","Valida","Non valida","Archivio mancante"},SelectedIndex=0,MinWidth=190};private readonly TextBlock _summary=new();
 public SupplierRmaCapaAttestationRegistryWindow(){Title="Registro attestazioni CAPA";Width=1320;Height=760;WindowStartupLocation=WindowStartupLocation.CenterOwner;Content=Build();_search.TextChanged+=(_,_)=>Load();_status.SelectionChanged+=(_,_)=>Load();VerifyAll();}
 private Control Build(){var root=new DockPanel{Margin=new Thickness(24)};var head=new Grid{ColumnDefinitions=new ColumnDefinitions("*,Auto"),Margin=new Thickness(0,0,0,12)};var title=new StackPanel{Children={new TextBlock{Text="Registro attestazioni CAPA",FontSize=28,FontWeight=FontWeight.Bold},new TextBlock{Text="Impronte, validita, approvatori e verbali.",Foreground=UiTokens.Brush(UiTokens.TextSecondary)}}};Grid.SetColumn(title,0);head.Children.Add(title);var verify=SupplierRmaCorrectiveActionsWindow.Button("Verifica tutte",VerifyAll,true);Grid.SetColumn(verify,1);head.Children.Add(verify);DockPanel.SetDock(head,Dock.Top);root.Children.Add(head);var filters=new Grid{ColumnDefinitions=new ColumnDefinitions("*,190"),Margin=new Thickness(0,0,0,8)};Add(filters,_search,0);Add(filters,_status,1);DockPanel.SetDock(filters,Dock.Top);root.Children.Add(filters);DockPanel.SetDock(_summary,Dock.Top);root.Children.Add(_summary);root.Children.Add(new ScrollViewer{Content=_rows,HorizontalScrollBarVisibility=Avalonia.Controls.Primitives.ScrollBarVisibility.Auto});return root;}
 private void VerifyAll(){_service.PublishInvalidNotifications();Load();}
 private void Load(){var all=_service.GetAll();var q=(_search.Text??"").Trim();var s=_status.SelectedItem?.ToString()??"Tutti gli stati";var values=all.Where(x=>s=="Tutti gli stati"||x.ValidationStatus==s).Where(x=>q.Length==0||$"{x.CaseNumber} {x.Approver} {x.Role} {x.Revision}".Contains(q,StringComparison.OrdinalIgnoreCase)).ToList();_rows.Children.Clear();_rows.MinWidth=1150;_rows.Children.Add(Row(new(){CaseNumber="Pratica",Revision="Rev.",Approver="Approvatore",Role="Ruolo",AttestedAt="Data"},true));foreach(var x in values)_rows.Children.Add(Row(x,false));_summary.Text=$"{values.Count} attestazioni · {all.Count(x=>x.IsValid)} valide · {all.Count(x=>!x.IsValid)} non valide";_summary.Foreground=UiTokens.Brush(UiTokens.TextSecondary);_summary.Margin=new Thickness(0,0,0,8);}
 private Control Row(SupplierRmaCapaAttestation x,bool header){var g=new Grid{ColumnDefinitions=new ColumnDefinitions("170,70,170,170,150,140,260")};Cell(g,x.CaseNumber,0,header);Cell(g,x.Revision,1,header);Cell(g,x.Approver,2,header);Cell(g,x.Role,3,header);Cell(g,header?x.AttestedAt:Date(x.AttestedAt),4,header);Cell(g,header?"Stato":x.ValidationStatus,5,true);if(!header){var a=new StackPanel{Orientation=Orientation.Horizontal,Spacing=6};var archive=SupplierRmaCorrectiveActionsWindow.Button("Archivio",()=>Open(x.ArchivePath));archive.IsEnabled=x.ArchiveAvailable;a.Children.Add(archive);var report=SupplierRmaCorrectiveActionsWindow.Button("Verbale",()=>Open(x.ReportPath));report.IsEnabled=x.ReportAvailable;a.Children.Add(report);Add(g,a,6);}return new Border{Padding=new Thickness(9),Background=UiTokens.Brush(header?UiTokens.SurfaceAlt:UiTokens.Surface),BorderBrush=UiTokens.Brush(UiTokens.Border),BorderThickness=new Thickness(0,0,0,1),Child=g};}
 private static void Open(string p){if(File.Exists(p))Process.Start(new ProcessStartInfo{FileName=p,UseShellExecute=true});}private static string Date(string v)=>DateTime.TryParse(v,out var d)?d.ToString("dd/MM/yyyy HH:mm"):v;private static void Cell(Grid g,string t,int c,bool strong=false)=>Add(g,new TextBlock{Text=t,FontWeight=strong?FontWeight.Bold:FontWeight.Normal,TextTrimming=TextTrimming.CharacterEllipsis},c);private static void Add(Grid g,Control x,int c){x.Margin=new Thickness(0,0,8,0);Grid.SetColumn(x,c);g.Children.Add(x);}
}
