using System.Diagnostics;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Layout;
using Avalonia.Media;
using Accyourate.App.AssetManagement.Models;
using Accyourate.App.AssetManagement.Services;
using Accyourate.App.UIFramework.Tokens;

namespace Accyourate.App.AssetManagement;

public sealed class SupplierEmailComposerWindow:Window
{
    public event Action? DraftPrepared;
    private readonly int _supplierId;private readonly string _supplierName;private readonly IReadOnlyList<SupplierPortalContact> _contacts;private readonly IReadOnlyList<SparePartRmaCase> _cases;private readonly IReadOnlyList<SupplierPortalAttachment> _attachments;private readonly SupplierRmaPortalRepository _repository;private readonly SupplierEmailComposerService _composer=new();
    private readonly ComboBox _contact=new(),_template=new(),_rma=new(),_attachment=new();private readonly TextBox _subject=new(),_body=new(){AcceptsReturn=true,TextWrapping=TextWrapping.Wrap,MinHeight=260};private readonly TextBlock _status=new();private IReadOnlyList<SupplierEmailTemplate> _templates=[];
    public SupplierEmailComposerWindow(int supplierId,string supplierName,IReadOnlyList<SupplierPortalContact> contacts,IReadOnlyList<SparePartRmaCase> cases,IReadOnlyList<SupplierPortalAttachment> attachments,SupplierRmaPortalRepository repository,int selectedRma=0){_supplierId=supplierId;_supplierName=supplierName;_contacts=contacts.Where(x=>!string.IsNullOrWhiteSpace(x.Email)).OrderByDescending(x=>x.IsPrimary).ToList();_cases=cases;_attachments=attachments;_repository=repository;Title="Prepara e-mail fornitore";Width=760;Height=820;MinWidth=640;MinHeight=650;WindowStartupLocation=WindowStartupLocation.CenterOwner;var root=SupplierContactDialog.Panel("Prepara e-mail");root.Children.Add(new TextBlock{Text=$"Fornitore: {supplierName}",Foreground=UiTokens.Brush(UiTokens.TextSecondary)});_contact.ItemsSource=_contacts.Select(x=>$"{x.Name} · {x.Email}").ToList();_contact.SelectedIndex=_contacts.Count>0?0:-1;_rma.ItemsSource=new[]{"Nessuna pratica"}.Concat(cases.Select(x=>x.CaseNumber)).ToList();_rma.SelectedIndex=selectedRma>0?Math.Max(0,cases.ToList().FindIndex(x=>x.Id==selectedRma)+1):0;_attachment.ItemsSource=new[]{"Nessun allegato"}.Concat(attachments.Select(x=>$"{x.Category} · {x.FileName}")).ToList();_attachment.SelectedIndex=0;LoadTemplates();_template.SelectionChanged+=(_,_)=>ApplySelectedTemplate();_rma.SelectionChanged+=(_,_)=>ApplySelectedTemplate();SupplierContactDialog.Field(root,"Destinatario",_contact);var templateRow=new Grid{ColumnDefinitions=new ColumnDefinitions("*,Auto")};Grid.SetColumn(_template,0);templateRow.Children.Add(_template);var manage=Button("Gestisci modelli",()=>new SupplierEmailTemplateWindow(_repository).Show(this));Grid.SetColumn(manage,1);manage.Margin=new Thickness(8,0,0,0);templateRow.Children.Add(manage);SupplierContactDialog.Field(root,"Modello",templateRow);SupplierContactDialog.Field(root,"Pratica RMA",_rma);SupplierContactDialog.Field(root,"Oggetto",_subject);SupplierContactDialog.Field(root,"Messaggio",_body);SupplierContactDialog.Field(root,"Allegato archiviato",_attachment);root.Children.Add(_status);root.Children.Add(Button("Prepara nel programma e-mail",Prepare,true));Content=new ScrollViewer{Content=root};ApplySelectedTemplate();}
    private void LoadTemplates(){_templates=_repository.GetEmailTemplates();_template.ItemsSource=_templates.Select(x=>x.Name).ToList();_template.SelectedIndex=_templates.Count>0?0:-1;}
    private void ApplySelectedTemplate(){if(_template.SelectedIndex<0||_template.SelectedIndex>=_templates.Count)return;var t=_templates[_template.SelectedIndex];var contact=_contact.SelectedIndex>=0&&_contact.SelectedIndex<_contacts.Count?_contacts[_contact.SelectedIndex].Name:"Referente";var rma=_rma.SelectedIndex>0&&_rma.SelectedIndex<=_cases.Count?_cases[_rma.SelectedIndex-1]:null;var code=rma?.CaseNumber??"pratica RMA";var due=DateTime.TryParse(rma?.DueDate,out var d)?d.ToString("dd/MM/yyyy"):"da concordare";_subject.Text=SupplierEmailComposerService.ApplyTemplate(t.SubjectTemplate,_supplierName,contact,code,due);_body.Text=SupplierEmailComposerService.ApplyTemplate(t.BodyTemplate,_supplierName,contact,code,due);}
    private void Prepare(){try{if(_contact.SelectedIndex<0||_contact.SelectedIndex>=_contacts.Count)throw new InvalidOperationException("Aggiungi un contatto fornitore con indirizzo e-mail.");var contact=_contacts[_contact.SelectedIndex];var rmaId=_rma.SelectedIndex>0&&_rma.SelectedIndex<=_cases.Count?_cases[_rma.SelectedIndex-1].Id:0;var files=new List<string>();if(_attachment.SelectedIndex>0&&_attachment.SelectedIndex<=_attachments.Count)files.Add(_attachments[_attachment.SelectedIndex-1].StoredPath);var path=_composer.CreateDraft(contact.Email,_subject.Text??"",_body.Text??"",files);_repository.AddInteraction(new(){SupplierId=_supplierId,RmaId=rmaId,Type="Email",Direction="In uscita",Subject=_subject.Text??"",Message=_body.Text??"",Status="Aperta",CreatedBy=Environment.UserName});DraftPrepared?.Invoke();Process.Start(new ProcessStartInfo{FileName=path,UseShellExecute=true});_status.Text="Bozza e-mail preparata e comunicazione registrata.";_status.Foreground=UiTokens.Brush(UiTokens.Success);}catch(Exception ex){_status.Text=ex.Message;_status.Foreground=UiTokens.Brush(UiTokens.Danger);}}
    private static Button Button(string text,Action action,bool primary=false){var b=new Button{Content=text,Padding=new Thickness(10,7),Background=UiTokens.Brush(primary?UiTokens.BrandBlue:UiTokens.SurfaceAlt),Foreground=primary?Brushes.White:UiTokens.Brush(UiTokens.TextPrimary)};b.Click+=(_,_)=>action();return b;}
}

internal sealed class SupplierEmailTemplateWindow:Window
{
    private readonly SupplierRmaPortalRepository _repository;private readonly ComboBox _existing=new();private readonly TextBox _name=new(),_subject=new(),_body=new(){AcceptsReturn=true,TextWrapping=TextWrapping.Wrap,MinHeight=220};private readonly CheckBox _default=new(){Content="Modello predefinito"};private readonly TextBlock _status=new();private IReadOnlyList<SupplierEmailTemplate> _values=[];
    public SupplierEmailTemplateWindow(SupplierRmaPortalRepository repository){_repository=repository;Title="Modelli e-mail fornitori";Width=680;Height=720;WindowStartupLocation=WindowStartupLocation.CenterOwner;var root=SupplierContactDialog.Panel("Modelli e-mail");Load();_existing.SelectionChanged+=(_,_)=>Select();SupplierContactDialog.Field(root,"Modello esistente",_existing);SupplierContactDialog.Field(root,"Nome",_name);SupplierContactDialog.Field(root,"Oggetto",_subject);SupplierContactDialog.Field(root,"Corpo del messaggio",_body);root.Children.Add(new TextBlock{Text="Variabili: {FORNITORE}, {CONTATTO}, {RMA}, {SCADENZA}",Foreground=UiTokens.Brush(UiTokens.TextSecondary)});root.Children.Add(_default);root.Children.Add(_status);root.Children.Add(SupplierContactDialog.SaveButton("Salva modello",Save));Content=new ScrollViewer{Content=root};Select();}
    private void Load(){_values=_repository.GetEmailTemplates();_existing.ItemsSource=_values.Select(x=>x.Name).ToList();_existing.SelectedIndex=_values.Count>0?0:-1;}
    private void Select(){if(_existing.SelectedIndex<0||_existing.SelectedIndex>=_values.Count)return;var x=_values[_existing.SelectedIndex];_name.Text=x.Name;_subject.Text=x.SubjectTemplate;_body.Text=x.BodyTemplate;_default.IsChecked=x.IsDefault;}
    private void Save(){try{_repository.SaveEmailTemplate(new(){Name=_name.Text??"",SubjectTemplate=_subject.Text??"",BodyTemplate=_body.Text??"",IsDefault=_default.IsChecked==true});_status.Text="Modello salvato.";_status.Foreground=UiTokens.Brush(UiTokens.Success);Load();}catch(Exception ex){_status.Text=ex.Message;_status.Foreground=UiTokens.Brush(UiTokens.Danger);}}
}
