using System.Diagnostics;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Layout;
using Avalonia.Media;
using Accyourate.App.AssetManagement.Services;
using Accyourate.App.UIFramework.Tokens;

namespace Accyourate.App.AssetManagement;

public sealed class SupplierRmaCapaAttestationRetentionAuditWindow : Window
{
    private readonly SupplierRmaCapaAttestationExportService _service=new();private readonly StackPanel _rows=new();private readonly TextBlock _summary=new();private readonly TextBox _search=new(){Watermark="Cerca azione, dettaglio, operatore..."};private readonly ComboBox _action=new(){ItemsSource=new[]{"Tutte le azioni","Configurazione conservazione","Proroga conservazione","Archiviazione controllata"},SelectedIndex=0,MinWidth=230};private IReadOnlyList<SupplierRmaCapaAttestationRetentionAuditRecord> _filtered=Array.Empty<SupplierRmaCapaAttestationRetentionAuditRecord>();
    public SupplierRmaCapaAttestationRetentionAuditWindow(){Title="Audit conservazione CAPA";Width=1320;Height=740;WindowStartupLocation=WindowStartupLocation.CenterOwner;Content=Build();_search.TextChanged+=(_,_)=>Load();_action.SelectionChanged+=(_,_)=>Load();Load();}
    private Control Build(){var root=new DockPanel{Margin=new Thickness(24)};var head=new Grid{ColumnDefinitions=new ColumnDefinitions("*,Auto"),Margin=new Thickness(0,0,0,12)};var title=new StackPanel{Children={new TextBlock{Text="Audit conservazione CAPA",FontSize=28,FontWeight=FontWeight.Bold},new TextBlock{Text="Configurazioni, proroghe e archiviazioni controllate.",Foreground=UiTokens.Brush(UiTokens.TextSecondary)}}};Add(head,title,0);var report=SupplierRmaCorrectiveActionsWindow.Button("Report PDF",Export,true);Add(head,report,1);DockPanel.SetDock(head,Dock.Top);root.Children.Add(head);var filters=new Grid{ColumnDefinitions=new ColumnDefinitions("*,230"),Margin=new Thickness(0,0,0,8)};Add(filters,_search,0);Add(filters,_action,1);DockPanel.SetDock(filters,Dock.Top);root.Children.Add(filters);DockPanel.SetDock(_summary,Dock.Top);root.Children.Add(_summary);root.Children.Add(new ScrollViewer{Content=_rows,HorizontalScrollBarVisibility=Avalonia.Controls.Primitives.ScrollBarVisibility.Auto});return root;}
    private void Load(){var all=_service.GetRetentionAudit();var q=(_search.Text??"").Trim();var action=_action.SelectedItem?.ToString()??"Tutte le azioni";_filtered=all.Where(x=>action=="Tutte le azioni"||x.Action==action).Where(x=>q.Length==0||$"{x.Action} {x.Detail} {x.PerformedBy} {x.ExportId} {x.Format}".Contains(q,StringComparison.OrdinalIgnoreCase)).ToList();_rows.Children.Clear();_rows.MinWidth=1180;_rows.Children.Add(Row(new(){PerformedAt="Data",Action="Azione",PerformedBy="Operatore",Detail="Dettaglio",Format="Formato"},true));foreach(var row in _filtered)_rows.Children.Add(Row(row,false));_summary.Text=$"{_filtered.Count} operazioni visualizzate";_summary.Foreground=UiTokens.Brush(UiTokens.TextSecondary);_summary.Margin=new Thickness(0,0,0,8);}
    private void Export(){try{var filter=$"Azione: {_action.SelectedItem}; ricerca: {(_search.Text??"").Trim()}";var path=_service.ExportRetentionAuditPdf(_filtered,filter);_summary.Text=$"Report creato: {Path.GetFileName(path)}";_summary.Foreground=UiTokens.Brush(UiTokens.Success);Process.Start(new ProcessStartInfo{FileName=path,UseShellExecute=true});}catch(Exception ex){_summary.Text=$"Errore report: {ex.Message}";_summary.Foreground=UiTokens.Brush(UiTokens.Danger);}}
    private static Control Row(SupplierRmaCapaAttestationRetentionAuditRecord x,bool header){var grid=new Grid{ColumnDefinitions=new ColumnDefinitions("160,100,230,180,170,400")};Cell(grid,header?x.PerformedAt:Date(x.PerformedAt),0,header);Cell(grid,header?"Export":x.ExportId==0?"Generale":$"#{x.ExportId}",1,header);Cell(grid,x.Action,2,header);Cell(grid,x.PerformedBy,3,header);Cell(grid,x.Format,4,header);Cell(grid,x.Detail,5,header);return new Border{Padding=new Thickness(9),Background=UiTokens.Brush(header?UiTokens.SurfaceAlt:UiTokens.Surface),BorderBrush=UiTokens.Brush(UiTokens.Border),BorderThickness=new Thickness(0,0,0,1),Child=grid};}
    private static string Date(string value)=>DateTime.TryParse(value,out var date)?date.ToString("dd/MM/yyyy HH:mm"):value;private static void Cell(Grid grid,string text,int col,bool bold=false)=>Add(grid,new TextBlock{Text=text,FontWeight=bold?FontWeight.Bold:FontWeight.Normal,TextTrimming=TextTrimming.CharacterEllipsis},col);private static void Add(Grid grid,Control control,int col){control.Margin=new Thickness(0,0,8,0);Grid.SetColumn(control,col);grid.Children.Add(control);}
}
