using System.Diagnostics;using Avalonia;using Avalonia.Controls;using Avalonia.Layout;using Avalonia.Media;using Accyourate.App.AssetManagement.Services;using Accyourate.App.UIFramework.Tokens;
namespace Accyourate.App.AssetManagement;
public sealed class SupplierRmaCapaGovernanceReviewsWindow:Window
{
 private readonly SupplierRmaCapaGovernanceReviewService _service=new();private readonly StackPanel _rows=new();private readonly TextBlock _summary=new();public SupplierRmaCapaGovernanceReviewsWindow(){Title="Riesami Governance CAPA";Width=1250;Height=720;WindowStartupLocation=WindowStartupLocation.CenterOwner;Content=Build();_service.PublishAlerts();Load();}
 private Control Build(){var root=new DockPanel{Margin=new Thickness(24)};var head=new Grid{ColumnDefinitions=new ColumnDefinitions("*,Auto"),Margin=new Thickness(0,0,0,12)};Add(head,new StackPanel{Children={new TextBlock{Text="Riesami Governance CAPA",FontSize=28,FontWeight=FontWeight.Bold},new TextBlock{Text="Valutazioni periodiche, decisioni, verbali e prossime scadenze.",Foreground=UiTokens.Brush(UiTokens.TextSecondary)}}},0);var actions=new StackPanel{Orientation=Orientation.Horizontal,Spacing=8};actions.Children.Add(SupplierRmaCorrectiveActionsWindow.Button("Nuovo riesame",()=>new SupplierRmaCapaGovernanceReviewDialog(_service,Load).Show(this),true));actions.Children.Add(SupplierRmaCorrectiveActionsWindow.Button("Aggiorna e notifica",Refresh));Add(head,actions,1);DockPanel.SetDock(head,Dock.Top);root.Children.Add(head);DockPanel.SetDock(_summary,Dock.Top);root.Children.Add(_summary);root.Children.Add(new ScrollViewer{Content=_rows,HorizontalScrollBarVisibility=Avalonia.Controls.Primitives.ScrollBarVisibility.Auto});return root;}
 private void Refresh(){_service.PublishAlerts();Load();}private void Load(){var all=_service.GetAll();_rows.Children.Clear();_rows.MinWidth=1120;_rows.Children.Add(Row(new(){Reviewer="Responsabile",ReviewDate="Data",NextReviewDate="Prossimo",Outcome="Esito",EvaluationStatus="Indicatori"},true));foreach(var x in all)_rows.Children.Add(Row(x,false));_summary.Text=$"{all.Count} riesami · {all.Count(x=>x.IsDueSoon)} in scadenza · {all.Count(x=>x.IsOverdue)} scaduti";_summary.Foreground=UiTokens.Brush(all.Any(x=>x.IsOverdue)?UiTokens.Danger:UiTokens.TextSecondary);_summary.Margin=new Thickness(0,0,0,8);}
 private Control Row(SupplierRmaCapaGovernanceReview x,bool header){var g=new Grid{ColumnDefinitions=new ColumnDefinitions("80,150,160,160,150,110,110,180")};Cell(g,header?"Numero":x.Id.ToString("D6"),0,header);Cell(g,header?x.ReviewDate:Date(x.ReviewDate),1,header);Cell(g,x.Reviewer,2,header);Cell(g,x.Outcome,3,true);Cell(g,x.EvaluationStatus,4,true);Cell(g,header?"Azioni":x.TotalActions.ToString(),5,header);Cell(g,header?x.NextReviewDate:Date(x.NextReviewDate),6,header||x.IsOverdue);if(!header){var b=SupplierRmaCorrectiveActionsWindow.Button("Apri verbale",()=>Open(x.ReportPath));b.IsEnabled=x.ReportAvailable;Add(g,b,7);}else Cell(g,"Documento",7,true);return new Border{Padding=new Thickness(9),Background=UiTokens.Brush(header?UiTokens.SurfaceAlt:UiTokens.Surface),BorderBrush=UiTokens.Brush(UiTokens.Border),BorderThickness=new Thickness(0,0,0,1),Child=g};}
 private static void Open(string p){if(File.Exists(p))Process.Start(new ProcessStartInfo{FileName=p,UseShellExecute=true});}private static string Date(string v)=>DateTime.TryParse(v,out var d)?d.ToString("dd/MM/yyyy"):v;private static void Cell(Grid g,string t,int c,bool bold=false)=>Add(g,new TextBlock{Text=t,FontWeight=bold?FontWeight.Bold:FontWeight.Normal,TextTrimming=TextTrimming.CharacterEllipsis},c);private static void Add(Grid g,Control x,int c){x.Margin=new Thickness(0,0,8,0);Grid.SetColumn(x,c);g.Children.Add(x);}
}
internal sealed class SupplierRmaCapaGovernanceReviewDialog:Window
{
 private readonly SupplierRmaCapaGovernanceReviewService _service;private readonly Action _saved;private readonly ComboBox _outcome=new(){ItemsSource=new[]{"Confermato","Con riserva","Non conforme"},SelectedIndex=0};private readonly TextBox _reviewer=new(){Text=Environment.UserName},_next=new(){Text=DateTime.Today.AddMonths(6).ToString("yyyy-MM-dd")},_notes=new(){AcceptsReturn=true,TextWrapping=TextWrapping.Wrap,MinHeight=100},_decisions=new(){AcceptsReturn=true,TextWrapping=TextWrapping.Wrap,MinHeight=100};private readonly TextBlock _message=new();
 public SupplierRmaCapaGovernanceReviewDialog(SupplierRmaCapaGovernanceReviewService service,Action saved){_service=service;_saved=saved;Title="Nuovo riesame Governance CAPA";Width=680;Height=690;WindowStartupLocation=WindowStartupLocation.CenterOwner;var analytics=new SupplierRmaCapaGovernanceActionAnalyticsService().Analyze(new SupplierRmaCapaGovernanceActionService().GetAll());var evaluation=new SupplierRmaCapaGovernanceGoalService().Evaluate(analytics);var root=new StackPanel{Margin=new Thickness(24),Spacing=8,Children={new TextBlock{Text="Nuovo riesame Governance CAPA",FontSize=27,FontWeight=FontWeight.Bold},new TextBlock{Text=$"Valutazione corrente: {evaluation.OverallStatus} · {analytics.Total} azioni · {analytics.Overdue} scadute",Foreground=UiTokens.Brush(evaluation.OverallStatus=="Conforme"?UiTokens.Success:UiTokens.Warning)}}};Field(root,"Esito del riesame",_outcome);Field(root,"Responsabile",_reviewer);Field(root,"Prossimo riesame (AAAA-MM-GG)",_next);Field(root,"Osservazioni ed evidenze",_notes);Field(root,"Decisioni e azioni conseguenti",_decisions);root.Children.Add(_message);root.Children.Add(SupplierRmaCorrectiveActionsWindow.Button("Registra e genera verbale",()=>Save(analytics,evaluation),true));Content=new ScrollViewer{Content=root};}
 private void Save(SupplierRmaCapaGovernanceActionAnalytics a,SupplierRmaCapaGovernanceGoalEvaluation e){try{var item=_service.Create(_outcome.SelectedItem?.ToString()??"Confermato",_notes.Text??"",_decisions.Text??"",_reviewer.Text??"",_next.Text??"",a,e);_saved();Process.Start(new ProcessStartInfo{FileName=item.ReportPath,UseShellExecute=true});Close();}catch(Exception ex){_message.Text=ex.Message;_message.Foreground=UiTokens.Brush(UiTokens.Danger);}}private static void Field(StackPanel root,string label,Control c)=>root.Children.Add(new StackPanel{Spacing=3,Children={new TextBlock{Text=label,FontWeight=FontWeight.SemiBold},c}});
}
