using System.Diagnostics;using Avalonia;using Avalonia.Controls;using Avalonia.Layout;using Avalonia.Media;using Accyourate.App.AssetManagement.Services;using Accyourate.App.UIFramework.DesignSystem;using Accyourate.App.UIFramework.Tokens;
namespace Accyourate.App.AssetManagement;
public sealed class SupplierRmaCapaGovernanceReviewsWindow:Window
{
 readonly SupplierRmaCapaGovernanceReviewService _service=new();readonly StackPanel _rows=new();readonly TextBlock _summary=new();
 public SupplierRmaCapaGovernanceReviewsWindow(){Title="Riesami Governance CAPA";Width=1480;Height=740;WindowStartupLocation=WindowStartupLocation.CenterOwner;Content=Build();_service.PublishAlerts();new SupplierRmaCapaGovernanceReviewAttestationService().PublishInvalidNotifications();new SupplierRmaCapaGovernanceReviewRetentionService().PublishAlerts();Load();}
 Control Build(){var root=new DockPanel{Margin=new Thickness(24)};var head=AxResponsivePageHeader.Create("Riesami Governance CAPA","Valutazioni, approvazioni, revisioni, verbali e prossime scadenze.",SupplierRmaCorrectiveActionsWindow.Button("Nuovo riesame",()=>new ReviewCreateDialog(_service,Load).Show(this),true),SupplierRmaCorrectiveActionsWindow.Button("Registro conservazioni",()=>new SupplierRmaCapaGovernanceReviewRetentionRegistryWindow().Show(this)),SupplierRmaCorrectiveActionsWindow.Button("Aggiorna e notifica",()=>{_service.PublishAlerts();Load();}));head.Margin=new Thickness(0,0,0,12);DockPanel.SetDock(head,Dock.Top);root.Children.Add(head);DockPanel.SetDock(_summary,Dock.Top);root.Children.Add(_summary);root.Children.Add(new ScrollViewer{Content=_rows,HorizontalScrollBarVisibility=Avalonia.Controls.Primitives.ScrollBarVisibility.Disabled,VerticalScrollBarVisibility=Avalonia.Controls.Primitives.ScrollBarVisibility.Auto});return root;}
 void Load(){var all=_service.GetAll();_rows.Children.Clear();_rows.MinWidth=0;_rows.Spacing=8;foreach(var x in all)_rows.Children.Add(Row(x));_summary.Text=$"{all.Count} riesami - {all.Count(x=>x.ApprovalStatus=="In approvazione")} in approvazione - {all.Count(x=>x.ApprovalStatus=="Approvato")} approvati";_summary.Foreground=UiTokens.Brush(UiTokens.TextSecondary);_summary.Margin=new Thickness(0,0,0,8);}
 Control Row(SupplierRmaCapaGovernanceReview x){var approve=SupplierRmaCorrectiveActionsWindow.Button("Approva",()=>new ReviewApprovalDialog(x,_service,Load).Show(this),x.ApprovalStatus!="Approvato");var integrity=SupplierRmaCorrectiveActionsWindow.Button("Integrita",()=>new ReviewAttestationDialog(x).Show(this),x.ApprovalStatus=="Approvato");integrity.IsEnabled=x.ApprovalStatus=="Approvato"||new SupplierRmaCapaGovernanceReviewAttestationService().GetAll(x.Id).Count>0;var retention=SupplierRmaCorrectiveActionsWindow.Button("Conserva",()=>new ReviewRetentionDialog(x).Show(this));retention.IsEnabled=x.ApprovalStatus=="Approvato"||new SupplierRmaCapaGovernanceReviewRetentionService().GetAll(x.Id).Count>0;var audit=SupplierRmaCorrectiveActionsWindow.Button("Audit",()=>new ReviewApprovalHistoryWindow(x,_service).Show(this));var report=SupplierRmaCorrectiveActionsWindow.Button("Verbale",()=>Open(x.ReportPath));report.IsEnabled=x.ReportAvailable;return AxResponsiveRecordCard.Create($"Riesame {x.Id:D6}",new[]{new AxResponsiveRecordField("Data",Date(x.ReviewDate),140),new AxResponsiveRecordField("Responsabile",x.Reviewer,180),new AxResponsiveRecordField("Esito",x.Outcome,150),new AxResponsiveRecordField("Indicatori",x.EvaluationStatus,150),new AxResponsiveRecordField("Revisione",x.Revision.ToString(),100),new AxResponsiveRecordField("Prossimo riesame",Date(x.NextReviewDate),160,x.IsOverdue?UiTokens.Danger:null),new AxResponsiveRecordField("Approvazione",x.ApprovalStatus,160)},approve,integrity,retention,audit,report);}
 static void Open(string p){if(File.Exists(p))Process.Start(new ProcessStartInfo{FileName=p,UseShellExecute=true});}static string Date(string v)=>DateTime.TryParse(v,out var d)?d.ToString("dd/MM/yyyy"):v;static void Cell(Grid g,string t,int c,bool bold=false)=>Add(g,new TextBlock{Text=t,FontWeight=bold?FontWeight.Bold:FontWeight.Normal,TextTrimming=TextTrimming.CharacterEllipsis},c);static void Add(Grid g,Control x,int c){x.Margin=new Thickness(0,0,8,0);Grid.SetColumn(x,c);g.Children.Add(x);}
}
internal sealed class ReviewCreateDialog:Window
{
 readonly SupplierRmaCapaGovernanceReviewService _service;readonly Action _saved;readonly ComboBox _outcome=new(){ItemsSource=new[]{"Confermato","Con riserva","Non conforme"},SelectedIndex=0};readonly TextBox _reviewer=new(){Text=Environment.UserName},_next=new(){Text=DateTime.Today.AddMonths(6).ToString("yyyy-MM-dd")},_notes=new(){AcceptsReturn=true,TextWrapping=TextWrapping.Wrap,MinHeight=100},_decisions=new(){AcceptsReturn=true,TextWrapping=TextWrapping.Wrap,MinHeight=100};readonly TextBlock _message=new();
 public ReviewCreateDialog(SupplierRmaCapaGovernanceReviewService service,Action saved){_service=service;_saved=saved;Title="Nuovo riesame Governance CAPA";Width=680;Height=690;WindowStartupLocation=WindowStartupLocation.CenterOwner;var analytics=new SupplierRmaCapaGovernanceActionAnalyticsService().Analyze(new SupplierRmaCapaGovernanceActionService().GetAll());var evaluation=new SupplierRmaCapaGovernanceGoalService().Evaluate(analytics);var root=new StackPanel{Margin=new Thickness(24),Spacing=8,Children={new TextBlock{Text="Nuovo riesame Governance CAPA",FontSize=27,FontWeight=FontWeight.Bold},new TextBlock{Text=$"Valutazione corrente: {evaluation.OverallStatus} - {analytics.Total} azioni - {analytics.Overdue} scadute"}}};Field(root,"Esito",_outcome);Field(root,"Responsabile",_reviewer);Field(root,"Prossimo riesame",_next);Field(root,"Osservazioni",_notes);Field(root,"Decisioni",_decisions);root.Children.Add(_message);root.Children.Add(SupplierRmaCorrectiveActionsWindow.Button("Registra e genera verbale",()=>Save(analytics,evaluation),true));Content=new ScrollViewer{Content=root};}
 void Save(SupplierRmaCapaGovernanceActionAnalytics a,SupplierRmaCapaGovernanceGoalEvaluation e){try{var item=_service.Create(_outcome.SelectedItem?.ToString()??"Confermato",_notes.Text??"",_decisions.Text??"",_reviewer.Text??"",_next.Text??"",a,e);_saved();Process.Start(new ProcessStartInfo{FileName=item.ReportPath,UseShellExecute=true});Close();}catch(Exception ex){_message.Text=ex.Message;_message.Foreground=UiTokens.Brush(UiTokens.Danger);}}static void Field(StackPanel root,string label,Control c)=>root.Children.Add(new StackPanel{Spacing=3,Children={new TextBlock{Text=label,FontWeight=FontWeight.SemiBold},c}});
}
internal sealed class ReviewApprovalDialog:Window
{
 readonly SupplierRmaCapaGovernanceReview _item;readonly SupplierRmaCapaGovernanceReviewService _service;readonly Action _saved;readonly TextBox _approver=new(),_notes=new(){AcceptsReturn=true,TextWrapping=TextWrapping.Wrap,MinHeight=110};readonly TextBlock _message=new();
 public ReviewApprovalDialog(SupplierRmaCapaGovernanceReview item,SupplierRmaCapaGovernanceReviewService service,Action saved){_item=item;_service=service;_saved=saved;Title="Approvazione riesame Governance CAPA";Width=650;Height=520;WindowStartupLocation=WindowStartupLocation.CenterOwner;_approver.Text=string.IsNullOrWhiteSpace(item.Approver)?Environment.UserName:item.Approver;var root=new StackPanel{Margin=new Thickness(24),Spacing=8,Children={new TextBlock{Text="Approvazione riesame",FontSize=26,FontWeight=FontWeight.Bold},new TextBlock{Text=$"Riesame #{item.Id:D6} - Revisione {item.Revision} - {item.ApprovalStatus}"},new TextBlock{Text="Approvatore",FontWeight=FontWeight.SemiBold},_approver,new TextBlock{Text="Note / motivazione",FontWeight=FontWeight.SemiBold},_notes,_message}};var buttons=new StackPanel{Orientation=Orientation.Horizontal,Spacing=8};if(item.ApprovalStatus is "Bozza" or "Rifiutato" or "Riaperto")buttons.Children.Add(SupplierRmaCorrectiveActionsWindow.Button("Invia in approvazione",()=>Run(()=>_service.Submit(item.Id,_approver.Text??"",Environment.UserName)),true));if(item.ApprovalStatus=="In approvazione"){buttons.Children.Add(SupplierRmaCorrectiveActionsWindow.Button("Approva",()=>Run(()=>_service.Decide(item.Id,true,_notes.Text??"",Environment.UserName)),true));buttons.Children.Add(SupplierRmaCorrectiveActionsWindow.Button("Rifiuta",()=>Run(()=>_service.Decide(item.Id,false,_notes.Text??"",Environment.UserName))));}if(item.ApprovalStatus=="Approvato")buttons.Children.Add(SupplierRmaCorrectiveActionsWindow.Button("Riapri",()=>Run(()=>_service.Reopen(item.Id,_notes.Text??"",Environment.UserName))));root.Children.Add(buttons);Content=root;}
 void Run(Action action){try{action();_saved();Close();}catch(Exception ex){_message.Text=ex.Message;_message.Foreground=UiTokens.Brush(UiTokens.Danger);}}
}
internal sealed class ReviewApprovalHistoryWindow:Window
{
 public ReviewApprovalHistoryWindow(SupplierRmaCapaGovernanceReview item,SupplierRmaCapaGovernanceReviewService service){Title="Audit approvazione riesame";Width=900;Height=600;WindowStartupLocation=WindowStartupLocation.CenterOwner;var root=new StackPanel{Margin=new Thickness(24),Spacing=8,Children={new TextBlock{Text="Audit approvazione",FontSize=26,FontWeight=FontWeight.Bold},new TextBlock{Text=$"Riesame #{item.Id:D6} - revisione {item.Revision}"}}};foreach(var x in service.ApprovalHistory(item.Id))root.Children.Add(new Border{Padding=new Thickness(10),BorderBrush=UiTokens.Brush(UiTokens.Border),BorderThickness=new Thickness(0,0,0,1),Child=new StackPanel{Children={new TextBlock{Text=$"{x.EventType} - {Date(x.CreatedAt)}",FontWeight=FontWeight.Bold},new TextBlock{Text=$"{x.OldStatus} -> {x.NewStatus}"},new TextBlock{Text=x.Notes,TextWrapping=TextWrapping.Wrap},new TextBlock{Text=$"Operatore: {x.CreatedBy}"}}}});Content=new ScrollViewer{Content=root};}static string Date(string v)=>DateTime.TryParse(v,out var d)?d.ToString("dd/MM/yyyy HH:mm"):v;
}
internal sealed class ReviewAttestationDialog:Window
{
 readonly SupplierRmaCapaGovernanceReview _item;readonly SupplierRmaCapaGovernanceReviewAttestationService _service=new();readonly TextBox _role=new(){Text="Responsabile qualita"};readonly TextBlock _message=new();readonly StackPanel _history=new();
 public ReviewAttestationDialog(SupplierRmaCapaGovernanceReview item){_item=item;Title="Integrita riesame Governance CAPA";Width=780;Height=620;WindowStartupLocation=WindowStartupLocation.CenterOwner;var root=new StackPanel{Margin=new Thickness(24),Spacing=9,Children={new TextBlock{Text="Attestazione e integrita",FontSize=26,FontWeight=FontWeight.Bold},new TextBlock{Text=$"Riesame #{item.Id:D6} - revisione {item.Revision} - {item.ApprovalStatus}"},new TextBlock{Text="Ruolo dell'attestatore",FontWeight=FontWeight.SemiBold},_role,_message}};var actions=new StackPanel{Orientation=Orientation.Horizontal,Spacing=8};var attest=SupplierRmaCorrectiveActionsWindow.Button("Genera attestazione",Create,true);attest.IsEnabled=item.ApprovalStatus=="Approvato";actions.Children.Add(attest);actions.Children.Add(SupplierRmaCorrectiveActionsWindow.Button("Verifica ora",Load));root.Children.Add(actions);root.Children.Add(new TextBlock{Text="Registro attestazioni",FontSize=20,FontWeight=FontWeight.Bold,Margin=new Thickness(0,12,0,0)});root.Children.Add(_history);Content=new ScrollViewer{Content=root};Load();}
 void Load(){_history.Children.Clear();var all=_service.GetAll(_item.Id);if(all.Count==0){_history.Children.Add(new TextBlock{Text="Nessuna attestazione presente.",Foreground=UiTokens.Brush(UiTokens.TextSecondary)});return;}foreach(var x in all){var row=new Grid{ColumnDefinitions=new ColumnDefinitions("90,120,140,*,100")};Cell(row,$"R{x.Revision}",0,true);Cell(row,Date(x.AttestedAt),1);Cell(row,x.AttestedBy,2);Cell(row,x.ValidationStatus,3,!x.IsValid);var open=SupplierRmaCorrectiveActionsWindow.Button("Certificato",()=>Open(x.CertificatePath));open.IsEnabled=x.CertificateAvailable;Add(row,open,4);_history.Children.Add(new Border{Padding=new Thickness(8),BorderBrush=UiTokens.Brush(UiTokens.Border),BorderThickness=new Thickness(0,0,0,1),Child=row});}}
 void Create(){try{var result=_service.Attest(_item,_role.Text??"",Environment.UserName);Load();Open(result.CertificatePath);}catch(Exception ex){_message.Text=ex.Message;_message.Foreground=UiTokens.Brush(UiTokens.Danger);}}
 static void Open(string path){if(File.Exists(path))Process.Start(new ProcessStartInfo{FileName=path,UseShellExecute=true});}static string Date(string value)=>DateTime.TryParse(value,out var date)?date.ToString("dd/MM/yyyy HH:mm"):value;static void Cell(Grid grid,string text,int column,bool alert=false){var value=new TextBlock{Text=text,FontWeight=alert?FontWeight.Bold:FontWeight.Normal,Foreground=alert?UiTokens.Brush(UiTokens.Danger):UiTokens.Brush(UiTokens.TextPrimary),TextTrimming=TextTrimming.CharacterEllipsis};Add(grid,value,column);}static void Add(Grid grid,Control control,int column){control.Margin=new Thickness(0,0,8,0);Grid.SetColumn(control,column);grid.Children.Add(control);}
}
internal sealed class ReviewRetentionDialog:Window
{
 readonly SupplierRmaCapaGovernanceReview _item;readonly SupplierRmaCapaGovernanceReviewRetentionService _service=new();readonly TextBox _custodian=new(){Text=Environment.UserName},_days=new(){Text="3650"};readonly TextBlock _message=new();readonly StackPanel _history=new();
 public ReviewRetentionDialog(SupplierRmaCapaGovernanceReview item){_item=item;Title="Conservazione riesame Governance CAPA";Width=860;Height=650;WindowStartupLocation=WindowStartupLocation.CenterOwner;var root=new StackPanel{Margin=new Thickness(24),Spacing=9,Children={new TextBlock{Text="Conservazione controllata",FontSize=26,FontWeight=FontWeight.Bold},new TextBlock{Text=$"Riesame #{item.Id:D6} - revisione {item.Revision} - {item.ApprovalStatus}"},new TextBlock{Text="Custode",FontWeight=FontWeight.SemiBold},_custodian,new TextBlock{Text="Durata della conservazione (giorni)",FontWeight=FontWeight.SemiBold},_days,_message}};var actions=new StackPanel{Orientation=Orientation.Horizontal,Spacing=8};var archive=SupplierRmaCorrectiveActionsWindow.Button("Crea archivio",Create,true);archive.IsEnabled=item.ApprovalStatus=="Approvato";actions.Children.Add(archive);actions.Children.Add(SupplierRmaCorrectiveActionsWindow.Button("Verifica ora",Load));root.Children.Add(actions);root.Children.Add(new TextBlock{Text="Registro conservazioni",FontSize=20,FontWeight=FontWeight.Bold,Margin=new Thickness(0,12,0,0)});root.Children.Add(_history);Content=new ScrollViewer{Content=root};Load();}
 void Load(){_history.Children.Clear();var all=_service.GetAll(_item.Id);if(all.Count==0){_history.Children.Add(new TextBlock{Text="Nessuna conservazione presente.",Foreground=UiTokens.Brush(UiTokens.TextSecondary)});return;}foreach(var x in all){var row=new Grid{ColumnDefinitions=new ColumnDefinitions("70,125,150,130,*,90")};Cell(row,$"R{x.Revision}",0,true);Cell(row,Date(x.ArchivedAt),1);Cell(row,x.Custodian,2);Cell(row,DateOnly(x.RetentionUntil),3);Cell(row,x.ValidationStatus,4,!x.IsValid);var open=SupplierRmaCorrectiveActionsWindow.Button("Archivio",()=>Open(x.ArchivePath));open.IsEnabled=x.ArchiveAvailable;Add(row,open,5);_history.Children.Add(new Border{Padding=new Thickness(8),BorderBrush=UiTokens.Brush(UiTokens.Border),BorderThickness=new Thickness(0,0,0,1),Child=row});}}
 void Create(){try{if(!int.TryParse(_days.Text,out var days))throw new InvalidOperationException("Indica una durata valida in giorni.");var result=_service.Archive(_item,_custodian.Text??"",days,Environment.UserName);Load();Open(result.ArchivePath);}catch(Exception ex){_message.Text=ex.Message;_message.Foreground=UiTokens.Brush(UiTokens.Danger);}}
 static void Open(string path){if(File.Exists(path))Process.Start(new ProcessStartInfo{FileName=path,UseShellExecute=true});}static string Date(string value)=>DateTime.TryParse(value,out var date)?date.ToString("dd/MM/yyyy HH:mm"):value;static string DateOnly(string value)=>DateTime.TryParse(value,out var date)?date.ToString("dd/MM/yyyy"):value;static void Cell(Grid grid,string text,int column,bool alert=false){var value=new TextBlock{Text=text,FontWeight=alert?FontWeight.Bold:FontWeight.Normal,Foreground=alert?UiTokens.Brush(UiTokens.Danger):UiTokens.Brush(UiTokens.TextPrimary),TextTrimming=TextTrimming.CharacterEllipsis};Add(grid,value,column);}static void Add(Grid grid,Control control,int column){control.Margin=new Thickness(0,0,8,0);Grid.SetColumn(control,column);grid.Children.Add(control);}
}
