using System.Text;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Layout;
using Avalonia.Media;
using Avalonia.Platform.Storage;
using Accyourate.App.AssetManagement.Models;
using Accyourate.App.AssetManagement.Services;
using Accyourate.App.UIFramework.Tokens;

namespace Accyourate.App.AssetManagement;

public sealed class SupplierCommunicationRegisterWindow:Window
{
    private readonly SupplierRmaPortalRepository _repository=new();private readonly TextBox _search=new(){Watermark="Cerca fornitore, oggetto o testo..."};private readonly ComboBox _supplier=new(),_type=new(){ItemsSource=new[]{"Tutti i tipi","Email","Telefonata","Richiesta","Risposta","Sollecito"},SelectedIndex=0},_direction=new(){ItemsSource=new[]{"Tutte le direzioni","In uscita","In entrata"},SelectedIndex=0},_period=new(){ItemsSource=new[]{"Tutto il periodo","Ultimi 7 giorni","Ultimi 30 giorni","Anno corrente"},SelectedIndex=0},_status=new(){ItemsSource=new[]{"Tutti gli stati","Bozza","Inviata","Risposta ricevuta","Registrata"},SelectedIndex=0};private readonly StackPanel _rows=new(),_kpis=new();private readonly TextBlock _summary=new();private IReadOnlyList<MaintenanceSupplier> _suppliers=[];
    public SupplierCommunicationRegisterWindow(){Title="Registro comunicazioni fornitori";Width=1500;Height=850;MinWidth=1100;MinHeight=650;WindowStartupLocation=WindowStartupLocation.CenterOwner;Content=Build();_search.TextChanged+=(_,_)=>Refresh();_supplier.SelectionChanged+=(_,_)=>Refresh();_type.SelectionChanged+=(_,_)=>Refresh();_direction.SelectionChanged+=(_,_)=>Refresh();_period.SelectionChanged+=(_,_)=>Refresh();_status.SelectionChanged+=(_,_)=>Refresh();Refresh();}
    private Control Build(){_suppliers=new MaintenancePurchasingRepository().GetSuppliers();_supplier.ItemsSource=new[]{"Tutti i fornitori"}.Concat(_suppliers.Select(x=>x.Name)).ToList();_supplier.SelectedIndex=0;var root=new StackPanel{Margin=new Thickness(24),Spacing=12};var header=new Grid{ColumnDefinitions=new ColumnDefinitions("*,Auto")};header.Children.Add(new StackPanel{Spacing=3,Children={new TextBlock{Text="Registro comunicazioni fornitori",FontSize=29,FontWeight=FontWeight.Bold},new TextBlock{Text="E-mail, telefonate, solleciti e risposte raccolti in un unico registro.",Foreground=UiTokens.Brush(UiTokens.TextSecondary)}}});var export=Button("Esporta CSV",Export,true);Grid.SetColumn(export,1);header.Children.Add(export);root.Children.Add(header);_kpis.Orientation=Orientation.Horizontal;_kpis.Spacing=10;root.Children.Add(_kpis);var first=new Grid{ColumnDefinitions=new ColumnDefinitions("*,220,180,180")};Add(first,_search,0);Add(first,_supplier,1);Add(first,_type,2);Add(first,_direction,3);root.Children.Add(first);var second=new StackPanel{Orientation=Orientation.Horizontal,Spacing=8};second.Children.Add(_period);second.Children.Add(_status);second.Children.Add(Button("Aggiorna",Refresh));root.Children.Add(second);root.Children.Add(_summary);root.Children.Add(new ScrollViewer{Content=_rows,HorizontalScrollBarVisibility=Avalonia.Controls.Primitives.ScrollBarVisibility.Auto});return new ScrollViewer{Content=root,VerticalScrollBarVisibility=Avalonia.Controls.Primitives.ScrollBarVisibility.Auto};}
    private void Refresh(){if(_supplier.ItemsSource is null)return;var all=_repository.GetAllCommunications();var values=Filter(all).ToList();_kpis.Children.Clear();_kpis.Children.Add(Kpi("Totali",all.Count.ToString(),UiTokens.BrandBlue));_kpis.Children.Add(Kpi("Bozze",all.Count(x=>x.CommunicationStatus=="Bozza").ToString(),UiTokens.Warning));_kpis.Children.Add(Kpi("Inviate",all.Count(x=>x.CommunicationStatus=="Inviata").ToString(),UiTokens.BrandBlue));_kpis.Children.Add(Kpi("Risposte",all.Count(x=>x.Direction=="In entrata"||x.CommunicationStatus=="Risposta ricevuta").ToString(),UiTokens.Success));_kpis.Children.Add(Kpi("Tempo medio risposta",AverageResponse(all),UiTokens.BrandBlue));_summary.Text=$"{values.Count} comunicazioni visualizzate";_summary.Foreground=UiTokens.Brush(UiTokens.TextSecondary);_rows.Children.Clear();_rows.Children.Add(Header());for(var i=0;i<values.Count;i++)_rows.Children.Add(Row(values[i],i));if(values.Count==0)_rows.Children.Add(new TextBlock{Text="Nessuna comunicazione corrisponde ai filtri selezionati.",Margin=new Thickness(12),Foreground=UiTokens.Brush(UiTokens.TextSecondary)});}
    private IEnumerable<SupplierPortalInteraction> Filter(IEnumerable<SupplierPortalInteraction> values){var q=(_search.Text??"").Trim();var supplierId=_supplier.SelectedIndex>0&&_supplier.SelectedIndex<=_suppliers.Count?_suppliers[_supplier.SelectedIndex-1].Id:0;var type=_type.SelectedItem?.ToString()??"Tutti i tipi";var direction=_direction.SelectedItem?.ToString()??"Tutte le direzioni";var status=_status.SelectedItem?.ToString()??"Tutti gli stati";return values.Where(x=>q.Length==0||$"{x.SupplierName} {x.Subject} {x.Message}".Contains(q,StringComparison.OrdinalIgnoreCase)).Where(x=>supplierId==0||x.SupplierId==supplierId).Where(x=>type=="Tutti i tipi"||x.Type==type).Where(x=>direction=="Tutte le direzioni"||x.Direction==direction).Where(x=>status=="Tutti gli stati"||x.CommunicationStatus==status).Where(MatchesPeriod);}
    private bool MatchesPeriod(SupplierPortalInteraction x){if(!DateTime.TryParse(x.CreatedAt,out var date))return true;return (_period.SelectedItem?.ToString()??"Tutto il periodo") switch{"Ultimi 7 giorni"=>date>=DateTime.Today.AddDays(-7),"Ultimi 30 giorni"=>date>=DateTime.Today.AddDays(-30),"Anno corrente"=>date.Year==DateTime.Today.Year,_=>true};}
    private Control Header(){var g=GridRow();Text(g,"Data",0,true);Text(g,"Fornitore",1,true);Text(g,"Tipo",2,true);Text(g,"Direzione",3,true);Text(g,"Oggetto",4,true);Text(g,"Stato",5,true);Text(g,"Risposta",6,true);Text(g,"Azioni",7,true);return new Border{Padding=new Thickness(8),Background=UiTokens.Brush(UiTokens.SurfaceAlt),Child=g};}
    private Control Row(SupplierPortalInteraction x,int index){var g=GridRow();Text(g,Date(x.CreatedAt),0);Text(g,x.SupplierName,1,true);Text(g,x.Type,2);Text(g,x.Direction,3);Text(g,x.Subject,4,true);Text(g,x.CommunicationStatus,5);Text(g,ResponseTime(x),6);var actions=new StackPanel{Orientation=Orientation.Horizontal,Spacing=4};actions.Children.Add(Button("Leggi",()=>new SupplierInteractionDetailWindow(x,$"RMA #{x.RmaId}").Show(this)));actions.Children.Add(Button("Portale",()=>new SupplierRmaPortalWindow(x.SupplierId,x.RmaId).Show(this)));if(x.Direction=="In uscita"&&x.CommunicationStatus=="Bozza")actions.Children.Add(Button("Segna inviata",()=>{_repository.UpdateCommunicationStatus(x.Id,"Inviata");Refresh();},true));if(x.Direction=="In uscita"&&x.CommunicationStatus is "Inviata" or "Registrata")actions.Children.Add(Button("Registra risposta",()=>Response(x),true));Add(g,actions,7);return new Border{Padding=new Thickness(8,7),Background=UiTokens.Brush(index%2==0?UiTokens.Surface:UiTokens.SurfaceAlt),BorderBrush=UiTokens.Brush(UiTokens.Border),BorderThickness=new Thickness(0,0,0,1),Child=g};}
    private async void Response(SupplierPortalInteraction original){var response=await new SupplierCommunicationResponseDialog(original).ShowDialog<(string Subject,string Message)?>(this);if(response is null)return;_repository.AddInteraction(new(){SupplierId=original.SupplierId,RmaId=original.RmaId,Type="Risposta",Direction="In entrata",Subject=response.Value.Subject,Message=response.Value.Message,Status="Aperta",CommunicationStatus="Risposta ricevuta",ParentInteractionId=original.Id,ResponseReceivedAt=DateTime.Now.ToString("s"),CreatedBy=Environment.UserName});_repository.UpdateCommunicationStatus(original.Id,"Risposta ricevuta");Refresh();}
    private async void Export(){var values=Filter(_repository.GetAllCommunications()).ToList();var file=await StorageProvider.SaveFilePickerAsync(new FilePickerSaveOptions{Title="Esporta registro comunicazioni",SuggestedFileName=$"Registro-comunicazioni-{DateTime.Today:yyyyMMdd}.csv",FileTypeChoices=new[]{new FilePickerFileType("CSV"){Patterns=new[]{"*.csv"}}}});var path=file?.TryGetLocalPath();if(string.IsNullOrWhiteSpace(path))return;var sb=new StringBuilder();sb.AppendLine("Data;Fornitore;Tipo;Direzione;Oggetto;Stato;Messaggio");foreach(var x in values)sb.AppendLine(string.Join(";",new[]{Date(x.CreatedAt),x.SupplierName,x.Type,x.Direction,x.Subject,x.CommunicationStatus,x.Message}.Select(Csv)));File.WriteAllText(path,sb.ToString(),new UTF8Encoding(true));}
    private static string AverageResponse(IEnumerable<SupplierPortalInteraction> values){var list=values.Where(x=>DateTime.TryParse(x.SentAt,out _)&&DateTime.TryParse(x.ResponseReceivedAt,out _)).Select(x=>(DateTime.Parse(x.ResponseReceivedAt)-DateTime.Parse(x.SentAt)).TotalHours).Where(x=>x>=0).ToList();return list.Count==0?"—":$"{list.Average():N1} h";}
    private static string ResponseTime(SupplierPortalInteraction x)=>DateTime.TryParse(x.SentAt,out var sent)&&DateTime.TryParse(x.ResponseReceivedAt,out var response)?$"{(response-sent).TotalHours:N1} h":"—";
    private static Grid GridRow()=>new(){MinWidth=1400,ColumnDefinitions=new ColumnDefinitions("115,180,110,115,*,145,110,420")};private static string Date(string value)=>DateTime.TryParse(value,out var d)?d.ToString("dd/MM/yyyy HH:mm"):"—";private static string Csv(string value)=>$"\"{value.Replace("\"","\"\"").Replace("\r"," ").Replace("\n"," ")}\"";
    private static void Text(Grid g,string value,int col,bool strong=false)=>Add(g,new TextBlock{Text=string.IsNullOrWhiteSpace(value)?"—":value,FontWeight=strong?FontWeight.SemiBold:FontWeight.Normal,TextTrimming=TextTrimming.CharacterEllipsis,VerticalAlignment=VerticalAlignment.Center},col);private static void Add(Grid g,Control c,int col){c.Margin=new Thickness(0,0,8,0);Grid.SetColumn(c,col);g.Children.Add(c);}private static Button Button(string text,Action action,bool primary=false){var b=new Button{Content=text,Padding=new Thickness(8,5),Background=UiTokens.Brush(primary?UiTokens.BrandBlue:UiTokens.SurfaceAlt),Foreground=primary?Brushes.White:UiTokens.Brush(UiTokens.TextPrimary)};b.Click+=(_,_)=>action();return b;}private static Control Kpi(string label,string value,string color)=>new Border{Width=245,Padding=new Thickness(12),Background=UiTokens.Brush(UiTokens.Surface),BorderBrush=UiTokens.Brush(UiTokens.Border),BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(12),Child=new StackPanel{Children={new TextBlock{Text=value,FontSize=22,FontWeight=FontWeight.Bold,Foreground=UiTokens.Brush(color)},new TextBlock{Text=label,Foreground=UiTokens.Brush(UiTokens.TextSecondary)}}}};
}

internal sealed class SupplierCommunicationResponseDialog:Window
{
    private readonly TextBox _subject=new(),_message=new(){AcceptsReturn=true,TextWrapping=TextWrapping.Wrap,MinHeight=180};public SupplierCommunicationResponseDialog(SupplierPortalInteraction original){Title="Registra risposta fornitore";Width=620;Height=520;WindowStartupLocation=WindowStartupLocation.CenterOwner;_subject.Text=original.Subject.StartsWith("RE:",StringComparison.OrdinalIgnoreCase)?original.Subject:$"RE: {original.Subject}";var root=SupplierContactDialog.Panel("Risposta ricevuta");SupplierContactDialog.Field(root,"Oggetto",_subject);SupplierContactDialog.Field(root,"Messaggio",_message);root.Children.Add(SupplierContactDialog.SaveButton("Registra risposta",()=>{if(!string.IsNullOrWhiteSpace(_message.Text))Close((_subject.Text??"",_message.Text??""));}));Content=root;}
}
