using System.Diagnostics;
using System.Text;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Layout;
using Avalonia.Media;
using Avalonia.Platform.Storage;
using Accyourate.App.AssetManagement.Models;
using Accyourate.App.AssetManagement.Services;
using Accyourate.App.UIFramework.Tokens;

namespace Accyourate.App.AssetManagement;

public sealed class SupplierRmaCentralAuditRegisterWindow : Window
{
    private readonly SparePartRmaRepository _rma=new();private readonly SupplierRmaValidationService _validation=new();private readonly SupplierRmaAuditScheduleService _schedules=new();
    private readonly TextBox _search=new(){Watermark="Cerca pratica, evento, operatore o note..."};private readonly ComboBox _type=new(){ItemsSource=new[]{"Tutti gli eventi","Pianificazione","Audit eseguito","Validazione","Anomalia"},SelectedIndex=0,MinWidth=180};private readonly ComboBox _status=new(){ItemsSource=new[]{"Tutti gli stati","Completo","Completata","Attiva","In scadenza","Scaduta","Non validata","Chiusa non validata","Disattiva"},SelectedIndex=0,MinWidth=180};
    private readonly StackPanel _rows=new(),_kpis=new(){Orientation=Orientation.Horizontal,Spacing=10};private readonly TextBlock _summary=new(),_message=new();
    public SupplierRmaCentralAuditRegisterWindow(){Title="Registro audit RMA centralizzato";Width=1360;Height=800;MinWidth=1040;MinHeight=620;WindowStartupLocation=WindowStartupLocation.CenterOwner;Content=Build();_search.TextChanged+=(_,_)=>LoadData();_type.SelectionChanged+=(_,_)=>LoadData();_status.SelectionChanged+=(_,_)=>LoadData();LoadData();}
    private Control Build(){var root=new DockPanel{Margin=new Thickness(24)};var actions=new StackPanel{Orientation=Orientation.Horizontal,Spacing=8};actions.Children.Add(Button("Esporta CSV",Export,true));actions.Children.Add(Button("Aggiorna",LoadData));var head=new Grid{ColumnDefinitions=new ColumnDefinitions("*,Auto"),Margin=new Thickness(0,0,0,12)};Add(head,new StackPanel{Spacing=3,Children={new TextBlock{Text="Registro audit RMA centralizzato",FontSize=28,FontWeight=FontWeight.Bold},new TextBlock{Text="Pianificazioni, esecuzioni, validazioni, documenti e anomalie in un'unica vista.",Foreground=UiTokens.Brush(UiTokens.TextSecondary)}}},0);Add(head,actions,1);DockPanel.SetDock(head,Dock.Top);root.Children.Add(head);_kpis.Margin=new Thickness(0,0,0,10);DockPanel.SetDock(_kpis,Dock.Top);root.Children.Add(_kpis);var filters=new Grid{ColumnDefinitions=new ColumnDefinitions("*,190,190"),Margin=new Thickness(0,0,0,8)};Add(filters,_search,0);Add(filters,_type,1);Add(filters,_status,2);DockPanel.SetDock(filters,Dock.Top);root.Children.Add(filters);_summary.Foreground=UiTokens.Brush(UiTokens.TextSecondary);_summary.Margin=new Thickness(0,0,0,8);DockPanel.SetDock(_summary,Dock.Top);root.Children.Add(_summary);DockPanel.SetDock(_message,Dock.Top);root.Children.Add(_message);root.Children.Add(new ScrollViewer{Content=_rows,HorizontalScrollBarVisibility=Avalonia.Controls.Primitives.ScrollBarVisibility.Auto,VerticalScrollBarVisibility=Avalonia.Controls.Primitives.ScrollBarVisibility.Auto});return root;}
    private void LoadData(){try{var all=AllEvents();UpdateKpis(all);var values=Filter(all).ToList();_rows.Children.Clear();_rows.MinWidth=1250;_rows.Children.Add(Header());for(var i=0;i<values.Count;i++)_rows.Children.Add(Row(values[i],i));_summary.Text=$"{values.Count} eventi visualizzati · {values.Count(x=>x.Type=="Anomalia")} anomalie · {values.Count(x=>!string.IsNullOrWhiteSpace(x.DocumentPath)&&File.Exists(x.DocumentPath))} documenti disponibili";_message.Text="";}catch(Exception ex){Status($"Registro non caricato: {ex.Message}",true);}}
    private List<AuditEvent> AllEvents(){var values=new List<AuditEvent>();var cases=_rma.GetAll();var closures=_validation.GetClosures();var validated=closures.Select(x=>x.RmaId).Distinct().ToHashSet();foreach(var x in _schedules.GetSchedules())values.Add(new("Pianificazione",x.Name,x.DisplayStatus,x.NextRun,"Sistema",$"Frequenza {x.Frequency}","",x.Id));foreach(var x in _schedules.GetRuns())values.Add(new("Audit eseguito",x.ScheduleName,x.Status,x.ExecutedAt,x.ExecutedBy,x.Notes,x.PdfPath,x.ScheduleId));foreach(var x in closures)values.Add(new("Validazione",x.CaseNumber,x.ValidationStatus,x.ClosedAt,x.ClosedBy,x.Notes,SupplierRmaValidationService.DossierPath(x.CaseNumber),x.RmaId));foreach(var x in cases.Where(x=>IsOverdue(x)||!validated.Contains(x.Id))){var overdue=IsOverdue(x);var status=overdue?"Scaduta":x.Status==SparePartRmaStatus.Closed?"Chiusa non validata":"Non validata";values.Add(new("Anomalia",x.CaseNumber,status,overdue?x.DueDate:x.UpdatedAt,"Sistema",$"Stato pratica: {x.Status}",SupplierRmaValidationService.DossierPath(x.CaseNumber),x.Id));}return values.OrderByDescending(x=>Parse(x.Date)).ThenBy(x=>x.Type).ToList();}
    private IEnumerable<AuditEvent> Filter(IEnumerable<AuditEvent> values){var q=(_search.Text??"").Trim();var type=_type.SelectedItem?.ToString()??"Tutti gli eventi";var status=_status.SelectedItem?.ToString()??"Tutti gli stati";return values.Where(x=>type=="Tutti gli eventi"||x.Type==type).Where(x=>status=="Tutti gli stati"||x.Status==status).Where(x=>q.Length==0||$"{x.Type} {x.Reference} {x.Status} {x.User} {x.Notes}".Contains(q,StringComparison.OrdinalIgnoreCase));}
    private void UpdateKpis(IReadOnlyList<AuditEvent> values){_kpis.Children.Clear();_kpis.Children.Add(Kpi("Eventi audit",values.Count,UiTokens.BrandBlue));_kpis.Children.Add(Kpi("Pianificazioni",values.Count(x=>x.Type=="Pianificazione"),UiTokens.BrandBlue));_kpis.Children.Add(Kpi("Audit eseguiti",values.Count(x=>x.Type=="Audit eseguito"),UiTokens.Success));_kpis.Children.Add(Kpi("Validazioni",values.Count(x=>x.Type=="Validazione"),UiTokens.Success));_kpis.Children.Add(Kpi("Anomalie",values.Count(x=>x.Type=="Anomalia"),values.Any(x=>x.Type=="Anomalia")?UiTokens.Danger:UiTokens.Success));}
    private Control Header(){var g=GridRow();var labels=new[]{"Tipo","Riferimento","Stato","Data","Operatore","Note","Documento"};for(var i=0;i<labels.Length;i++)Text(g,labels[i],i,true);return new Border{Background=UiTokens.Brush(UiTokens.SurfaceAlt),Padding=new Thickness(8),Child=g};}
    private Control Row(AuditEvent x,int index){var g=GridRow();Text(g,x.Type,0,true);Text(g,x.Reference,1,true);Add(g,Badge(x.Status),2);Text(g,DateValue(x.Date),3);Text(g,x.User,4);Text(g,x.Notes,5);var exists=!string.IsNullOrWhiteSpace(x.DocumentPath)&&File.Exists(x.DocumentPath);var open=Button(exists?"Apri":"—",()=>Open(x.DocumentPath));open.IsEnabled=exists;Add(g,open,6);return new Border{Background=UiTokens.Brush(index%2==0?UiTokens.Surface:UiTokens.SurfaceAlt),BorderBrush=UiTokens.Brush(UiTokens.Border),BorderThickness=new Thickness(0,0,0,1),Padding=new Thickness(8,6),Child=g};}
    private async void Export(){try{var values=Filter(AllEvents()).ToList();var file=await StorageProvider.SaveFilePickerAsync(new FilePickerSaveOptions{Title="Esporta registro audit RMA",SuggestedFileName=$"Registro-audit-RMA-{DateTime.Today:yyyyMMdd}.csv",FileTypeChoices=new[]{new FilePickerFileType("CSV"){Patterns=new[]{"*.csv"}}}});var path=file?.TryGetLocalPath();if(string.IsNullOrWhiteSpace(path))return;var lines=new List<string>{"Tipo;Riferimento;Stato;Data;Operatore;Note;Documento"};foreach(var x in values)lines.Add(string.Join(";",new[]{x.Type,x.Reference,x.Status,DateValue(x.Date),x.User,x.Notes,x.DocumentPath}.Select(Csv)));File.WriteAllLines(path,lines,new UTF8Encoding(true));Status($"Registro esportato: {path}",false);}catch(Exception ex){Status($"Esportazione non riuscita: {ex.Message}",true);}}
    private static Grid GridRow()=>new(){ColumnDefinitions=new ColumnDefinitions("155,230,150,155,170,*,130")};private static void Text(Grid g,string value,int col,bool strong=false)=>Add(g,new TextBlock{Text=string.IsNullOrWhiteSpace(value)?"—":value,FontWeight=strong?FontWeight.SemiBold:FontWeight.Normal,VerticalAlignment=VerticalAlignment.Center,TextTrimming=TextTrimming.CharacterEllipsis},col);private static void Add(Grid g,Control c,int col){c.Margin=new Thickness(0,0,8,0);Grid.SetColumn(c,col);g.Children.Add(c);}
    private static Border Badge(string status){var color=status switch{"Completo" or "Completata" or "Attiva"=>UiTokens.Success,"Scaduta" or "Chiusa non validata"=>UiTokens.Danger,"In scadenza" or "Non validata"=>UiTokens.Warning,_=>UiTokens.TextSecondary};return new Border{BorderBrush=UiTokens.Brush(color),BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(8),Padding=new Thickness(6,3),Child=new TextBlock{Text=status,Foreground=UiTokens.Brush(color),HorizontalAlignment=HorizontalAlignment.Center,FontWeight=FontWeight.SemiBold}};}
    private static Control Kpi(string label,int value,string color)=>new Border{Width=205,Padding=new Thickness(14,10),Background=UiTokens.Brush(UiTokens.Surface),BorderBrush=UiTokens.Brush(UiTokens.Border),BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(12),Child=new StackPanel{Spacing=2,Children={new TextBlock{Text=value.ToString(),FontSize=23,FontWeight=FontWeight.Bold,Foreground=UiTokens.Brush(color)},new TextBlock{Text=label,Foreground=UiTokens.Brush(UiTokens.TextSecondary)}}}};
    private static Button Button(string text,Action action,bool primary=false){var b=new Button{Content=text,MinHeight=34,Background=UiTokens.Brush(primary?UiTokens.BrandBlue:UiTokens.SurfaceAlt),Foreground=primary?Brushes.White:UiTokens.Brush(UiTokens.TextPrimary)};b.Click+=(_,_)=>action();return b;}private void Status(string text,bool error){_message.Text=text;_message.Foreground=UiTokens.Brush(error?UiTokens.Danger:UiTokens.Success);}private static bool IsOverdue(SparePartRmaCase x)=>x.Status is not (SparePartRmaStatus.Closed or SparePartRmaStatus.Cancelled)&&DateTime.TryParse(x.DueDate,out var date)&&date.Date<DateTime.Today;private static DateTime Parse(string value)=>DateTime.TryParse(value,out var date)?date:DateTime.MinValue;private static string DateValue(string value)=>DateTime.TryParse(value,out var date)?date.ToString("dd/MM/yyyy HH:mm"):"—";private static string Csv(string value)=>$"\"{(value??"").Replace("\"","\"\"")}\"";private static void Open(string path){if(File.Exists(path))Process.Start(new ProcessStartInfo{FileName=path,UseShellExecute=true});}
    private sealed record AuditEvent(string Type,string Reference,string Status,string Date,string User,string Notes,string DocumentPath,int SourceId);
}
