using Avalonia;using Avalonia.Controls;using Avalonia.Layout;using Avalonia.Media;using Accyourate.App.AssetManagement.Services;using Accyourate.App.UIFramework.Tokens;
namespace Accyourate.App.AssetManagement;
public sealed class SupplierRmaCapaGovernanceGoalsWindow:Window
{
 private readonly SupplierRmaCapaGovernanceGoalService _service=new();private readonly SupplierRmaCapaGovernanceActionAnalyticsService _analytics=new();private readonly SupplierRmaCapaGovernanceActionService _actions=new();private readonly TextBox _onTime=new(),_overdue=new(),_average=new(),_low=new(),_medium=new(),_high=new(),_critical=new(),_notes=new(){AcceptsReturn=true,TextWrapping=TextWrapping.Wrap,MinHeight=75};private readonly TextBlock _result=new();private readonly StackPanel _history=new();
 public SupplierRmaCapaGovernanceGoalsWindow(){Title="Obiettivi e soglie Governance CAPA";Width=980;Height=780;WindowStartupLocation=WindowStartupLocation.CenterOwner;Content=Build();Load();}
 private Control Build(){var root=new StackPanel{Margin=new Thickness(24),Spacing=10,Children={new TextBlock{Text="Obiettivi e soglie Governance CAPA",FontSize=28,FontWeight=FontWeight.Bold},new TextBlock{Text="Definisci gli obiettivi e controlla automaticamente gli scostamenti.",Foreground=UiTokens.Brush(UiTokens.TextSecondary)}}};var grid=new Grid{ColumnDefinitions=new ColumnDefinitions("*,*"),RowDefinitions=new RowDefinitions("Auto,Auto,Auto,Auto")};Field(grid,"Puntualita minima (%)",_onTime,0,0);Field(grid,"Azioni scadute massime",_overdue,1,0);Field(grid,"Tempo medio massimo (giorni)",_average,0,1);Field(grid,"Scadenza priorita Bassa (giorni)",_low,1,1);Field(grid,"Scadenza priorita Media (giorni)",_medium,0,2);Field(grid,"Scadenza priorita Alta (giorni)",_high,1,2);Field(grid,"Scadenza priorita Critica (giorni)",_critical,0,3);root.Children.Add(grid);root.Children.Add(new TextBlock{Text="Motivazione della modifica",FontWeight=FontWeight.SemiBold});root.Children.Add(_notes);var actions=new StackPanel{Orientation=Orientation.Horizontal,Spacing=8};actions.Children.Add(SupplierRmaCorrectiveActionsWindow.Button("Salva obiettivi",Save,true));actions.Children.Add(SupplierRmaCorrectiveActionsWindow.Button("Valuta e notifica",Evaluate));root.Children.Add(actions);root.Children.Add(_result);root.Children.Add(new TextBlock{Text="Storico modifiche",FontSize=20,FontWeight=FontWeight.Bold});root.Children.Add(_history);return new ScrollViewer{Content=root};}
 private void Load(){var g=_service.Get();_onTime.Text=g.MinimumOnTimePercentage.ToString("N1");_overdue.Text=g.MaximumOverdueActions.ToString();_average.Text=g.MaximumAverageCompletionDays.ToString("N1");_low.Text=g.LowPriorityDays.ToString();_medium.Text=g.MediumPriorityDays.ToString();_high.Text=g.HighPriorityDays.ToString();_critical.Text=g.CriticalPriorityDays.ToString();LoadHistory();Evaluate();}
 private void Save(){try{var g=new SupplierRmaCapaGovernanceGoals{MinimumOnTimePercentage=Double(_onTime),MaximumOverdueActions=Int(_overdue),MaximumAverageCompletionDays=Double(_average),LowPriorityDays=Int(_low),MediumPriorityDays=Int(_medium),HighPriorityDays=Int(_high),CriticalPriorityDays=Int(_critical)};_service.Save(g,_notes.Text??"",Environment.UserName);_notes.Text="";LoadHistory();Evaluate();}catch(Exception ex){Message(ex.Message,UiTokens.Danger);}}
 private void Evaluate(){try{var analytics=_analytics.Analyze(_actions.GetAll());var e=_service.Evaluate(analytics);var published=_service.PublishAlerts(analytics);Message($"Esito: {e.OverallStatus} · puntualita {e.OnTimeStatus} · scadute {e.OverdueStatus} · tempo medio {e.AverageStatus}"+(published>0?" · notifica pubblicata":""),e.OverallStatus switch{"Conforme"=>UiTokens.Success,"Attenzione"=>UiTokens.Warning,_=>UiTokens.Danger});}catch(Exception ex){Message(ex.Message,UiTokens.Danger);}}
 private void LoadHistory(){_history.Children.Clear();var rows=_service.History();if(rows.Count==0)_history.Children.Add(new TextBlock{Text="Nessuna modifica registrata.",Foreground=UiTokens.Brush(UiTokens.TextSecondary)});foreach(var x in rows)_history.Children.Add(new Border{Padding=new Thickness(9),BorderBrush=UiTokens.Brush(UiTokens.Border),BorderThickness=new Thickness(0,0,0,1),Child=new StackPanel{Children={new TextBlock{Text=$"{Date(x.UpdatedAt)} · {x.UpdatedBy}",FontWeight=FontWeight.Bold},new TextBlock{Text=$"{x.OldValues} → {x.NewValues}",TextWrapping=TextWrapping.Wrap},new TextBlock{Text=x.Notes,TextWrapping=TextWrapping.Wrap}}}});}
 private void Message(string text,string color){_result.Text=text;_result.Foreground=UiTokens.Brush(color);_result.FontWeight=FontWeight.SemiBold;}private static double Double(TextBox x)=>double.TryParse(x.Text,out var v)?v:throw new InvalidOperationException("Inserisci valori numerici validi.");private static int Int(TextBox x)=>int.TryParse(x.Text,out var v)?v:throw new InvalidOperationException("Inserisci valori interi validi.");private static string Date(string v)=>DateTime.TryParse(v,out var d)?d.ToString("dd/MM/yyyy HH:mm"):v;private static void Field(Grid g,string label,Control c,int col,int row){var s=new StackPanel{Spacing=3,Margin=new Thickness(0,0,10,8),Children={new TextBlock{Text=label,FontWeight=FontWeight.SemiBold},c}};Grid.SetColumn(s,col);Grid.SetRow(s,row);g.Children.Add(s);}
}
