using System.Diagnostics;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Layout;
using Avalonia.Media;
using Accyourate.App.AssetManagement.Models;
using Accyourate.App.AssetManagement.Services;
using Accyourate.App.UIFramework.Tokens;

namespace Accyourate.App.AssetManagement;

public sealed class SupplierRmaComplianceWindow:Window
{
    private readonly SupplierRmaComplianceService _service=new();private readonly SparePartRmaRepository _rma=new();private readonly StackPanel _rows=new(),_kpis=new(){Orientation=Orientation.Horizontal,Spacing=10};private readonly TextBox _search=new(){Watermark="Cerca pratica, responsabile o rilievo..."};private readonly ComboBox _status=new(){ItemsSource=new[]{"Tutti gli stati","Conforme","Non conforme"},SelectedIndex=0,MinWidth=170};private readonly TextBlock _message=new();
    public SupplierRmaComplianceWindow(){Title="Evidenze e conformità RMA";Width=1280;Height=780;MinWidth=980;MinHeight=600;WindowStartupLocation=WindowStartupLocation.CenterOwner;Content=Build();_search.TextChanged+=(_,_)=>LoadData();_status.SelectionChanged+=(_,_)=>LoadData();LoadData();}
    private Control Build(){var root=new DockPanel{Margin=new Thickness(24)};var actions=new StackPanel{Orientation=Orientation.Horizontal,Spacing=8};actions.Children.Add(Button("Piano azioni",()=>new SupplierRmaCorrectiveActionsWindow().Show(this)));actions.Children.Add(Button("Configura checklist",()=>new SupplierRmaChecklistWindow(_service).Show(this)));actions.Children.Add(Button("Nuova verifica",Create,true));var head=new Grid{ColumnDefinitions=new ColumnDefinitions("*,Auto"),Margin=new Thickness(0,0,0,12)};Add(head,new StackPanel{Spacing=3,Children={new TextBlock{Text="Evidenze e conformità RMA",FontSize=28,FontWeight=FontWeight.Bold},new TextBlock{Text="Checklist, rilievi, non conformità e azioni correttive.",Foreground=UiTokens.Brush(UiTokens.TextSecondary)}}},0);Add(head,actions,1);DockPanel.SetDock(head,Dock.Top);root.Children.Add(head);_kpis.Margin=new Thickness(0,0,0,10);DockPanel.SetDock(_kpis,Dock.Top);root.Children.Add(_kpis);var filters=new Grid{ColumnDefinitions=new ColumnDefinitions("*,180"),Margin=new Thickness(0,0,0,8)};Add(filters,_search,0);Add(filters,_status,1);DockPanel.SetDock(filters,Dock.Top);root.Children.Add(filters);DockPanel.SetDock(_message,Dock.Top);root.Children.Add(_message);root.Children.Add(new ScrollViewer{Content=_rows,HorizontalScrollBarVisibility=Avalonia.Controls.Primitives.ScrollBarVisibility.Auto,VerticalScrollBarVisibility=Avalonia.Controls.Primitives.ScrollBarVisibility.Auto});return root;}
    private void LoadData(){try{var all=_service.GetAudits();var q=(_search.Text??"").Trim();var status=_status.SelectedItem?.ToString()??"Tutti gli stati";var values=all.Where(x=>status=="Tutti gli stati"||x.Status==status).Where(x=>q.Length==0||$"{x.CaseNumber} {x.Responsible} {x.Findings} {x.CorrectiveActions}".Contains(q,StringComparison.OrdinalIgnoreCase)).ToList();_kpis.Children.Clear();_kpis.Children.Add(Kpi("Verifiche",all.Count,UiTokens.BrandBlue));_kpis.Children.Add(Kpi("Conformi",all.Count(x=>x.Status=="Conforme"),UiTokens.Success));_kpis.Children.Add(Kpi("Non conformi",all.Count(x=>x.Status=="Non conforme"),all.Any(x=>x.Status=="Non conforme")?UiTokens.Danger:UiTokens.Success));_rows.Children.Clear();_rows.MinWidth=1160;_rows.Children.Add(Header());for(var i=0;i<values.Count;i++)_rows.Children.Add(Row(values[i],i));_message.Text=$"{values.Count} verifiche visualizzate";_message.Foreground=UiTokens.Brush(UiTokens.TextSecondary);}catch(Exception ex){Status($"Dati non caricati: {ex.Message}",true);}}
    private Control Header(){var g=GridRow();var labels=new[]{"Pratica","Esito","Responsabile","Data","Rilievi","Azioni correttive","Comandi"};for(var i=0;i<labels.Length;i++)Text(g,labels[i],i,true);return new Border{Background=UiTokens.Brush(UiTokens.SurfaceAlt),Padding=new Thickness(8),Child=g};}
    private Control Row(SupplierRmaComplianceAudit x,int index){var g=GridRow();Text(g,x.CaseNumber,0,true);Add(g,Badge(x.Status),1);Text(g,x.Responsible,2);Text(g,Date(x.VerifiedAt),3);Text(g,x.Findings,4);Text(g,x.CorrectiveActions,5);var actions=new StackPanel{Orientation=Orientation.Horizontal,Spacing=5};if(x.Status=="Non conforme")actions.Children.Add(Button("Crea azione",()=>CreateAction(x),true));actions.Children.Add(Button("PDF",()=>Pdf(x)));var dossier=SupplierRmaValidationService.DossierPath(x.CaseNumber);var open=Button("Fascicolo",()=>Open(dossier));open.IsEnabled=File.Exists(dossier);actions.Children.Add(open);Add(g,actions,6);return new Border{Background=UiTokens.Brush(index%2==0?UiTokens.Surface:UiTokens.SurfaceAlt),BorderBrush=UiTokens.Brush(UiTokens.Border),BorderThickness=new Thickness(0,0,0,1),Padding=new Thickness(8,6),Child=g};}
    private async void Create(){var cases=_rma.GetAll();if(cases.Count==0){Status("Nessuna pratica RMA disponibile.",true);return;}var audit=await new SupplierRmaComplianceDialog(cases,_service.GetItems()).ShowDialog<SupplierRmaComplianceAudit?>(this);if(audit is null)return;try{audit.CreatedBy=Environment.UserName;var id=_service.Save(audit);var saved=_service.GetAudits().First(x=>x.Id==id);var path=new SupplierRmaCompliancePdfService().Generate(saved);Open(path);Status("Verifica salvata e report generato.",false);LoadData();}catch(Exception ex){Status($"Verifica non salvata: {ex.Message}",true);}}
    private void Pdf(SupplierRmaComplianceAudit x){try{var path=new SupplierRmaCompliancePdfService().Generate(x);Open(path);Status($"Report creato: {path}",false);}catch(Exception ex){Status($"Report non creato: {ex.Message}",true);}}
    private async void CreateAction(SupplierRmaComplianceAudit audit){var value=await new SupplierRmaCorrectiveActionDialog(audit).ShowDialog<SupplierRmaCorrectiveAction?>(this);if(value is null)return;try{new SupplierRmaCorrectiveActionService().Create(value);Status("Azione correttiva creata e notificata.",false);}catch(Exception ex){Status($"Azione non creata: {ex.Message}",true);}}
    private static Grid GridRow()=>new(){ColumnDefinitions=new ColumnDefinitions("170,140,170,145,*,*,210")};private static void Text(Grid g,string value,int col,bool strong=false)=>Add(g,new TextBlock{Text=string.IsNullOrWhiteSpace(value)?"—":value,FontWeight=strong?FontWeight.SemiBold:FontWeight.Normal,VerticalAlignment=VerticalAlignment.Center,TextTrimming=TextTrimming.CharacterEllipsis},col);private static void Add(Grid g,Control c,int col){c.Margin=new Thickness(0,0,8,0);Grid.SetColumn(c,col);g.Children.Add(c);}
    private static Border Badge(string status){var color=status=="Conforme"?UiTokens.Success:UiTokens.Danger;return new Border{BorderBrush=UiTokens.Brush(color),BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(8),Padding=new Thickness(6,3),Child=new TextBlock{Text=status,Foreground=UiTokens.Brush(color),HorizontalAlignment=HorizontalAlignment.Center,FontWeight=FontWeight.SemiBold}};}private static Control Kpi(string label,int value,string color)=>new Border{Width=210,Padding=new Thickness(14,10),Background=UiTokens.Brush(UiTokens.Surface),BorderBrush=UiTokens.Brush(UiTokens.Border),BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(12),Child=new StackPanel{Spacing=2,Children={new TextBlock{Text=value.ToString(),FontSize=23,FontWeight=FontWeight.Bold,Foreground=UiTokens.Brush(color)},new TextBlock{Text=label,Foreground=UiTokens.Brush(UiTokens.TextSecondary)}}}};
    internal static Button Button(string text,Action action,bool primary=false){var b=new Button{Content=text,MinHeight=34,Background=UiTokens.Brush(primary?UiTokens.BrandBlue:UiTokens.SurfaceAlt),Foreground=primary?Brushes.White:UiTokens.Brush(UiTokens.TextPrimary)};b.Click+=(_,_)=>action();return b;}private void Status(string text,bool error){_message.Text=text;_message.Foreground=UiTokens.Brush(error?UiTokens.Danger:UiTokens.Success);}private static string Date(string value)=>DateTime.TryParse(value,out var d)?d.ToString("dd/MM/yyyy HH:mm"):"—";private static void Open(string path){if(File.Exists(path))Process.Start(new ProcessStartInfo{FileName=path,UseShellExecute=true});}
}

internal sealed class SupplierRmaComplianceDialog:Window
{
    private readonly IReadOnlyList<SparePartRmaCase> _cases;private readonly ComboBox _rma=new();private readonly TextBox _responsible=new(){Text=Environment.UserName},_date=new(){Text=DateTime.Today.ToString("yyyy-MM-dd")},_findings=new(){AcceptsReturn=true,TextWrapping=TextWrapping.Wrap,MinHeight=70},_actions=new(){AcceptsReturn=true,TextWrapping=TextWrapping.Wrap,MinHeight=70};private readonly List<(SupplierRmaComplianceItem Item,CheckBox Check,TextBox Notes)> _checks=new();
    public SupplierRmaComplianceDialog(IReadOnlyList<SparePartRmaCase> cases,IReadOnlyList<SupplierRmaComplianceItem> items){_cases=cases;Title="Nuova verifica conformità RMA";Width=720;Height=800;MinHeight=620;WindowStartupLocation=WindowStartupLocation.CenterOwner;_rma.ItemsSource=cases.Select(x=>$"{x.CaseNumber} · {x.Status}").ToList();_rma.SelectedIndex=0;var root=new StackPanel{Margin=new Thickness(24),Spacing=9,Children={new TextBlock{Text="Nuova verifica conformità",FontSize=24,FontWeight=FontWeight.Bold}}};Field(root,"Pratica RMA",_rma);Field(root,"Responsabile",_responsible);Field(root,"Data verifica",_date);root.Children.Add(new TextBlock{Text="Checklist delle evidenze",FontSize=17,FontWeight=FontWeight.Bold,Margin=new Thickness(0,8,0,2)});foreach(var item in items){var check=new CheckBox{Content=$"{item.Label}{(item.IsRequired?" *":"")}"};var notes=new TextBox{Watermark="Note del controllo",Margin=new Thickness(24,2,0,6)};root.Children.Add(check);root.Children.Add(notes);_checks.Add((item,check,notes));}Field(root,"Rilievi / non conformità",_findings);Field(root,"Azioni correttive",_actions);root.Children.Add(SupplierRmaComplianceWindow.Button("Salva e genera report",Save,true));Content=new ScrollViewer{Content=root};}
    private void Save(){if(_rma.SelectedIndex<0||string.IsNullOrWhiteSpace(_responsible.Text)||!DateTime.TryParse(_date.Text,out var date))return;var rma=_cases[_rma.SelectedIndex];Close(new SupplierRmaComplianceAudit{RmaId=rma.Id,CaseNumber=rma.CaseNumber,Responsible=_responsible.Text.Trim(),VerifiedAt=date.ToString("s"),Findings=_findings.Text??"",CorrectiveActions=_actions.Text??"",Checks=_checks.Select(x=>new SupplierRmaComplianceCheck{ItemId=x.Item.Id,Code=x.Item.Code,Label=x.Item.Label,IsRequired=x.Item.IsRequired,IsCompliant=x.Check.IsChecked==true,Notes=x.Notes.Text??""}).ToList()});}private static void Field(StackPanel root,string label,Control control)=>root.Children.Add(new StackPanel{Spacing=3,Children={new TextBlock{Text=label,FontWeight=FontWeight.SemiBold},control}});
}

internal sealed class SupplierRmaChecklistWindow:Window
{
    private readonly SupplierRmaComplianceService _service;private readonly StackPanel _rows=new();private readonly TextBox _label=new(){Watermark="Nuovo controllo"};private readonly CheckBox _required=new(){Content="Obbligatorio",IsChecked=true};
    public SupplierRmaChecklistWindow(SupplierRmaComplianceService service){_service=service;Title="Configurazione checklist RMA";Width=720;Height=620;WindowStartupLocation=WindowStartupLocation.CenterOwner;var root=new DockPanel{Margin=new Thickness(24)};var add=new Grid{ColumnDefinitions=new ColumnDefinitions("*,Auto,Auto"),Margin=new Thickness(0,0,0,12)};Add(add,_label,0);Add(add,_required,1);Add(add,SupplierRmaComplianceWindow.Button("Aggiungi",Create,true),2);DockPanel.SetDock(add,Dock.Top);root.Children.Add(add);root.Children.Add(new ScrollViewer{Content=_rows,VerticalScrollBarVisibility=Avalonia.Controls.Primitives.ScrollBarVisibility.Auto});Content=root;Load();}
    private void Load(){_rows.Children.Clear();foreach(var x in _service.GetItems(false)){var g=new Grid{ColumnDefinitions=new ColumnDefinitions("100,*,120,120"),Margin=new Thickness(0,0,0,5)};Add(g,new TextBlock{Text=x.Code,VerticalAlignment=VerticalAlignment.Center},0);Add(g,new TextBlock{Text=x.Label,TextWrapping=TextWrapping.Wrap,VerticalAlignment=VerticalAlignment.Center},1);Add(g,new TextBlock{Text=x.IsRequired?"Obbligatorio":"Facoltativo",VerticalAlignment=VerticalAlignment.Center},2);Add(g,SupplierRmaComplianceWindow.Button(x.IsActive?"Disattiva":"Attiva",()=>Toggle(x)),3);_rows.Children.Add(new Border{Padding=new Thickness(8),BorderBrush=UiTokens.Brush(UiTokens.Border),BorderThickness=new Thickness(0,0,0,1),Child=g});}}
    private void Create(){try{_service.AddItem(_label.Text??"",_required.IsChecked==true);_label.Text="";Load();}catch{}}private void Toggle(SupplierRmaComplianceItem x){_service.ToggleItem(x.Id,!x.IsActive);Load();}private static void Add(Grid g,Control c,int col){c.Margin=new Thickness(0,0,8,0);Grid.SetColumn(c,col);g.Children.Add(c);}
}
