using System.Diagnostics;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Layout;
using Avalonia.Media;
using Avalonia.Platform.Storage;
using Accyourate.App.AssetManagement.Models;
using Accyourate.App.AssetManagement.Services;
using Accyourate.App.UIFramework.Tokens;

namespace Accyourate.App.AssetManagement;

public sealed class SupplierRmaPortalWindow:Window
{
    private readonly int _supplierId,_initialRmaId;private readonly SupplierRmaPortalRepository _repository=new();private readonly SparePartRmaAnalyticsService _analytics=new();private readonly StackPanel _root=new();private readonly TextBlock _message=new();
    public SupplierRmaPortalWindow(int supplierId,int rmaId=0){_supplierId=supplierId;_initialRmaId=rmaId;Title="Portale operativo fornitore";Width=1220;Height=820;MinWidth=960;MinHeight=620;WindowStartupLocation=WindowStartupLocation.CenterOwner;Content=new ScrollViewer{Content=_root,VerticalScrollBarVisibility=Avalonia.Controls.Primitives.ScrollBarVisibility.Auto};_repository.PublishFollowUpReminders();Load();}
    private void Load(){_root.Children.Clear();_root.Margin=new Thickness(24);_root.Spacing=12;var supplier=_analytics.GetSupplier(_supplierId);if(supplier is null){_root.Children.Add(new TextBlock{Text="Fornitore non trovato."});return;}var contacts=_repository.GetContacts(_supplierId);var interactions=_repository.GetInteractions(_supplierId);var attachments=_repository.GetAttachments(_supplierId);var cases=_analytics.GetSupplierCases(_supplierId);var head=new Grid{ColumnDefinitions=new ColumnDefinitions("*,Auto")};Add(head,new StackPanel{Spacing=3,Children={new TextBlock{Text=$"Portale · {supplier.Name}",FontSize=28,FontWeight=FontWeight.Bold},new TextBlock{Text="Contatti, comunicazioni, solleciti e documenti RMA.",Foreground=UiTokens.Brush(UiTokens.TextSecondary)}}},0);var actions=new StackPanel{Orientation=Orientation.Horizontal,Spacing=8};actions.Children.Add(Button("Nuovo contatto",()=>NewContact()));actions.Children.Add(Button("Registra comunicazione",()=>NewInteraction(cases),true));actions.Children.Add(Button("Allega documento",()=>Attach(cases)));Add(head,actions,1);_root.Children.Add(head);var kpis=new StackPanel{Orientation=Orientation.Horizontal,Spacing=10};kpis.Children.Add(Kpi("Contatti",contacts.Count.ToString(),UiTokens.BrandBlue));kpis.Children.Add(Kpi("Comunicazioni",interactions.Count.ToString(),UiTokens.BrandBlue));kpis.Children.Add(Kpi("Solleciti aperti",interactions.Count(IsPending).ToString(),UiTokens.Warning));kpis.Children.Add(Kpi("Documenti",attachments.Count.ToString(),UiTokens.Success));_root.Children.Add(kpis);_root.Children.Add(_message);_root.Children.Add(Contacts(contacts));_root.Children.Add(Interactions(interactions,cases.ToDictionary(x=>x.Id)));_root.Children.Add(Attachments(attachments,cases.ToDictionary(x=>x.Id)));}
    private Control Contacts(IReadOnlyList<SupplierPortalContact> values){var rows=new StackPanel{Spacing=0};if(values.Count==0)rows.Children.Add(Empty("Nessun contatto aggiunto."));foreach(var x in values){var g=new Grid{ColumnDefinitions=new ColumnDefinitions("220,180,*,170,100")};Text(g,x.Name,0,true);Text(g,x.Role,1);Text(g,x.Email,2);Text(g,x.Phone,3);Text(g,x.IsPrimary?"Principale":"",4,true);rows.Children.Add(Row(g));}return Section("Contatti e referenti",rows);}
    private Control Interactions(IReadOnlyList<SupplierPortalInteraction> values,IReadOnlyDictionary<int,SparePartRmaCase> cases){var rows=new StackPanel{Spacing=0};if(values.Count==0)rows.Children.Add(Empty("Nessuna comunicazione registrata."));foreach(var x in values){cases.TryGetValue(x.RmaId,out var rma);var g=new Grid{ColumnDefinitions=new ColumnDefinitions("110,110,150,220,*,120,105")};Text(g,Date(x.CreatedAt),0);Text(g,x.Direction,1);Text(g,x.Type,2);Text(g,x.Subject,3,true);Text(g,x.Message,4);Text(g,rma?.CaseNumber??"—",5);Text(g,FollowUp(x),6,IsPending(x));rows.Children.Add(Row(g));}return Section("Cronologia comunicazioni e solleciti",rows);}
    private Control Attachments(IReadOnlyList<SupplierPortalAttachment> values,IReadOnlyDictionary<int,SparePartRmaCase> cases){var rows=new StackPanel{Spacing=0};if(values.Count==0)rows.Children.Add(Empty("Nessun documento allegato."));foreach(var x in values){cases.TryGetValue(x.RmaId,out var rma);var g=new Grid{ColumnDefinitions=new ColumnDefinitions("130,180,*,150,100")};Text(g,x.Category,0,true);Text(g,rma?.CaseNumber??"Generale",1);Text(g,x.FileName,2);Text(g,Date(x.CreatedAt),3);var open=Button("Apri",()=>Open(x.StoredPath));Add(g,open,4);rows.Children.Add(Row(g));}return Section("Documenti e allegati",rows);}
    private async void NewContact(){var result=await new SupplierContactDialog(_supplierId).ShowDialog<SupplierPortalContact?>(this);if(result is null)return;Run(()=>_repository.SaveContact(result),"Contatto registrato.");}
    private async void NewInteraction(IReadOnlyList<SparePartRmaCase> cases){var result=await new SupplierInteractionDialog(_supplierId,cases,_initialRmaId).ShowDialog<SupplierPortalInteraction?>(this);if(result is null)return;Run(()=>_repository.AddInteraction(result),"Comunicazione registrata.");}
    private async void Attach(IReadOnlyList<SparePartRmaCase> cases){var files=await StorageProvider.OpenFilePickerAsync(new FilePickerOpenOptions{Title="Seleziona documento del fornitore",AllowMultiple=false});if(files.Count==0)return;var path=files[0].TryGetLocalPath();if(string.IsNullOrWhiteSpace(path))return;var info=await new SupplierAttachmentDialog(cases,_initialRmaId).ShowDialog<(int RmaId,string Category,string Notes)?>(this);if(info is null)return;Run(()=>_repository.AttachFile(_supplierId,info.Value.RmaId,info.Value.Category,path,info.Value.Notes),"Documento archiviato.");}
    private static void Open(string path){if(!File.Exists(path))throw new FileNotFoundException("Il documento archiviato non è disponibile.",path);Process.Start(new ProcessStartInfo{FileName=path,UseShellExecute=true});}
    private void Run(Func<int> action,string success){try{action();_message.Text=success;_message.Foreground=UiTokens.Brush(UiTokens.Success);Load();}catch(Exception ex){_message.Text=ex.Message;_message.Foreground=UiTokens.Brush(UiTokens.Danger);}}
    private static bool IsPending(SupplierPortalInteraction x)=>x.Status=="Aperta"&&DateTime.TryParse(x.FollowUpDate,out var date)&&date.Date<=DateTime.Today;private static string FollowUp(SupplierPortalInteraction x)=>string.IsNullOrWhiteSpace(x.FollowUpDate)?x.Status:$"{x.Status} · {Date(x.FollowUpDate)}";private static string Date(string value)=>DateTime.TryParse(value,out var date)?date.ToString("dd/MM/yyyy"):"—";
    private static Control Row(Control child)=>new Border{Background=UiTokens.Brush(UiTokens.Surface),BorderBrush=UiTokens.Brush(UiTokens.Border),BorderThickness=new Thickness(0,0,0,1),Padding=new Thickness(8),Child=child};private static Control Empty(string text)=>new TextBlock{Text=text,Margin=new Thickness(8),Foreground=UiTokens.Brush(UiTokens.TextSecondary)};private static Control Section(string title,Control content)=>new Border{Padding=new Thickness(14),Background=UiTokens.Brush(UiTokens.Surface),BorderBrush=UiTokens.Brush(UiTokens.Border),BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(12),Child=new StackPanel{Spacing=8,Children={new TextBlock{Text=title,FontSize=17,FontWeight=FontWeight.Bold},content}}};private static Control Kpi(string label,string value,string color)=>new Border{Width=230,Padding=new Thickness(12),Background=UiTokens.Brush(UiTokens.Surface),BorderBrush=UiTokens.Brush(UiTokens.Border),BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(12),Child=new StackPanel{Children={new TextBlock{Text=value,FontSize=22,FontWeight=FontWeight.Bold,Foreground=UiTokens.Brush(color)},new TextBlock{Text=label,Foreground=UiTokens.Brush(UiTokens.TextSecondary)}}}};
    private static Button Button(string text,Action action,bool primary=false){var b=new Button{Content=text,Padding=new Thickness(10,7),Background=UiTokens.Brush(primary?UiTokens.BrandBlue:UiTokens.SurfaceAlt),Foreground=primary?Brushes.White:UiTokens.Brush(UiTokens.TextPrimary)};b.Click+=(_,_)=>action();return b;}private static void Text(Grid g,string value,int col,bool strong=false)=>Add(g,new TextBlock{Text=string.IsNullOrWhiteSpace(value)?"—":value,FontWeight=strong?FontWeight.SemiBold:FontWeight.Normal,VerticalAlignment=VerticalAlignment.Center,TextTrimming=TextTrimming.CharacterEllipsis},col);private static void Add(Grid g,Control c,int col){c.Margin=new Thickness(0,0,8,0);Grid.SetColumn(c,col);g.Children.Add(c);}
}

internal sealed class SupplierContactDialog:Window
{
    private readonly int _supplierId;private readonly TextBox _name=new(),_role=new(),_email=new(),_phone=new(),_notes=new();private readonly CheckBox _primary=new(){Content="Contatto principale"};
    public SupplierContactDialog(int supplierId){_supplierId=supplierId;Title="Nuovo contatto fornitore";Width=520;Height=560;WindowStartupLocation=WindowStartupLocation.CenterOwner;var p=Panel("Nuovo contatto");Field(p,"Nome e cognome",_name);Field(p,"Ruolo",_role);Field(p,"Email",_email);Field(p,"Telefono",_phone);Field(p,"Note",_notes);p.Children.Add(_primary);p.Children.Add(SaveButton("Salva",Save));Content=new ScrollViewer{Content=p};}private void Save(){if(string.IsNullOrWhiteSpace(_name.Text))return;Close(new SupplierPortalContact{SupplierId=_supplierId,Name=_name.Text,Role=_role.Text??"",Email=_email.Text??"",Phone=_phone.Text??"",Notes=_notes.Text??"",IsPrimary=_primary.IsChecked==true});}
    internal static StackPanel Panel(string title)=>new(){Margin=new Thickness(24),Spacing=8,Children={new TextBlock{Text=title,FontSize=24,FontWeight=FontWeight.Bold}}};internal static void Field(StackPanel p,string label,Control c)=>p.Children.Add(new StackPanel{Spacing=3,Children={new TextBlock{Text=label,FontWeight=FontWeight.SemiBold},c}});internal static Button SaveButton(string text,Action action){var b=new Button{Content=text,Height=40};b.Click+=(_,_)=>action();return b;}
}
internal sealed class SupplierInteractionDialog:Window
{
    private readonly int _supplierId;private readonly IReadOnlyList<SparePartRmaCase> _cases;private readonly ComboBox _type=new(){ItemsSource=new[]{"Email","Telefonata","Richiesta","Risposta","Sollecito"},SelectedIndex=0},_direction=new(){ItemsSource=new[]{"In uscita","In entrata"},SelectedIndex=0},_rma=new();private readonly TextBox _subject=new(),_message=new(){AcceptsReturn=true,MinHeight=90,TextWrapping=TextWrapping.Wrap},_follow=new(){Watermark="AAAA-MM-GG"};
    public SupplierInteractionDialog(int supplierId,IReadOnlyList<SparePartRmaCase> cases,int selectedRma){_supplierId=supplierId;_cases=cases;Title="Registra comunicazione";Width=560;Height=650;WindowStartupLocation=WindowStartupLocation.CenterOwner;_rma.ItemsSource=new[]{"Nessuna pratica"}.Concat(cases.Select(x=>x.CaseNumber)).ToList();_rma.SelectedIndex=selectedRma>0?Math.Max(0,cases.ToList().FindIndex(x=>x.Id==selectedRma)+1):0;var p=SupplierContactDialog.Panel("Nuova comunicazione");SupplierContactDialog.Field(p,"Tipo",_type);SupplierContactDialog.Field(p,"Direzione",_direction);SupplierContactDialog.Field(p,"Pratica RMA",_rma);SupplierContactDialog.Field(p,"Oggetto",_subject);SupplierContactDialog.Field(p,"Messaggio",_message);SupplierContactDialog.Field(p,"Data sollecito",_follow);p.Children.Add(SupplierContactDialog.SaveButton("Registra",Save));Content=new ScrollViewer{Content=p};}private void Save(){if(string.IsNullOrWhiteSpace(_subject.Text))return;var rmaId=_rma.SelectedIndex>0?_cases[_rma.SelectedIndex-1].Id:0;Close(new SupplierPortalInteraction{SupplierId=_supplierId,RmaId=rmaId,Type=_type.SelectedItem?.ToString()??"Email",Direction=_direction.SelectedItem?.ToString()??"In uscita",Subject=_subject.Text,Message=_message.Text??"",Status="Aperta",FollowUpDate=_follow.Text??"",CreatedBy=Environment.UserName});}
}
internal sealed class SupplierAttachmentDialog:Window
{
    private readonly IReadOnlyList<SparePartRmaCase> _cases;private readonly ComboBox _rma=new(),_category=new(){ItemsSource=new[]{"Autorizzazione RMA","Documento di trasporto","Risposta fornitore","Fattura / nota credito","Altro documento"},SelectedIndex=0};private readonly TextBox _notes=new();
    public SupplierAttachmentDialog(IReadOnlyList<SparePartRmaCase> cases,int selectedRma){_cases=cases;Title="Classifica documento";Width=520;Height=380;WindowStartupLocation=WindowStartupLocation.CenterOwner;_rma.ItemsSource=new[]{"Documento generale"}.Concat(cases.Select(x=>x.CaseNumber)).ToList();_rma.SelectedIndex=selectedRma>0?Math.Max(0,cases.ToList().FindIndex(x=>x.Id==selectedRma)+1):0;var p=SupplierContactDialog.Panel("Classifica allegato");SupplierContactDialog.Field(p,"Pratica RMA",_rma);SupplierContactDialog.Field(p,"Categoria",_category);SupplierContactDialog.Field(p,"Note",_notes);p.Children.Add(SupplierContactDialog.SaveButton("Archivia",Save));Content=p;}private void Save(){var rmaId=_rma.SelectedIndex>0?_cases[_rma.SelectedIndex-1].Id:0;Close((rmaId,_category.SelectedItem?.ToString()??"Documento",_notes.Text??""));}
}
