using Avalonia;using Avalonia.Controls;using Avalonia.Layout;using Avalonia.Media;using Accyourate.App.AssetManagement.Services;using Accyourate.App.UIFramework.Tokens;
namespace Accyourate.App.AssetManagement;
public sealed class SupplierRmaCapaGovernanceActionsWindow:Window
{
 private readonly SupplierRmaCapaGovernanceActionService _service=new();private readonly StackPanel _rows=new();private readonly TextBlock _summary=new();private readonly TextBox _search=new(){Watermark="Cerca titolo, responsabile, riferimento..."};private readonly ComboBox _status=new(){ItemsSource=new[]{"Tutti gli stati","Aperta","In corso","Completata","Scaduta"},SelectedIndex=0,MinWidth=170};
 public SupplierRmaCapaGovernanceActionsWindow(){Title="Piano azioni Governance CAPA";Width=1450;Height=780;WindowStartupLocation=WindowStartupLocation.CenterOwner;Content=Build();_search.TextChanged+=(_,_)=>Load();_status.SelectionChanged+=(_,_)=>Load();_service.PublishAlerts();Load();}
 private Control Build(){var root=new DockPanel{Margin=new Thickness(24)};var head=new Grid{ColumnDefinitions=new ColumnDefinitions("*,Auto"),Margin=new Thickness(0,0,0,12)};var title=new StackPanel{Children={new TextBlock{Text="Piano azioni Governance CAPA",FontSize=28,FontWeight=FontWeight.Bold},new TextBlock{Text="Responsabili, priorita, scadenze, evidenze e chiusure controllate.",Foreground=UiTokens.Brush(UiTokens.TextSecondary)}}};Add(head,title,0);var actions=new StackPanel{Orientation=Orientation.Horizontal,Spacing=8};actions.Children.Add(SupplierRmaCorrectiveActionsWindow.Button("Indicatori",()=>new SupplierRmaCapaGovernanceActionAnalyticsWindow().Show(this)));actions.Children.Add(SupplierRmaCorrectiveActionsWindow.Button("Nuova azione",()=>new SupplierRmaCapaGovernanceActionDialog(_service,Load).Show(this),true));actions.Children.Add(SupplierRmaCorrectiveActionsWindow.Button("Aggiorna e notifica",Refresh));Add(head,actions,1);DockPanel.SetDock(head,Dock.Top);root.Children.Add(head);var filters=new Grid{ColumnDefinitions=new ColumnDefinitions("*,170"),Margin=new Thickness(0,0,0,8)};Add(filters,_search,0);Add(filters,_status,1);DockPanel.SetDock(filters,Dock.Top);root.Children.Add(filters);DockPanel.SetDock(_summary,Dock.Top);root.Children.Add(_summary);root.Children.Add(new ScrollViewer{Content=_rows,HorizontalScrollBarVisibility=Avalonia.Controls.Primitives.ScrollBarVisibility.Auto});return root;}
 private void Refresh(){_service.PublishAlerts();Load();}
 private void Load(){var all=_service.GetAll();var q=(_search.Text??"").Trim();var status=_status.SelectedItem?.ToString()??"Tutti gli stati";var values=all.Where(x=>status switch{"Scaduta"=>x.IsOverdue,"Tutti gli stati"=>true,_=>x.Status==status}).Where(x=>q.Length==0||$"{x.Title} {x.Owner} {x.SourceType} {x.SourceReference} {x.Priority}".Contains(q,StringComparison.OrdinalIgnoreCase)).ToList();_rows.Children.Clear();_rows.MinWidth=1320;_rows.Children.Add(Row(new(){Title="Azione",SourceType="Origine",Owner="Responsabile",Priority="Priorita",Status="Stato",DueDate="Scadenza"},true));foreach(var x in values)_rows.Children.Add(Row(x,false));_summary.Text=$"{values.Count} azioni · {all.Count(x=>x.Status=="Aperta")} aperte · {all.Count(x=>x.Status=="In corso")} in corso · {all.Count(x=>x.IsOverdue)} scadute";_summary.Foreground=UiTokens.Brush(all.Any(x=>x.IsOverdue)?UiTokens.Danger:UiTokens.TextSecondary);_summary.Margin=new Thickness(0,0,0,8);}
 private Control Row(SupplierRmaCapaGovernanceAction x,bool header){var grid=new Grid{ColumnDefinitions=new ColumnDefinitions("260,150,140,150,100,110,130,330")};Cell(grid,x.Title,0,header);Cell(grid,header?x.SourceType:$"{x.SourceType} {x.SourceReference}",1,header);Cell(grid,x.Owner,2,header);Cell(grid,x.Priority,3,header);Cell(grid,header?x.DueDate:Date(x.DueDate),4,header||x.IsOverdue);Cell(grid,header?x.Status:x.IsOverdue?"Scaduta":x.Status,5,true);Cell(grid,header?"Evidenze":x.Evidence,6,header);if(!header){var a=new StackPanel{Orientation=Orientation.Horizontal,Spacing=5};var start=SupplierRmaCorrectiveActionsWindow.Button("Avvia",()=>Run(()=>_service.Start(x.Id,Environment.UserName)));start.IsEnabled=x.Status=="Aperta";a.Children.Add(start);var close=SupplierRmaCorrectiveActionsWindow.Button("Chiudi",()=>new SupplierRmaCapaGovernanceActionCloseDialog(x,_service,Load).Show(this),true);close.IsEnabled=x.Status!="Completata";a.Children.Add(close);a.Children.Add(SupplierRmaCorrectiveActionsWindow.Button("Storico",()=>new SupplierRmaCapaGovernanceActionHistoryWindow(x,_service).Show(this)));Add(grid,a,7);}else Cell(grid,"Comandi",7,true);return new Border{Padding=new Thickness(9),Background=UiTokens.Brush(header?UiTokens.SurfaceAlt:UiTokens.Surface),BorderBrush=UiTokens.Brush(UiTokens.Border),BorderThickness=new Thickness(0,0,0,1),Child=grid};}
 private void Run(Action action){try{action();Load();}catch(Exception ex){_summary.Text=ex.Message;_summary.Foreground=UiTokens.Brush(UiTokens.Danger);}}private static string Date(string v)=>DateTime.TryParse(v,out var d)?d.ToString("dd/MM/yyyy"):v;private static void Cell(Grid g,string t,int c,bool bold=false)=>Add(g,new TextBlock{Text=string.IsNullOrWhiteSpace(t)?"—":t,FontWeight=bold?FontWeight.Bold:FontWeight.Normal,TextTrimming=TextTrimming.CharacterEllipsis},c);private static void Add(Grid g,Control x,int c){x.Margin=new Thickness(0,0,8,0);Grid.SetColumn(x,c);g.Children.Add(x);}
}
internal sealed class SupplierRmaCapaGovernanceActionDialog:Window
{
 private readonly SupplierRmaCapaGovernanceActionService _service;private readonly Action _saved;private readonly ComboBox _source=new(){ItemsSource=new[]{"Fascicolo","Attestazione","Esportazione","Riesame","Governance"},SelectedIndex=0},_priority=new(){ItemsSource=new[]{"Bassa","Media","Alta","Critica"},SelectedIndex=1};private readonly TextBox _reference=new(),_title=new(),_description=new(){AcceptsReturn=true,TextWrapping=TextWrapping.Wrap,MinHeight=90},_owner=new(){Text=Environment.UserName},_due=new(){Text=DateTime.Today.AddDays(14).ToString("yyyy-MM-dd")};private readonly TextBlock _message=new();
 public SupplierRmaCapaGovernanceActionDialog(SupplierRmaCapaGovernanceActionService service,Action saved){_service=service;_saved=saved;Title="Nuova azione Governance CAPA";Width=650;Height=680;WindowStartupLocation=WindowStartupLocation.CenterOwner;var root=new StackPanel{Margin=new Thickness(24),Spacing=8,Children={new TextBlock{Text="Nuova azione Governance CAPA",FontSize=26,FontWeight=FontWeight.Bold}}};Field(root,"Origine",_source);Field(root,"Riferimento (numero pratica, attestazione o esportazione)",_reference);Field(root,"Titolo",_title);Field(root,"Descrizione",_description);Field(root,"Responsabile",_owner);Field(root,"Priorita",_priority);Field(root,"Scadenza (AAAA-MM-GG)",_due);root.Children.Add(_message);root.Children.Add(SupplierRmaCorrectiveActionsWindow.Button("Crea azione",Save,true));Content=new ScrollViewer{Content=root};}
 private void Save(){try{_service.Create(_source.SelectedItem?.ToString()??"Governance",_reference.Text??"",_title.Text??"",_description.Text??"",_owner.Text??"",_priority.SelectedItem?.ToString()??"Media",_due.Text??"",Environment.UserName);_saved();Close();}catch(Exception ex){_message.Text=ex.Message;_message.Foreground=UiTokens.Brush(UiTokens.Danger);}}private static void Field(StackPanel root,string label,Control control)=>root.Children.Add(new StackPanel{Spacing=3,Children={new TextBlock{Text=label,FontWeight=FontWeight.SemiBold},control}});
}
internal sealed class SupplierRmaCapaGovernanceActionCloseDialog:Window
{
 private readonly SupplierRmaCapaGovernanceAction _item;private readonly SupplierRmaCapaGovernanceActionService _service;private readonly Action _saved;private readonly TextBox _evidence=new(){AcceptsReturn=true,TextWrapping=TextWrapping.Wrap,MinHeight=160};private readonly TextBlock _message=new();public SupplierRmaCapaGovernanceActionCloseDialog(SupplierRmaCapaGovernanceAction item,SupplierRmaCapaGovernanceActionService service,Action saved){_item=item;_service=service;_saved=saved;Title="Chiusura controllata azione";Width=620;Height=430;WindowStartupLocation=WindowStartupLocation.CenterOwner;var root=new StackPanel{Margin=new Thickness(24),Spacing=8,Children={new TextBlock{Text="Chiusura controllata",FontSize=26,FontWeight=FontWeight.Bold},new TextBlock{Text=item.Title,TextWrapping=TextWrapping.Wrap},new TextBlock{Text="Evidenze di completamento",FontWeight=FontWeight.SemiBold},_evidence,_message}};root.Children.Add(SupplierRmaCorrectiveActionsWindow.Button("Registra chiusura",CloseAction,true));Content=root;}private void CloseAction(){try{_service.Complete(_item.Id,_evidence.Text??"",Environment.UserName);_saved();Close();}catch(Exception ex){_message.Text=ex.Message;_message.Foreground=UiTokens.Brush(UiTokens.Danger);}}
}
internal sealed class SupplierRmaCapaGovernanceActionHistoryWindow:Window
{
 public SupplierRmaCapaGovernanceActionHistoryWindow(SupplierRmaCapaGovernanceAction item,SupplierRmaCapaGovernanceActionService service){Title="Storico azione Governance CAPA";Width=850;Height=600;WindowStartupLocation=WindowStartupLocation.CenterOwner;var root=new StackPanel{Margin=new Thickness(24),Spacing=8,Children={new TextBlock{Text="Storico azione",FontSize=26,FontWeight=FontWeight.Bold},new TextBlock{Text=item.Title,TextWrapping=TextWrapping.Wrap}}};foreach(var x in service.History(item.Id))root.Children.Add(new Border{Padding=new Thickness(10),BorderBrush=UiTokens.Brush(UiTokens.Border),BorderThickness=new Thickness(0,0,0,1),Child=new StackPanel{Children={new TextBlock{Text=$"{x.EventType} · {Date(x.CreatedAt)}",FontWeight=FontWeight.Bold},new TextBlock{Text=x.Detail,TextWrapping=TextWrapping.Wrap},new TextBlock{Text=$"Operatore: {x.CreatedBy}",Foreground=UiTokens.Brush(UiTokens.TextSecondary)}}}});Content=new ScrollViewer{Content=root};}private static string Date(string v)=>DateTime.TryParse(v,out var d)?d.ToString("dd/MM/yyyy HH:mm"):v;
}
