using System.Diagnostics;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Layout;
using Avalonia.Media;
using Accyourate.App.AssetManagement.Services;
using Accyourate.App.UIFramework.Tokens;

namespace Accyourate.App.AssetManagement;

public sealed class SupplierRmaAuditScheduleWindow : Window
{
    private readonly SupplierRmaAuditScheduleService _service=new();
    private readonly StackPanel _schedules=new(),_runs=new();private readonly TextBlock _message=new();
    public SupplierRmaAuditScheduleWindow(){Title="Pianificazione audit RMA";Width=1180;Height=780;MinWidth=920;MinHeight=600;WindowStartupLocation=WindowStartupLocation.CenterOwner;Content=Build();_service.PublishDueNotifications();LoadData();}
    private Control Build(){var root=new DockPanel{Margin=new Thickness(24)};var actions=new StackPanel{Orientation=Orientation.Horizontal,Spacing=8};actions.Children.Add(Button("Nuova pianificazione",Create,true));actions.Children.Add(Button("Aggiorna",LoadData));var head=new Grid{ColumnDefinitions=new ColumnDefinitions("*,Auto"),Margin=new Thickness(0,0,0,14)};Add(head,new StackPanel{Spacing=3,Children={new TextBlock{Text="Pianificazione audit RMA",FontSize=28,FontWeight=FontWeight.Bold},new TextBlock{Text="Report periodici, prossime scadenze e storico delle esecuzioni.",Foreground=UiTokens.Brush(UiTokens.TextSecondary)}}},0);Add(head,actions,1);DockPanel.SetDock(head,Dock.Top);root.Children.Add(head);DockPanel.SetDock(_message,Dock.Top);root.Children.Add(_message);var content=new Grid{RowDefinitions=new RowDefinitions("Auto,*")};var planned=Section("Pianificazioni",new ScrollViewer{Content=_schedules,HorizontalScrollBarVisibility=Avalonia.Controls.Primitives.ScrollBarVisibility.Auto});Grid.SetRow(planned,0);content.Children.Add(planned);var history=Section("Storico esecuzioni",new ScrollViewer{Content=_runs,HorizontalScrollBarVisibility=Avalonia.Controls.Primitives.ScrollBarVisibility.Auto,VerticalScrollBarVisibility=Avalonia.Controls.Primitives.ScrollBarVisibility.Auto});history.Margin=new Thickness(0,12,0,0);Grid.SetRow(history,1);content.Children.Add(history);root.Children.Add(content);return root;}
    private void LoadData(){try{var schedules=_service.GetSchedules();_schedules.Children.Clear();_schedules.MinWidth=1050;_schedules.Children.Add(ScheduleHeader());for(var i=0;i<schedules.Count;i++)_schedules.Children.Add(ScheduleRow(schedules[i],i));var runs=_service.GetRuns();_runs.Children.Clear();_runs.MinWidth=1050;_runs.Children.Add(RunHeader());for(var i=0;i<runs.Count;i++)_runs.Children.Add(RunRow(runs[i],i));_message.Text=$"{schedules.Count(x=>x.IsActive)} pianificazioni attive · {schedules.Count(x=>x.DisplayStatus=="Scaduta")} scadute · {runs.Count} esecuzioni archiviate";_message.Foreground=UiTokens.Brush(UiTokens.TextSecondary);}catch(Exception ex){Status($"Dati non caricati: {ex.Message}",true);}}
    private Control ScheduleHeader(){var g=ScheduleGrid();var labels=new[]{"Nome","Frequenza","Prossima esecuzione","Ultima esecuzione","Stato","Azioni"};for(var i=0;i<labels.Length;i++)Text(g,labels[i],i,true);return Header(g);}
    private Control ScheduleRow(SupplierRmaAuditSchedule x,int index){var g=ScheduleGrid();Text(g,x.Name,0,true);Text(g,x.Frequency,1);Text(g,Date(x.NextRun),2);Text(g,DateTimeValue(x.LastRunAt),3);Add(g,Badge(x.DisplayStatus),4);var actions=new StackPanel{Orientation=Orientation.Horizontal,Spacing=5};actions.Children.Add(Button("Esegui ora",()=>Run(x),true));actions.Children.Add(Button(x.IsActive?"Disattiva":"Attiva",()=>Toggle(x)));Add(g,actions,5);return Row(g,index);}
    private Control RunHeader(){var g=RunGrid();var labels=new[]{"Pianificazione","Prevista","Eseguita","Stato","Operatore","PDF"};for(var i=0;i<labels.Length;i++)Text(g,labels[i],i,true);return Header(g);}
    private Control RunRow(SupplierRmaAuditRun x,int index){var g=RunGrid();Text(g,x.ScheduleName,0,true);Text(g,Date(x.ScheduledFor),1);Text(g,DateTimeValue(x.ExecutedAt),2);Add(g,Badge(x.Status),3);Text(g,x.ExecutedBy,4);var open=Button(File.Exists(x.PdfPath)?"Apri":"Non disponibile",()=>Open(x.PdfPath));open.IsEnabled=File.Exists(x.PdfPath);Add(g,open,5);return Row(g,index);}
    private async void Create(){var value=await new SupplierRmaAuditScheduleDialog().ShowDialog<SupplierRmaAuditSchedule?>(this);if(value is null)return;try{_service.Save(value);var notifications=_service.PublishDueNotifications();Status(notifications>0?"Pianificazione creata e notifica audit pubblicata.":"Pianificazione creata.",false);LoadData();}catch(Exception ex){Status(ex.Message,true);}}
    private void Run(SupplierRmaAuditSchedule value){try{var path=_service.Run(value,Environment.UserName);Open(path);Status("Report pianificato generato e archiviato.",false);LoadData();}catch(Exception ex){Status($"Esecuzione non riuscita: {ex.Message}",true);}}
    private void Toggle(SupplierRmaAuditSchedule value){try{_service.Toggle(value.Id,!value.IsActive);Status(value.IsActive?"Pianificazione disattivata.":"Pianificazione attivata.",false);LoadData();}catch(Exception ex){Status(ex.Message,true);}}
    private static Control Section(string title,Control content){var panel=new DockPanel();var heading=new TextBlock{Text=title,FontSize=18,FontWeight=FontWeight.Bold,Margin=new Thickness(0,0,0,9)};DockPanel.SetDock(heading,Dock.Top);panel.Children.Add(heading);panel.Children.Add(content);return new Border{Padding=new Thickness(14),Background=UiTokens.Brush(UiTokens.Surface),BorderBrush=UiTokens.Brush(UiTokens.Border),BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(12),Child=panel};}
    private static Grid ScheduleGrid()=>new(){ColumnDefinitions=new ColumnDefinitions("260,130,160,160,130,300")};private static Grid RunGrid()=>new(){ColumnDefinitions=new ColumnDefinitions("260,150,170,130,180,150")};
    private static Control Header(Grid g)=>new Border{Background=UiTokens.Brush(UiTokens.SurfaceAlt),Padding=new Thickness(8),Child=g};private static Control Row(Grid g,int i)=>new Border{Background=UiTokens.Brush(i%2==0?UiTokens.Surface:UiTokens.SurfaceAlt),BorderBrush=UiTokens.Brush(UiTokens.Border),BorderThickness=new Thickness(0,0,0,1),Padding=new Thickness(8,6),Child=g};
    private static Border Badge(string status){var color=status switch{"Completata" or "Attiva"=>UiTokens.Success,"Scaduta"=>UiTokens.Danger,"In scadenza"=>UiTokens.Warning,_=>UiTokens.TextSecondary};return new Border{BorderBrush=UiTokens.Brush(color),BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(8),Padding=new Thickness(6,3),Child=new TextBlock{Text=status,Foreground=UiTokens.Brush(color),HorizontalAlignment=HorizontalAlignment.Center,FontWeight=FontWeight.SemiBold}};}
    private static void Text(Grid g,string text,int col,bool strong=false)=>Add(g,new TextBlock{Text=string.IsNullOrWhiteSpace(text)?"—":text,FontWeight=strong?FontWeight.SemiBold:FontWeight.Normal,VerticalAlignment=VerticalAlignment.Center,TextTrimming=TextTrimming.CharacterEllipsis},col);private static void Add(Grid g,Control c,int col){c.Margin=new Thickness(0,0,8,0);Grid.SetColumn(c,col);g.Children.Add(c);}
    private static Button Button(string text,Action action,bool primary=false){var b=new Button{Content=text,MinHeight=34,Background=UiTokens.Brush(primary?UiTokens.BrandBlue:UiTokens.SurfaceAlt),Foreground=primary?Brushes.White:UiTokens.Brush(UiTokens.TextPrimary)};b.Click+=(_,_)=>action();return b;}
    private void Status(string text,bool error){_message.Text=text;_message.Foreground=UiTokens.Brush(error?UiTokens.Danger:UiTokens.Success);}private static string Date(string value)=>DateTime.TryParse(value,out var d)?d.ToString("dd/MM/yyyy"):"—";private static string DateTimeValue(string value)=>DateTime.TryParse(value,out var d)?d.ToString("dd/MM/yyyy HH:mm"):"—";private static void Open(string path){if(File.Exists(path))Process.Start(new ProcessStartInfo{FileName=path,UseShellExecute=true});}
}

internal sealed class SupplierRmaAuditScheduleDialog:Window
{
    private readonly TextBox _name=new(){Text="Audit RMA periodico"},_date=new(){Text=DateTime.Today.AddMonths(1).ToString("yyyy-MM-dd")};private readonly ComboBox _frequency=new(){ItemsSource=new[]{"Mensile","Trimestrale","Annuale"},SelectedIndex=0};private readonly CheckBox _active=new(){Content="Pianificazione attiva",IsChecked=true};
    public SupplierRmaAuditScheduleDialog(){Title="Nuova pianificazione audit RMA";Width=520;Height=430;WindowStartupLocation=WindowStartupLocation.CenterOwner;var root=new StackPanel{Margin=new Thickness(24),Spacing=10,Children={new TextBlock{Text="Nuova pianificazione",FontSize=24,FontWeight=FontWeight.Bold}}};Field(root,"Nome",_name);Field(root,"Frequenza",_frequency);Field(root,"Prima esecuzione (AAAA-MM-GG)",_date);root.Children.Add(_active);var save=new Button{Content="Salva pianificazione",Height=40};save.Click+=(_,_)=>Save();root.Children.Add(save);Content=root;}
    private void Save(){if(string.IsNullOrWhiteSpace(_name.Text)||!DateTime.TryParse(_date.Text,out var date))return;Close(new SupplierRmaAuditSchedule{Name=_name.Text.Trim(),Frequency=_frequency.SelectedItem?.ToString()??"Mensile",NextRun=date.ToString("yyyy-MM-dd"),IsActive=_active.IsChecked==true});}private static void Field(StackPanel root,string label,Control control)=>root.Children.Add(new StackPanel{Spacing=3,Children={new TextBlock{Text=label,FontWeight=FontWeight.SemiBold},control}});
}
