using Accyourate.App.AssetManagement.Models;
using Microsoft.Data.Sqlite;

namespace Accyourate.App.AssetManagement.Services;

public sealed class SparePartRmaRepository
{
    private readonly string _connectionString;
    public SparePartRmaRepository(string? databasePath=null){var folder=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),"AccyourateEnterpriseX");Directory.CreateDirectory(folder);_connectionString=$"Data Source={databasePath??Path.Combine(folder,"accyourate-assets.db")}";using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="""
        CREATE TABLE IF NOT EXISTS SparePartRmaCases(
        Id INTEGER PRIMARY KEY AUTOINCREMENT,CaseNumber TEXT NOT NULL UNIQUE,QuarantineId INTEGER NOT NULL UNIQUE,
        InventoryItemId INTEGER NOT NULL,SupplierId INTEGER NOT NULL DEFAULT 0,Quantity REAL NOT NULL,AuthorizationNumber TEXT,
        Status TEXT NOT NULL,Courier TEXT,TrackingNumber TEXT,ShippedAt TEXT,DueDate TEXT,Outcome TEXT,
        ShippingCost REAL NOT NULL DEFAULT 0,ResolutionCost REAL NOT NULL DEFAULT 0,Notes TEXT,CreatedAt TEXT NOT NULL,UpdatedAt TEXT NOT NULL,ClosedAt TEXT);
        """;cmd.ExecuteNonQuery();}
    public int Create(int quarantineId,int itemId,decimal quantity,int supplierId,string notes){using var c=Open();using var check=c.CreateCommand();check.CommandText="SELECT COUNT(*) FROM SparePartRmaCases WHERE QuarantineId=$q;";check.Parameters.AddWithValue("$q",quarantineId);if(Convert.ToInt32(check.ExecuteScalar())>0)throw new InvalidOperationException("Esiste già una pratica RMA per questo caso.");var number=$"RMA-{DateTime.Today:yyyy}-{NextId(c):D6}";var now=DateTime.Now.ToString("s");using var cmd=c.CreateCommand();cmd.CommandText="INSERT INTO SparePartRmaCases(CaseNumber,QuarantineId,InventoryItemId,SupplierId,Quantity,AuthorizationNumber,Status,Courier,TrackingNumber,ShippedAt,DueDate,Outcome,ShippingCost,ResolutionCost,Notes,CreatedAt,UpdatedAt,ClosedAt) VALUES($number,$q,$item,$supplier,$qty,'',$status,'','','','','',0,0,$notes,$now,$now,'');SELECT last_insert_rowid();";cmd.Parameters.AddWithValue("$number",number);cmd.Parameters.AddWithValue("$q",quarantineId);cmd.Parameters.AddWithValue("$item",itemId);cmd.Parameters.AddWithValue("$supplier",supplierId);cmd.Parameters.AddWithValue("$qty",quantity);cmd.Parameters.AddWithValue("$status",SparePartRmaStatus.Open);cmd.Parameters.AddWithValue("$notes",notes);cmd.Parameters.AddWithValue("$now",now);return Convert.ToInt32(cmd.ExecuteScalar());}
    public IReadOnlyList<SparePartRmaCase> GetAll(){using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText=Select+" ORDER BY CreatedAt DESC,Id DESC;";using var r=cmd.ExecuteReader();var list=new List<SparePartRmaCase>();while(r.Read())list.Add(Read(r));return list;}
    public void Authorize(int id,int supplierId,string authorization,string dueDate,string notes){Change(id,SparePartRmaStatus.Open,SparePartRmaStatus.Authorized,(c,t,x)=>{Exec(c,t,"UPDATE SparePartRmaCases SET SupplierId=$supplier,AuthorizationNumber=$auth,DueDate=$due,Notes=$notes WHERE Id=$id;",("$supplier",supplierId),("$auth",authorization),("$due",dueDate),("$notes",notes),("$id",id));});}
    public void Ship(int id,string courier,string tracking,decimal cost){Change(id,SparePartRmaStatus.Authorized,SparePartRmaStatus.Shipped,(c,t,x)=>Exec(c,t,"UPDATE SparePartRmaCases SET Courier=$courier,TrackingNumber=$tracking,ShippingCost=$cost,ShippedAt=$date WHERE Id=$id;",("$courier",courier),("$tracking",tracking),("$cost",Math.Max(0,cost)),("$date",DateTime.Now.ToString("s")),("$id",id)));}
    public void Resolve(int id,string outcome,decimal cost,string notes){Change(id,SparePartRmaStatus.Shipped,SparePartRmaStatus.Resolved,(c,t,x)=>Exec(c,t,"UPDATE SparePartRmaCases SET Outcome=$outcome,ResolutionCost=$cost,Notes=$notes WHERE Id=$id;",("$outcome",outcome),("$cost",Math.Max(0,cost)),("$notes",notes),("$id",id)));}
    public void Close(int id,int locationId,string notes,string user)
    {
        using var c=Open();using var t=c.BeginTransaction();var x=Get(c,t,id);if(x.Status!=SparePartRmaStatus.Resolved)throw new InvalidOperationException("La pratica deve essere risolta.");
        if(x.Outcome is SparePartRmaOutcome.Repair or SparePartRmaOutcome.Replacement){if(locationId<=0)throw new InvalidOperationException("Seleziona l'ubicazione di ricezione.");using var item=c.CreateCommand();item.Transaction=t;item.CommandText="SELECT Quantity,AverageUnitCost FROM SparePartsInventory WHERE Id=$id;";item.Parameters.AddWithValue("$id",x.InventoryItemId);using var r=item.ExecuteReader();if(!r.Read())throw new InvalidOperationException("Ricambio non trovato.");var before=Convert.ToDecimal(r.GetDouble(0));var cost=Convert.ToDecimal(r.GetDouble(1));r.Close();Exec(c,t,"UPDATE SparePartsInventory SET Quantity=$quantity,UpdatedAt=$date WHERE Id=$item;",("$quantity",before+x.Quantity),("$date",DateTime.Now.ToString("s")),("$item",x.InventoryItemId));Exec(c,t,"INSERT INTO SparePartLocationBalances(InventoryItemId,LocationId,Quantity) VALUES($item,$location,$quantity) ON CONFLICT(InventoryItemId,LocationId) DO UPDATE SET Quantity=Quantity+$quantity;",("$item",x.InventoryItemId),("$location",locationId),("$quantity",x.Quantity));Exec(c,t,"INSERT INTO SparePartsInventoryMovements(InventoryItemId,MovementType,Quantity,UnitCost,Reference,Notes,CreatedAt,BalanceBefore,BalanceAfter) VALUES($item,'Carico - Rientro RMA',$quantity,$cost,$reference,$notes,$date,$before,$after);",("$item",x.InventoryItemId),("$quantity",x.Quantity),("$cost",cost),("$reference",x.CaseNumber),("$notes",notes),("$date",DateTime.Now.ToString("s")),("$before",before),("$after",before+x.Quantity));}
        var now=DateTime.Now.ToString("s");Exec(c,t,"UPDATE SparePartRmaCases SET Status=$status,Notes=$notes,UpdatedAt=$now,ClosedAt=$now WHERE Id=$id;",("$status",SparePartRmaStatus.Closed),("$notes",notes),("$now",now),("$id",id));Exec(c,t,"UPDATE SparePartQuarantine SET Status=$status,AuthorizedBy=$user,UpdatedAt=$now,ClosedAt=$now WHERE Id=$id;",("$status",SparePartQuarantineStatus.ReturnedToSupplier),("$user",user),("$now",now),("$id",x.QuarantineId));t.Commit();
    }
    public void Cancel(int id){Change(id,SparePartRmaStatus.Open,SparePartRmaStatus.Cancelled,null);}
    private void Change(int id,string expected,string status,Action<SqliteConnection,SqliteTransaction,SparePartRmaCase>? extra){using var c=Open();using var t=c.BeginTransaction();var x=Get(c,t,id);if(x.Status!=expected)throw new InvalidOperationException($"Operazione consentita solo nello stato {expected}.");extra?.Invoke(c,t,x);Exec(c,t,"UPDATE SparePartRmaCases SET Status=$status,UpdatedAt=$date WHERE Id=$id;",("$status",status),("$date",DateTime.Now.ToString("s")),("$id",id));t.Commit();}
    private static SparePartRmaCase Get(SqliteConnection c,SqliteTransaction t,int id){using var cmd=c.CreateCommand();cmd.Transaction=t;cmd.CommandText=Select+" WHERE Id=$id;";cmd.Parameters.AddWithValue("$id",id);using var r=cmd.ExecuteReader();return r.Read()?Read(r):throw new InvalidOperationException("Pratica RMA non trovata.");}
    private static int NextId(SqliteConnection c){using var cmd=c.CreateCommand();cmd.CommandText="SELECT COALESCE(MAX(Id),0)+1 FROM SparePartRmaCases;";return Convert.ToInt32(cmd.ExecuteScalar());}
    private static void Exec(SqliteConnection c,SqliteTransaction t,string sql,params (string,object)[] values){using var cmd=c.CreateCommand();cmd.Transaction=t;cmd.CommandText=sql;foreach(var v in values)cmd.Parameters.AddWithValue(v.Item1,v.Item2);cmd.ExecuteNonQuery();}
    private SqliteConnection Open(){var c=new SqliteConnection(_connectionString);c.Open();return c;}
    private static SparePartRmaCase Read(SqliteDataReader r)=>new(){Id=r.GetInt32(0),CaseNumber=S(r,1),QuarantineId=r.GetInt32(2),InventoryItemId=r.GetInt32(3),SupplierId=r.GetInt32(4),Quantity=D(r,5),AuthorizationNumber=S(r,6),Status=S(r,7),Courier=S(r,8),TrackingNumber=S(r,9),ShippedAt=S(r,10),DueDate=S(r,11),Outcome=S(r,12),ShippingCost=D(r,13),ResolutionCost=D(r,14),Notes=S(r,15),CreatedAt=S(r,16),UpdatedAt=S(r,17),ClosedAt=S(r,18)};private static string S(SqliteDataReader r,int i)=>r.IsDBNull(i)?"":r.GetString(i);private static decimal D(SqliteDataReader r,int i)=>r.IsDBNull(i)?0:Convert.ToDecimal(r.GetDouble(i));
    private const string Select="SELECT Id,CaseNumber,QuarantineId,InventoryItemId,SupplierId,Quantity,AuthorizationNumber,Status,Courier,TrackingNumber,ShippedAt,DueDate,Outcome,ShippingCost,ResolutionCost,Notes,CreatedAt,UpdatedAt,ClosedAt FROM SparePartRmaCases";
}
