using System.Text;using Accyourate.App.Platform.Pdf;using Accyourate.App.Platform.Settings;
namespace Accyourate.App.AssetManagement.Services;
public sealed class SupplierRmaCapaGovernanceActionAnalytics{public int Total{get;init;}public int Open{get;init;}public int InProgress{get;init;}public int Completed{get;init;}public int Overdue{get;init;}public double AverageCompletionDays{get;init;}public double OnTimePercentage{get;init;}public IReadOnlyDictionary<string,int> ByPriority{get;init;}=new Dictionary<string,int>();public IReadOnlyDictionary<string,int> ByOwner{get;init;}=new Dictionary<string,int>();}
public sealed class SupplierRmaCapaGovernanceActionAnalyticsService
{
 private readonly SettingsService _settings=new();
 public SupplierRmaCapaGovernanceActionAnalytics Analyze(IReadOnlyList<SupplierRmaCapaGovernanceAction> rows){var completed=rows.Where(x=>x.Status=="Completata").ToList();var durations=completed.Select(x=>(CreatedClosed(x).closed-CreatedClosed(x).created).TotalDays).Where(x=>x>=0).ToList();var onTime=completed.Count(x=>DateTime.TryParse(x.ClosedAt,out var closed)&&DateTime.TryParse(x.DueDate,out var due)&&closed.Date<=due.Date);return new(){Total=rows.Count,Open=rows.Count(x=>x.Status=="Aperta"),InProgress=rows.Count(x=>x.Status=="In corso"),Completed=completed.Count,Overdue=rows.Count(x=>x.IsOverdue),AverageCompletionDays=durations.Count==0?0:durations.Average(),OnTimePercentage=completed.Count==0?0:onTime*100d/completed.Count,ByPriority=rows.GroupBy(x=>x.Priority).OrderByDescending(x=>x.Count()).ToDictionary(x=>x.Key,x=>x.Count()),ByOwner=rows.GroupBy(x=>string.IsNullOrWhiteSpace(x.Owner)?"Non assegnato":x.Owner).OrderByDescending(x=>x.Count()).ToDictionary(x=>x.Key,x=>x.Count())};}
 public string ExportCsv(IReadOnlyList<SupplierRmaCapaGovernanceAction> rows,string filters){var folder=Folder();var path=Path.Combine(folder,$"Piano-azioni-CAPA-{DateTime.Now:yyyyMMdd-HHmmss}.csv");var b=new StringBuilder("Id;Origine;Riferimento;Titolo;Responsabile;Priorita;Stato;Scadenza;Creazione;Chiusura;Evidenze\r\n");foreach(var x in rows)b.AppendLine(string.Join(";",new[]{Csv(x.Id.ToString()),Csv(x.SourceType),Csv(x.SourceReference),Csv(x.Title),Csv(x.Owner),Csv(x.Priority),Csv(x.Status),Csv(x.DueDate),Csv(x.CreatedAt),Csv(x.ClosedAt),Csv(x.Evidence)}));File.WriteAllText(path,b.ToString(),new UTF8Encoding(true));return path;}
 public string ExportPdf(IReadOnlyList<SupplierRmaCapaGovernanceAction> rows,string filters){var a=Analyze(rows);var goalService=new SupplierRmaCapaGovernanceGoalService();var evaluation=goalService.Evaluate(a);var goals=goalService.Get();var s=_settings.Load();var t=s.DocumentTemplate??new DocumentTemplateSettings();var d=new SimplePdfDocument{Title="Indicatori Piano azioni CAPA"};Brand(d,s,t,$"CAPA-ACT-{DateTime.Now:yyyyMMdd-HHmm}");d.AddTitle("Indicatori Piano azioni Governance CAPA");d.AddKeyValue("Data elaborazione",DateTime.Now.ToString("dd/MM/yyyy HH:mm"));d.AddKeyValue("Operatore",Environment.UserName);d.AddKeyValue("Filtri",filters);d.AddHeading("Esito obiettivi e soglie");d.AddStatus("Esito complessivo",evaluation.OverallStatus);d.AddKeyValue("Puntualita",$"{a.OnTimePercentage:N1}% (obiettivo almeno {goals.MinimumOnTimePercentage:N1}%) - {evaluation.OnTimeStatus}");d.AddKeyValue("Azioni scadute",$"{a.Overdue} (massimo {goals.MaximumOverdueActions}) - {evaluation.OverdueStatus}");d.AddKeyValue("Tempo medio",$"{a.AverageCompletionDays:N1} giorni (massimo {goals.MaximumAverageCompletionDays:N1}) - {evaluation.AverageStatus}");d.AddHeading("Indicatori");d.AddKeyValue("Azioni totali",a.Total.ToString());d.AddKeyValue("Aperte",a.Open.ToString());d.AddKeyValue("In corso",a.InProgress.ToString());d.AddKeyValue("Completate",a.Completed.ToString());d.AddKeyValue("Scadute",a.Overdue.ToString());d.AddKeyValue("Tempo medio completamento",$"{a.AverageCompletionDays:N1} giorni");d.AddKeyValue("Completate entro scadenza",$"{a.OnTimePercentage:N1}%");d.AddHeading("Distribuzione per priorita");foreach(var x in a.ByPriority)d.AddKeyValue(x.Key,x.Value.ToString());d.AddHeading("Distribuzione per responsabile");foreach(var x in a.ByOwner)d.AddKeyValue(x.Key,x.Value.ToString());d.AddHeading("Dettaglio azioni");foreach(var x in rows){d.AddText($"#{x.Id} {x.Title}",11);d.AddText($"{x.Status} | {x.Priority} | {x.Owner} | scadenza {Date(x.DueDate)}",9);}d.AddSignaturePair("Responsabile qualita","Responsabile processo");return new PdfExportService().Export(d,Folder(),$"Indicatori-Piano-azioni-CAPA-{DateTime.Now:yyyyMMdd-HHmmss}");}
 private static (DateTime created,DateTime closed) CreatedClosed(SupplierRmaCapaGovernanceAction x)=>(DateTime.TryParse(x.CreatedAt,out var c)?c:DateTime.Today,DateTime.TryParse(x.ClosedAt,out var d)?d:DateTime.Today);private static string Date(string v)=>DateTime.TryParse(v,out var d)?d.ToString("dd/MM/yyyy"):v;private static string Csv(string v)=>$"\"{(v??"").Replace("\"","\"\"")}\"";private static string Folder(){var f=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),"Accyourate Enterprise X","Piano azioni CAPA");Directory.CreateDirectory(f);return f;}
 private static void Brand(SimplePdfDocument d,ApplicationSettings s,DocumentTemplateSettings t,string code){d.Branding.CompanyName=string.IsNullOrWhiteSpace(s.Company.LegalName)?s.Company.CompanyName:s.Company.LegalName;d.Branding.CompanyDetailLines.AddRange(new[]{s.Company.Address,string.Join(" ",new[]{s.Company.City,s.Company.Province}.Where(v=>!string.IsNullOrWhiteSpace(v))),string.Join(" - ",new[]{s.Company.Phone,s.Company.Email}.Where(v=>!string.IsNullOrWhiteSpace(v)))}.Where(v=>!string.IsNullOrWhiteSpace(v)));d.Branding.HeaderLayout=t.HeaderLayout;d.Branding.LogoPath=s.Company.LogoPath;d.Branding.LogoSize=t.LogoSize;d.Branding.LogoPosition=t.LogoPosition;d.Branding.PrimaryColor=t.PrimaryColor;d.Branding.DocumentLabel="INDICATORI PIANO AZIONI CAPA";d.Branding.DocumentCode=code;d.Branding.DocumentVersion=t.DocumentVersion;d.Branding.FooterText=t.FooterText;d.Branding.ConfidentialityText=t.ConfidentialityText;d.Branding.ShowLogo=t.ShowLogo;d.Branding.ShowCompanyDetails=t.ShowCompanyDetails;d.Branding.ShowDocumentMetadata=t.ShowDocumentMetadata;d.Branding.ShowFooter=t.ShowFooter;d.Branding.ShowPageNumber=t.ShowPageNumber;d.Branding.ShowPrintTimestamp=t.ShowPrintTimestamp;}
}
