using System.Security.Cryptography;using System.Text;using Microsoft.Data.Sqlite;
namespace Accyourate.App.AssetManagement.Services;
public sealed class SupplierRmaCapaAttestation{public int Id{get;init;}public int RegistryId{get;init;}public string Approver{get;init;}="";public string Role{get;init;}="";public string ArchiveHash{get;init;}="";public string ArchivePath{get;init;}="";public string AttestedAt{get;init;}="";public string ReportPath{get;init;}="";public bool IsValid{get;init;}}
public sealed class SupplierRmaCapaAttestationService
{
 private readonly string _cs;public SupplierRmaCapaAttestationService(string? db=null){var f=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),"AccyourateEnterpriseX");Directory.CreateDirectory(f);_cs=$"Data Source={db??Path.Combine(f,"accyourate-assets.db")}";using var c=Open();using var q=c.CreateCommand();q.CommandText="CREATE TABLE IF NOT EXISTS SupplierRmaCapaAttestations(Id INTEGER PRIMARY KEY AUTOINCREMENT,RegistryId INTEGER NOT NULL,Approver TEXT NOT NULL,Role TEXT NOT NULL,ArchiveHash TEXT NOT NULL,ArchivePath TEXT NOT NULL,AttestedAt TEXT NOT NULL,ReportPath TEXT NOT NULL);";q.ExecuteNonQuery();}
 public SupplierRmaCapaAttestation Attest(SupplierRmaCapaDossierRegistryRecord x,string role,string user){if(x.ApprovalStatus!="Approvato")throw new InvalidOperationException("Il riesame deve essere approvato.");if(!File.Exists(x.ArchivePath))throw new InvalidOperationException("Archivio non disponibile.");if(string.IsNullOrWhiteSpace(role))throw new InvalidOperationException("Indica il ruolo dell'approvatore.");var hash=Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(x.ArchivePath)));var folder=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),"Accyourate Enterprise X","Attestazioni CAPA");Directory.CreateDirectory(folder);var report=Path.Combine(folder,$"Attestazione-{x.CaseNumber}-{x.Id}-{DateTime.Now:yyyyMMdd-HHmmss}.txt");File.WriteAllText(report,$"ATTESTAZIONE RIESAME CAPA\n\nPratica: {x.CaseNumber}\nRevisione: {x.Revision}\nApprovatore: {user}\nRuolo: {role}\nData: {DateTime.Now:dd/MM/yyyy HH:mm:ss}\nArchivio: {x.ArchivePath}\nSHA-256: {hash}\n",new UTF8Encoding(true));using var c=Open();using var q=c.CreateCommand();q.CommandText="INSERT INTO SupplierRmaCapaAttestations(RegistryId,Approver,Role,ArchiveHash,ArchivePath,AttestedAt,ReportPath) VALUES($id,$u,$r,$h,$a,$d,$p);SELECT last_insert_rowid();";q.Parameters.AddWithValue("$id",x.Id);q.Parameters.AddWithValue("$u",user);q.Parameters.AddWithValue("$r",role);q.Parameters.AddWithValue("$h",hash);q.Parameters.AddWithValue("$a",x.ArchivePath);q.Parameters.AddWithValue("$d",DateTime.Now.ToString("s"));q.Parameters.AddWithValue("$p",report);var id=Convert.ToInt32(q.ExecuteScalar());return new(){Id=id,RegistryId=x.Id,Approver=user,Role=role,ArchiveHash=hash,ArchivePath=x.ArchivePath,AttestedAt=DateTime.Now.ToString("s"),ReportPath=report,IsValid=true};}
 public SupplierRmaCapaAttestation? Latest(int id){using var c=Open();using var q=c.CreateCommand();q.CommandText="SELECT Id,RegistryId,Approver,Role,ArchiveHash,ArchivePath,AttestedAt,ReportPath FROM SupplierRmaCapaAttestations WHERE RegistryId=$id ORDER BY Id DESC LIMIT 1;";q.Parameters.AddWithValue("$id",id);using var r=q.ExecuteReader();if(!r.Read())return null;var path=r.GetString(5);var hash=File.Exists(path)?Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(path))):"";return new(){Id=r.GetInt32(0),RegistryId=r.GetInt32(1),Approver=r.GetString(2),Role=r.GetString(3),ArchiveHash=r.GetString(4),ArchivePath=path,AttestedAt=r.GetString(6),ReportPath=r.GetString(7),IsValid=hash==r.GetString(4)};}
 private SqliteConnection Open(){var c=new SqliteConnection(_cs);c.Open();return c;}
}
