using Microsoft.Data.Sqlite;using Accyourate.App.Platform.Notifications;
namespace Accyourate.App.AssetManagement.Services;
public sealed class SupplierRmaCapaGovernanceGoals{public double MinimumOnTimePercentage{get;init;}=80;public int MaximumOverdueActions{get;init;}=0;public double MaximumAverageCompletionDays{get;init;}=30;public int LowPriorityDays{get;init;}=30;public int MediumPriorityDays{get;init;}=21;public int HighPriorityDays{get;init;}=14;public int CriticalPriorityDays{get;init;}=7;}
public sealed class SupplierRmaCapaGovernanceGoalEvaluation{public string OverallStatus{get;init;}="Conforme";public string OnTimeStatus{get;init;}="Conforme";public string OverdueStatus{get;init;}="Conforme";public string AverageStatus{get;init;}="Conforme";public int Violations{get;init;}}
public sealed class SupplierRmaCapaGovernanceGoalHistory{public int Id{get;init;}public string OldValues{get;init;}="";public string NewValues{get;init;}="";public string Notes{get;init;}="";public string UpdatedAt{get;init;}="";public string UpdatedBy{get;init;}="";}
public sealed class SupplierRmaCapaGovernanceGoalService
{
 private readonly string _cs;public SupplierRmaCapaGovernanceGoalService(string? db=null){var folder=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),"AccyourateEnterpriseX");Directory.CreateDirectory(folder);_cs=$"Data Source={db??Path.Combine(folder,"accyourate-assets.db")}";using var c=Open();using var q=c.CreateCommand();q.CommandText="CREATE TABLE IF NOT EXISTS SupplierRmaCapaGovernanceGoals(Id INTEGER PRIMARY KEY CHECK(Id=1),MinimumOnTimePercentage REAL NOT NULL,MaximumOverdueActions INTEGER NOT NULL,MaximumAverageCompletionDays REAL NOT NULL,LowPriorityDays INTEGER NOT NULL,MediumPriorityDays INTEGER NOT NULL,HighPriorityDays INTEGER NOT NULL,CriticalPriorityDays INTEGER NOT NULL);INSERT OR IGNORE INTO SupplierRmaCapaGovernanceGoals VALUES(1,80,0,30,30,21,14,7);CREATE TABLE IF NOT EXISTS SupplierRmaCapaGovernanceGoalHistory(Id INTEGER PRIMARY KEY AUTOINCREMENT,OldValues TEXT NOT NULL,NewValues TEXT NOT NULL,Notes TEXT NOT NULL,UpdatedAt TEXT NOT NULL,UpdatedBy TEXT NOT NULL);CREATE TABLE IF NOT EXISTS SupplierRmaCapaGovernanceGoalNotifications(NotificationKey TEXT PRIMARY KEY,CreatedAt TEXT NOT NULL);";q.ExecuteNonQuery();}
 public SupplierRmaCapaGovernanceGoals Get(){using var c=Open();using var q=c.CreateCommand();q.CommandText="SELECT MinimumOnTimePercentage,MaximumOverdueActions,MaximumAverageCompletionDays,LowPriorityDays,MediumPriorityDays,HighPriorityDays,CriticalPriorityDays FROM SupplierRmaCapaGovernanceGoals WHERE Id=1;";using var r=q.ExecuteReader();r.Read();return new(){MinimumOnTimePercentage=r.GetDouble(0),MaximumOverdueActions=r.GetInt32(1),MaximumAverageCompletionDays=r.GetDouble(2),LowPriorityDays=r.GetInt32(3),MediumPriorityDays=r.GetInt32(4),HighPriorityDays=r.GetInt32(5),CriticalPriorityDays=r.GetInt32(6)};}
 public void Save(SupplierRmaCapaGovernanceGoals x,string notes,string user){if(x.MinimumOnTimePercentage<0||x.MinimumOnTimePercentage>100||x.MaximumOverdueActions<0||x.MaximumAverageCompletionDays<0||new[]{x.LowPriorityDays,x.MediumPriorityDays,x.HighPriorityDays,x.CriticalPriorityDays}.Any(v=>v<1))throw new InvalidOperationException("Controlla i valori delle soglie.");if(string.IsNullOrWhiteSpace(notes))throw new InvalidOperationException("Indica la motivazione della modifica.");var old=Get();using var c=Open();using var q=c.CreateCommand();q.CommandText="UPDATE SupplierRmaCapaGovernanceGoals SET MinimumOnTimePercentage=$o,MaximumOverdueActions=$s,MaximumAverageCompletionDays=$m,LowPriorityDays=$l,MediumPriorityDays=$n,HighPriorityDays=$h,CriticalPriorityDays=$c WHERE Id=1;";q.Parameters.AddWithValue("$o",x.MinimumOnTimePercentage);q.Parameters.AddWithValue("$s",x.MaximumOverdueActions);q.Parameters.AddWithValue("$m",x.MaximumAverageCompletionDays);q.Parameters.AddWithValue("$l",x.LowPriorityDays);q.Parameters.AddWithValue("$n",x.MediumPriorityDays);q.Parameters.AddWithValue("$h",x.HighPriorityDays);q.Parameters.AddWithValue("$c",x.CriticalPriorityDays);q.ExecuteNonQuery();using var a=c.CreateCommand();a.CommandText="INSERT INTO SupplierRmaCapaGovernanceGoalHistory(OldValues,NewValues,Notes,UpdatedAt,UpdatedBy) VALUES($o,$n,$x,$d,$u);";a.Parameters.AddWithValue("$o",Describe(old));a.Parameters.AddWithValue("$n",Describe(x));a.Parameters.AddWithValue("$x",notes.Trim());a.Parameters.AddWithValue("$d",DateTime.Now.ToString("s"));a.Parameters.AddWithValue("$u",user);a.ExecuteNonQuery();}
 public SupplierRmaCapaGovernanceGoalEvaluation Evaluate(SupplierRmaCapaGovernanceActionAnalytics a){var g=Get();var on=a.Completed==0?"Attenzione":a.OnTimePercentage>=g.MinimumOnTimePercentage?"Conforme":a.OnTimePercentage>=g.MinimumOnTimePercentage-10?"Attenzione":"Non conforme";var overdue=a.Overdue<=g.MaximumOverdueActions?"Conforme":a.Overdue<=g.MaximumOverdueActions+1?"Attenzione":"Non conforme";var average=a.Completed==0?"Attenzione":a.AverageCompletionDays<=g.MaximumAverageCompletionDays?"Conforme":a.AverageCompletionDays<=g.MaximumAverageCompletionDays*1.2?"Attenzione":"Non conforme";var states=new[]{on,overdue,average};return new(){OnTimeStatus=on,OverdueStatus=overdue,AverageStatus=average,OverallStatus=states.Contains("Non conforme")?"Non conforme":states.Contains("Attenzione")?"Attenzione":"Conforme",Violations=states.Count(x=>x!="Conforme")};}
 public IReadOnlyList<SupplierRmaCapaGovernanceGoalHistory> History(){using var c=Open();using var q=c.CreateCommand();q.CommandText="SELECT Id,OldValues,NewValues,Notes,UpdatedAt,UpdatedBy FROM SupplierRmaCapaGovernanceGoalHistory ORDER BY Id DESC;";using var r=q.ExecuteReader();var v=new List<SupplierRmaCapaGovernanceGoalHistory>();while(r.Read())v.Add(new(){Id=r.GetInt32(0),OldValues=r.GetString(1),NewValues=r.GetString(2),Notes=r.GetString(3),UpdatedAt=r.GetString(4),UpdatedBy=r.GetString(5)});return v;}
 public int PublishAlerts(SupplierRmaCapaGovernanceActionAnalytics analytics,NotificationService? n=null){var e=Evaluate(analytics);if(e.OverallStatus=="Conforme")return 0;var key=$"capa-governance-goals:{e.OverallStatus}:{DateTime.Today:yyyyMMdd}";using var c=Open();using var q=c.CreateCommand();q.CommandText="SELECT COUNT(*) FROM SupplierRmaCapaGovernanceGoalNotifications WHERE NotificationKey=$k;";q.Parameters.AddWithValue("$k",key);if(Convert.ToInt32(q.ExecuteScalar())>0)return 0;n??=new NotificationService();n.Publish("Soglie Governance CAPA superate",$"Esito {e.OverallStatus}: {e.Violations} indicatori richiedono attenzione.",NotificationCategory.Asset,e.OverallStatus=="Non conforme"?NotificationPriority.Critical:NotificationPriority.High,"Obiettivi Governance CAPA","open-rma-corrective-actions","");using var add=c.CreateCommand();add.CommandText="INSERT INTO SupplierRmaCapaGovernanceGoalNotifications(NotificationKey,CreatedAt) VALUES($k,$d);";add.Parameters.AddWithValue("$k",key);add.Parameters.AddWithValue("$d",DateTime.Now.ToString("s"));add.ExecuteNonQuery();return 1;}
 private static string Describe(SupplierRmaCapaGovernanceGoals x)=>$"Puntualita {x.MinimumOnTimePercentage:N1}%; scadute max {x.MaximumOverdueActions}; media max {x.MaximumAverageCompletionDays:N1} gg; priorita B/M/A/C {x.LowPriorityDays}/{x.MediumPriorityDays}/{x.HighPriorityDays}/{x.CriticalPriorityDays} gg";private SqliteConnection Open(){var c=new SqliteConnection(_cs);c.Open();return c;}
}
