using Accyourate.App.AssetManagement.Models;
using Accyourate.App.Platform.Notifications;
using Microsoft.Data.Sqlite;

namespace Accyourate.App.AssetManagement.Services;

public sealed class SupplierRmaPortalRepository
{
    private readonly string _databasePath;private readonly NotificationService _notifications;
    public SupplierRmaPortalRepository(string? databasePath=null,NotificationService? notifications=null){var folder=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),"AccyourateEnterpriseX");Directory.CreateDirectory(folder);_databasePath=databasePath??Path.Combine(folder,"accyourate-assets.db");_notifications=notifications??new NotificationService();using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="""
        CREATE TABLE IF NOT EXISTS SupplierRmaContacts(Id INTEGER PRIMARY KEY AUTOINCREMENT,SupplierId INTEGER NOT NULL,Name TEXT NOT NULL,Role TEXT,Email TEXT,Phone TEXT,IsPrimary INTEGER NOT NULL DEFAULT 0,Notes TEXT,CreatedAt TEXT NOT NULL);
        CREATE TABLE IF NOT EXISTS SupplierRmaInteractions(Id INTEGER PRIMARY KEY AUTOINCREMENT,SupplierId INTEGER NOT NULL,RmaId INTEGER NOT NULL DEFAULT 0,Type TEXT NOT NULL,Direction TEXT NOT NULL,Subject TEXT NOT NULL,Message TEXT,Status TEXT NOT NULL,FollowUpDate TEXT,CreatedAt TEXT NOT NULL,CreatedBy TEXT);
        CREATE TABLE IF NOT EXISTS SupplierRmaAttachments(Id INTEGER PRIMARY KEY AUTOINCREMENT,SupplierId INTEGER NOT NULL,RmaId INTEGER NOT NULL DEFAULT 0,Category TEXT NOT NULL,FileName TEXT NOT NULL,StoredPath TEXT NOT NULL,Notes TEXT,CreatedAt TEXT NOT NULL);
        CREATE TABLE IF NOT EXISTS SupplierRmaFollowUpLog(NotificationKey TEXT PRIMARY KEY,InteractionId INTEGER NOT NULL,CreatedAt TEXT NOT NULL);
        CREATE INDEX IF NOT EXISTS IX_SupplierRmaContacts_Supplier ON SupplierRmaContacts(SupplierId);
        CREATE INDEX IF NOT EXISTS IX_SupplierRmaInteractions_Supplier ON SupplierRmaInteractions(SupplierId);
        CREATE INDEX IF NOT EXISTS IX_SupplierRmaAttachments_Supplier ON SupplierRmaAttachments(SupplierId);
        CREATE TABLE IF NOT EXISTS SupplierRmaFollowUpAudit(Id INTEGER PRIMARY KEY AUTOINCREMENT,InteractionId INTEGER NOT NULL,Action TEXT NOT NULL,OldValue TEXT,NewValue TEXT,Notes TEXT,CreatedAt TEXT NOT NULL,CreatedBy TEXT);
        """;cmd.ExecuteNonQuery();EnsureColumn(c,"SupplierRmaInteractions","UpdatedAt","TEXT");EnsureColumn(c,"SupplierRmaInteractions","CompletedAt","TEXT");EnsureColumn(c,"SupplierRmaInteractions","CancelledAt","TEXT");EnsureColumn(c,"SupplierRmaInteractions","ResolutionNotes","TEXT");EnsureColumn(c,"SupplierRmaInteractions","Priority","TEXT NOT NULL DEFAULT 'Normale'");EnsureColumn(c,"SupplierRmaInteractions","Owner","TEXT");}
    public int SaveContact(SupplierPortalContact value){if(value.SupplierId<=0||string.IsNullOrWhiteSpace(value.Name))throw new InvalidOperationException("Inserisci il nominativo del contatto.");using var c=Open();using var t=c.BeginTransaction();if(value.IsPrimary){using var clear=c.CreateCommand();clear.Transaction=t;clear.CommandText="UPDATE SupplierRmaContacts SET IsPrimary=0 WHERE SupplierId=$supplier;";clear.Parameters.AddWithValue("$supplier",value.SupplierId);clear.ExecuteNonQuery();}using var cmd=c.CreateCommand();cmd.Transaction=t;cmd.CommandText="INSERT INTO SupplierRmaContacts(SupplierId,Name,Role,Email,Phone,IsPrimary,Notes,CreatedAt) VALUES($supplier,$name,$role,$email,$phone,$primary,$notes,$date);SELECT last_insert_rowid();";cmd.Parameters.AddWithValue("$supplier",value.SupplierId);cmd.Parameters.AddWithValue("$name",value.Name.Trim());cmd.Parameters.AddWithValue("$role",value.Role.Trim());cmd.Parameters.AddWithValue("$email",value.Email.Trim());cmd.Parameters.AddWithValue("$phone",value.Phone.Trim());cmd.Parameters.AddWithValue("$primary",value.IsPrimary?1:0);cmd.Parameters.AddWithValue("$notes",value.Notes.Trim());cmd.Parameters.AddWithValue("$date",DateTime.Now.ToString("s"));var id=Convert.ToInt32(cmd.ExecuteScalar());t.Commit();return id;}
    public int AddInteraction(SupplierPortalInteraction value)
    {
        if(value.SupplierId<=0||string.IsNullOrWhiteSpace(value.Subject))throw new InvalidOperationException("Inserisci l'oggetto della comunicazione.");
        int id;
        using(var c=Open())
        using(var cmd=c.CreateCommand())
        {
            cmd.CommandText="INSERT INTO SupplierRmaInteractions(SupplierId,RmaId,Type,Direction,Subject,Message,Status,FollowUpDate,CreatedAt,CreatedBy) VALUES($supplier,$rma,$type,$direction,$subject,$message,$status,$follow,$date,$user);SELECT last_insert_rowid();";
            cmd.Parameters.AddWithValue("$supplier",value.SupplierId);cmd.Parameters.AddWithValue("$rma",value.RmaId);cmd.Parameters.AddWithValue("$type",value.Type);cmd.Parameters.AddWithValue("$direction",value.Direction);cmd.Parameters.AddWithValue("$subject",value.Subject.Trim());cmd.Parameters.AddWithValue("$message",value.Message.Trim());cmd.Parameters.AddWithValue("$status",value.Status);cmd.Parameters.AddWithValue("$follow",value.FollowUpDate.Trim());cmd.Parameters.AddWithValue("$date",DateTime.Now.ToString("s"));cmd.Parameters.AddWithValue("$user",value.CreatedBy);
            id=Convert.ToInt32(cmd.ExecuteScalar());
        }
        PublishFollowUpReminders();
        return id;
    }
    public int AttachFile(int supplierId,int rmaId,string category,string sourcePath,string notes){if(!File.Exists(sourcePath))throw new FileNotFoundException("File non trovato.",sourcePath);var folder=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),"AccyourateEnterpriseX","SupplierPortal",supplierId.ToString());Directory.CreateDirectory(folder);var safe=string.Concat(Path.GetFileName(sourcePath).Select(c=>Path.GetInvalidFileNameChars().Contains(c)?'_':c));var destination=Path.Combine(folder,$"{DateTime.Now:yyyyMMddHHmmss}-{Guid.NewGuid():N}-{safe}");File.Copy(sourcePath,destination,false);using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="INSERT INTO SupplierRmaAttachments(SupplierId,RmaId,Category,FileName,StoredPath,Notes,CreatedAt) VALUES($supplier,$rma,$category,$name,$path,$notes,$date);SELECT last_insert_rowid();";cmd.Parameters.AddWithValue("$supplier",supplierId);cmd.Parameters.AddWithValue("$rma",rmaId);cmd.Parameters.AddWithValue("$category",category);cmd.Parameters.AddWithValue("$name",Path.GetFileName(sourcePath));cmd.Parameters.AddWithValue("$path",destination);cmd.Parameters.AddWithValue("$notes",notes);cmd.Parameters.AddWithValue("$date",DateTime.Now.ToString("s"));return Convert.ToInt32(cmd.ExecuteScalar());}
    public IReadOnlyList<SupplierPortalContact> GetContacts(int supplierId){using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="SELECT Id,SupplierId,Name,Role,Email,Phone,IsPrimary,Notes,CreatedAt FROM SupplierRmaContacts WHERE SupplierId=$supplier ORDER BY IsPrimary DESC,Name;";cmd.Parameters.AddWithValue("$supplier",supplierId);using var r=cmd.ExecuteReader();var list=new List<SupplierPortalContact>();while(r.Read())list.Add(new(){Id=r.GetInt32(0),SupplierId=r.GetInt32(1),Name=S(r,2),Role=S(r,3),Email=S(r,4),Phone=S(r,5),IsPrimary=r.GetInt32(6)==1,Notes=S(r,7),CreatedAt=S(r,8)});return list;}
    public IReadOnlyList<SupplierPortalInteraction> GetInteractions(int supplierId){using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="SELECT Id,SupplierId,RmaId,Type,Direction,Subject,Message,Status,FollowUpDate,CreatedAt,CreatedBy,UpdatedAt,CompletedAt,CancelledAt,ResolutionNotes,Priority,Owner FROM SupplierRmaInteractions WHERE SupplierId=$supplier ORDER BY CreatedAt DESC,Id DESC;";cmd.Parameters.AddWithValue("$supplier",supplierId);using var r=cmd.ExecuteReader();var list=new List<SupplierPortalInteraction>();while(r.Read())list.Add(new(){Id=r.GetInt32(0),SupplierId=r.GetInt32(1),RmaId=r.GetInt32(2),Type=S(r,3),Direction=S(r,4),Subject=S(r,5),Message=S(r,6),Status=S(r,7),FollowUpDate=S(r,8),CreatedAt=S(r,9),CreatedBy=S(r,10),UpdatedAt=S(r,11),CompletedAt=S(r,12),CancelledAt=S(r,13),ResolutionNotes=S(r,14),Priority=string.IsNullOrWhiteSpace(S(r,15))?"Normale":S(r,15),Owner=string.IsNullOrWhiteSpace(S(r,16))?S(r,10):S(r,16)});return list;}
    public IReadOnlyList<SupplierPortalInteraction> GetAllFollowUps(){var suppliers=new MaintenancePurchasingRepository().GetSuppliers().ToDictionary(x=>x.Id,x=>x.Name);using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="SELECT Id,SupplierId,RmaId,Type,Direction,Subject,Message,Status,FollowUpDate,CreatedAt,CreatedBy,UpdatedAt,CompletedAt,CancelledAt,ResolutionNotes,Priority,Owner FROM SupplierRmaInteractions WHERE FollowUpDate<>'' ORDER BY FollowUpDate,Id DESC;";using var r=cmd.ExecuteReader();var list=new List<SupplierPortalInteraction>();while(r.Read()){var supplierId=r.GetInt32(1);list.Add(new(){Id=r.GetInt32(0),SupplierId=supplierId,RmaId=r.GetInt32(2),Type=S(r,3),Direction=S(r,4),Subject=S(r,5),Message=S(r,6),Status=S(r,7),FollowUpDate=S(r,8),CreatedAt=S(r,9),CreatedBy=S(r,10),UpdatedAt=S(r,11),CompletedAt=S(r,12),CancelledAt=S(r,13),ResolutionNotes=S(r,14),Priority=string.IsNullOrWhiteSpace(S(r,15))?"Normale":S(r,15),Owner=string.IsNullOrWhiteSpace(S(r,16))?S(r,10):S(r,16),SupplierName=suppliers.TryGetValue(supplierId,out var name)?name:$"Fornitore #{supplierId}"});}return list;}
    public void UpdateFollowUpAssignment(int id,string priority,string owner){using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="UPDATE SupplierRmaInteractions SET Priority=$priority,Owner=$owner,UpdatedAt=$date WHERE Id=$id;";cmd.Parameters.AddWithValue("$id",id);cmd.Parameters.AddWithValue("$priority",priority);cmd.Parameters.AddWithValue("$owner",owner.Trim());cmd.Parameters.AddWithValue("$date",DateTime.Now.ToString("s"));cmd.ExecuteNonQuery();}
    public void CompleteFollowUp(int id,string notes,string user)=>ChangeFollowUp(id,"Completata","",notes,user,"Completato");
    public void CancelFollowUp(int id,string notes,string user)=>ChangeFollowUp(id,"Annullata","",notes,user,"Annullato");
    public void RescheduleFollowUp(int id,DateTime date,string notes,string user)=>ChangeFollowUp(id,"Aperta",date.ToString("yyyy-MM-dd"),notes,user,"Rinviato");
    public IReadOnlyList<SupplierFollowUpAudit> GetFollowUpAudit(int interactionId){using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="SELECT Id,InteractionId,Action,OldValue,NewValue,Notes,CreatedAt,CreatedBy FROM SupplierRmaFollowUpAudit WHERE InteractionId=$id ORDER BY Id DESC;";cmd.Parameters.AddWithValue("$id",interactionId);using var r=cmd.ExecuteReader();var list=new List<SupplierFollowUpAudit>();while(r.Read())list.Add(new(){Id=r.GetInt32(0),InteractionId=r.GetInt32(1),Action=S(r,2),OldValue=S(r,3),NewValue=S(r,4),Notes=S(r,5),CreatedAt=S(r,6),CreatedBy=S(r,7)});return list;}
    public IReadOnlyList<SupplierPortalAttachment> GetAttachments(int supplierId){using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="SELECT Id,SupplierId,RmaId,Category,FileName,StoredPath,Notes,CreatedAt FROM SupplierRmaAttachments WHERE SupplierId=$supplier ORDER BY CreatedAt DESC,Id DESC;";cmd.Parameters.AddWithValue("$supplier",supplierId);using var r=cmd.ExecuteReader();var list=new List<SupplierPortalAttachment>();while(r.Read())list.Add(new(){Id=r.GetInt32(0),SupplierId=r.GetInt32(1),RmaId=r.GetInt32(2),Category=S(r,3),FileName=S(r,4),StoredPath=S(r,5),Notes=S(r,6),CreatedAt=S(r,7)});return list;}
    public int PublishFollowUpReminders(){var count=0;using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="SELECT Id,SupplierId,RmaId,Subject,FollowUpDate FROM SupplierRmaInteractions WHERE Status='Aperta' AND FollowUpDate<>'';";using var r=cmd.ExecuteReader();var pending=new List<(int Id,int Supplier,int Rma,string Subject,string Date)>();while(r.Read())pending.Add((r.GetInt32(0),r.GetInt32(1),r.GetInt32(2),S(r,3),S(r,4)));r.Close();foreach(var item in pending){if(!DateTime.TryParse(item.Date,out var due)||due.Date>DateTime.Today)continue;var key=$"supplier-followup:{item.Id}:{due:yyyyMMdd}";using var check=c.CreateCommand();check.CommandText="SELECT COUNT(*) FROM SupplierRmaFollowUpLog WHERE NotificationKey=$key;";check.Parameters.AddWithValue("$key",key);if(Convert.ToInt32(check.ExecuteScalar())>0)continue;_notifications.Publish("Sollecito fornitore da eseguire",item.Subject,NotificationCategory.Asset,NotificationPriority.High,"Portale fornitori","open-supplier-portal",item.Supplier.ToString());using var insert=c.CreateCommand();insert.CommandText="INSERT INTO SupplierRmaFollowUpLog(NotificationKey,InteractionId,CreatedAt) VALUES($key,$id,$date);";insert.Parameters.AddWithValue("$key",key);insert.Parameters.AddWithValue("$id",item.Id);insert.Parameters.AddWithValue("$date",DateTime.Now.ToString("s"));insert.ExecuteNonQuery();count++;}return count;}
    private void ChangeFollowUp(int id,string status,string followUpDate,string notes,string user,string action){using var c=Open();using var t=c.BeginTransaction();string oldStatus,oldDate;using(var read=c.CreateCommand()){read.Transaction=t;read.CommandText="SELECT Status,FollowUpDate FROM SupplierRmaInteractions WHERE Id=$id;";read.Parameters.AddWithValue("$id",id);using var r=read.ExecuteReader();if(!r.Read())throw new InvalidOperationException("Sollecito non trovato.");oldStatus=S(r,0);oldDate=S(r,1);}var now=DateTime.Now.ToString("s");using(var update=c.CreateCommand()){update.Transaction=t;update.CommandText="UPDATE SupplierRmaInteractions SET Status=$status,FollowUpDate=$follow,UpdatedAt=$now,CompletedAt=$completed,CancelledAt=$cancelled,ResolutionNotes=$notes WHERE Id=$id;";update.Parameters.AddWithValue("$id",id);update.Parameters.AddWithValue("$status",status);update.Parameters.AddWithValue("$follow",followUpDate);update.Parameters.AddWithValue("$now",now);update.Parameters.AddWithValue("$completed",status=="Completata"?now:"");update.Parameters.AddWithValue("$cancelled",status=="Annullata"?now:"");update.Parameters.AddWithValue("$notes",notes.Trim());update.ExecuteNonQuery();}using(var audit=c.CreateCommand()){audit.Transaction=t;audit.CommandText="INSERT INTO SupplierRmaFollowUpAudit(InteractionId,Action,OldValue,NewValue,Notes,CreatedAt,CreatedBy) VALUES($id,$action,$old,$new,$notes,$now,$user);";audit.Parameters.AddWithValue("$id",id);audit.Parameters.AddWithValue("$action",action);audit.Parameters.AddWithValue("$old",$"{oldStatus} | {oldDate}");audit.Parameters.AddWithValue("$new",$"{status} | {followUpDate}");audit.Parameters.AddWithValue("$notes",notes.Trim());audit.Parameters.AddWithValue("$now",now);audit.Parameters.AddWithValue("$user",user);audit.ExecuteNonQuery();}t.Commit();if(status=="Aperta")PublishFollowUpReminders();}
    private static void EnsureColumn(SqliteConnection c,string table,string column,string type){using var check=c.CreateCommand();check.CommandText=$"PRAGMA table_info({table});";using var r=check.ExecuteReader();while(r.Read())if(string.Equals(S(r,1),column,StringComparison.OrdinalIgnoreCase))return;r.Close();using var alter=c.CreateCommand();alter.CommandText=$"ALTER TABLE {table} ADD COLUMN {column} {type};";alter.ExecuteNonQuery();}
    private SqliteConnection Open(){var c=new SqliteConnection($"Data Source={_databasePath}");c.Open();return c;}private static string S(SqliteDataReader r,int i)=>r.IsDBNull(i)?"":r.GetString(i);
}
