using System.Security.Cryptography;using System.Text;using Microsoft.Data.Sqlite;using Accyourate.App.Platform.Notifications;
namespace Accyourate.App.AssetManagement.Services;
public sealed class SupplierRmaCapaAttestation{public int Id{get;init;}public int RegistryId{get;init;}public string CaseNumber{get;init;}="";public string Revision{get;init;}="";public string Approver{get;init;}="";public string Role{get;init;}="";public string ArchiveHash{get;init;}="";public string ArchivePath{get;init;}="";public string AttestedAt{get;init;}="";public string ReportPath{get;init;}="";public bool ArchiveAvailable=>File.Exists(ArchivePath);public bool ReportAvailable=>File.Exists(ReportPath);public bool IsValid{get;init;}public string ValidationStatus=>!ArchiveAvailable?"Archivio mancante":IsValid?"Valida":"Non valida";}
public sealed class SupplierRmaCapaAttestationService
{
 private readonly string _cs;public SupplierRmaCapaAttestationService(string? db=null){var f=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),"AccyourateEnterpriseX");Directory.CreateDirectory(f);_cs=$"Data Source={db??Path.Combine(f,"accyourate-assets.db")}";using var c=Open();using var q=c.CreateCommand();q.CommandText="CREATE TABLE IF NOT EXISTS SupplierRmaCapaAttestations(Id INTEGER PRIMARY KEY AUTOINCREMENT,RegistryId INTEGER NOT NULL,Approver TEXT NOT NULL,Role TEXT NOT NULL,ArchiveHash TEXT NOT NULL,ArchivePath TEXT NOT NULL,AttestedAt TEXT NOT NULL,ReportPath TEXT NOT NULL);CREATE TABLE IF NOT EXISTS SupplierRmaCapaAttestationNotifications(NotificationKey TEXT PRIMARY KEY,AttestationId INTEGER NOT NULL,CreatedAt TEXT NOT NULL);";q.ExecuteNonQuery();}
 public SupplierRmaCapaAttestation Attest(SupplierRmaCapaDossierRegistryRecord x,string role,string user){if(x.ApprovalStatus!="Approvato")throw new InvalidOperationException("Il riesame deve essere approvato.");if(!File.Exists(x.ArchivePath))throw new InvalidOperationException("Archivio non disponibile.");if(string.IsNullOrWhiteSpace(role))throw new InvalidOperationException("Indica il ruolo dell'approvatore.");var hash=Hash(x.ArchivePath);var folder=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),"Accyourate Enterprise X","Attestazioni CAPA");Directory.CreateDirectory(folder);var report=Path.Combine(folder,$"Attestazione-{x.CaseNumber}-{x.Id}-{DateTime.Now:yyyyMMdd-HHmmss}.txt");File.WriteAllText(report,$"ATTESTAZIONE RIESAME CAPA\n\nPratica: {x.CaseNumber}\nRevisione: {x.Revision}\nApprovatore: {user}\nRuolo: {role}\nData: {DateTime.Now:dd/MM/yyyy HH:mm:ss}\nArchivio: {x.ArchivePath}\nSHA-256: {hash}\n",new UTF8Encoding(true));using var c=Open();using var q=c.CreateCommand();q.CommandText="INSERT INTO SupplierRmaCapaAttestations(RegistryId,Approver,Role,ArchiveHash,ArchivePath,AttestedAt,ReportPath) VALUES($id,$u,$r,$h,$a,$d,$p);SELECT last_insert_rowid();";q.Parameters.AddWithValue("$id",x.Id);q.Parameters.AddWithValue("$u",user);q.Parameters.AddWithValue("$r",role);q.Parameters.AddWithValue("$h",hash);q.Parameters.AddWithValue("$a",x.ArchivePath);q.Parameters.AddWithValue("$d",DateTime.Now.ToString("s"));q.Parameters.AddWithValue("$p",report);var id=Convert.ToInt32(q.ExecuteScalar());return new(){Id=id,RegistryId=x.Id,CaseNumber=x.CaseNumber,Revision=x.Revision,Approver=user,Role=role,ArchiveHash=hash,ArchivePath=x.ArchivePath,AttestedAt=DateTime.Now.ToString("s"),ReportPath=report,IsValid=true};}
 public SupplierRmaCapaAttestation? Latest(int id)=>GetAll().FirstOrDefault(x=>x.RegistryId==id);
 public IReadOnlyList<SupplierRmaCapaAttestation> GetAll(){using var c=Open();using var q=c.CreateCommand();q.CommandText="SELECT a.Id,a.RegistryId,COALESCE(r.CaseNumber,''),COALESCE(r.Revision,''),a.Approver,a.Role,a.ArchiveHash,a.ArchivePath,a.AttestedAt,a.ReportPath FROM SupplierRmaCapaAttestations a LEFT JOIN SupplierRmaCapaDossierRegistry r ON r.Id=a.RegistryId ORDER BY a.Id DESC;";using var rd=q.ExecuteReader();var list=new List<SupplierRmaCapaAttestation>();while(rd.Read()){var path=rd.GetString(7);var stored=rd.GetString(6);list.Add(new(){Id=rd.GetInt32(0),RegistryId=rd.GetInt32(1),CaseNumber=rd.GetString(2),Revision=rd.GetString(3),Approver=rd.GetString(4),Role=rd.GetString(5),ArchiveHash=stored,ArchivePath=path,AttestedAt=rd.GetString(8),ReportPath=rd.GetString(9),IsValid=File.Exists(path)&&string.Equals(Hash(path),stored,StringComparison.OrdinalIgnoreCase)});}return list;}
 public int PublishInvalidNotifications(NotificationService? notifications=null){notifications??=new NotificationService();var count=0;foreach(var x in GetAll().Where(x=>!x.IsValid)){var key=$"capa-attestation:{x.Id}:{x.ValidationStatus}:{DateTime.Today:yyyyMMdd}";using var c=Open();using var ck=c.CreateCommand();ck.CommandText="SELECT COUNT(*) FROM SupplierRmaCapaAttestationNotifications WHERE NotificationKey=$k;";ck.Parameters.AddWithValue("$k",key);if(Convert.ToInt32(ck.ExecuteScalar())>0)continue;notifications.Publish("Attestazione CAPA invalidata",$"{x.CaseNumber}: {x.ValidationStatus}.",NotificationCategory.Asset,NotificationPriority.Critical,"Controllo attestazioni CAPA","open-rma-corrective-actions",x.RegistryId.ToString());using var ins=c.CreateCommand();ins.CommandText="INSERT INTO SupplierRmaCapaAttestationNotifications(NotificationKey,AttestationId,CreatedAt) VALUES($k,$id,$d);";ins.Parameters.AddWithValue("$k",key);ins.Parameters.AddWithValue("$id",x.Id);ins.Parameters.AddWithValue("$d",DateTime.Now.ToString("s"));ins.ExecuteNonQuery();count++;}return count;}
 private static string Hash(string path)=>Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(path)));private SqliteConnection Open(){var c=new SqliteConnection(_cs);c.Open();return c;}
}
