using Accyourate.App.Platform.Pdf;
using Accyourate.App.Platform.Settings;
namespace Accyourate.App.AssetManagement.Services;
public sealed class SupplierRmaCapaGovernanceSnapshot{public int Dossiers{get;init;}public int ActiveDossiers{get;init;}public int ArchivedDossiers{get;init;}public int ApprovedDossiers{get;init;}public int MissingDocuments{get;init;}public int ReviewsDue{get;init;}public int ReviewsOverdue{get;init;}public int Attestations{get;init;}public int ValidAttestations{get;init;}public int InvalidAttestations{get;init;}public int MissingAttestationArchives{get;init;}public int Exports{get;init;}public int ValidExports{get;init;}public int InvalidExports{get;init;}public int MissingExports{get;init;}public int RetentionDue{get;init;}public int RetentionOverdue{get;init;}public int CriticalCount=>MissingDocuments+ReviewsOverdue+InvalidAttestations+MissingAttestationArchives+InvalidExports+MissingExports+RetentionOverdue;}
public sealed class SupplierRmaCapaGovernanceDashboardService
{
 private readonly SupplierRmaCapaDossierRegistryService _dossiers=new();private readonly SupplierRmaCapaAttestationService _attestations=new();private readonly SupplierRmaCapaAttestationExportService _exports=new();private readonly SettingsService _settings=new();
 public SupplierRmaCapaGovernanceSnapshot Load(){var d=_dossiers.GetAll();var a=_attestations.GetAll();var e=_exports.GetExports();return new(){Dossiers=d.Count,ActiveDossiers=d.Count(x=>x.DocumentStatus=="Attivo"),ArchivedDossiers=d.Count(x=>x.DocumentStatus=="Archiviato"),ApprovedDossiers=d.Count(x=>x.ApprovalStatus=="Approvato"),MissingDocuments=d.Count(x=>x.MissingDocuments),ReviewsDue=d.Count(x=>x.IsReviewDueSoon),ReviewsOverdue=d.Count(x=>x.IsReviewOverdue),Attestations=a.Count,ValidAttestations=a.Count(x=>x.IsValid),InvalidAttestations=a.Count(x=>!x.IsValid&&x.ArchiveAvailable),MissingAttestationArchives=a.Count(x=>!x.ArchiveAvailable),Exports=e.Count,ValidExports=e.Count(x=>x.IsValid),InvalidExports=e.Count(x=>!x.IsValid&&x.FileAvailable),MissingExports=e.Count(x=>!x.FileAvailable),RetentionDue=e.Count(x=>x.RetentionStatus=="In scadenza"),RetentionOverdue=e.Count(x=>x.RetentionStatus=="Scaduta")};}
 public string ExportPdf(SupplierRmaCapaGovernanceSnapshot x){var s=_settings.Load();var t=s.DocumentTemplate??new DocumentTemplateSettings();var d=new SimplePdfDocument{Title="Dashboard Governance CAPA"};Brand(d,s,t,$"CAPA-GOV-{DateTime.Now:yyyyMMdd-HHmm}");d.AddTitle("Dashboard Governance CAPA");d.AddKeyValue("Data elaborazione",DateTime.Now.ToString("dd/MM/yyyy HH:mm"));d.AddKeyValue("Operatore",Environment.UserName);d.AddStatus("Esito complessivo",x.CriticalCount==0?"Conforme":$"{x.CriticalCount} criticita da gestire");d.AddHeading("Fascicoli");d.AddKeyValue("Fascicoli totali",x.Dossiers.ToString());d.AddKeyValue("Attivi",x.ActiveDossiers.ToString());d.AddKeyValue("Archiviati",x.ArchivedDossiers.ToString());d.AddKeyValue("Approvati",x.ApprovedDossiers.ToString());d.AddKeyValue("Documenti mancanti",x.MissingDocuments.ToString());d.AddKeyValue("Riesami in scadenza",x.ReviewsDue.ToString());d.AddKeyValue("Riesami scaduti",x.ReviewsOverdue.ToString());d.AddHeading("Attestazioni");d.AddKeyValue("Totali",x.Attestations.ToString());d.AddKeyValue("Valide",x.ValidAttestations.ToString());d.AddKeyValue("Non valide",x.InvalidAttestations.ToString());d.AddKeyValue("Archivi mancanti",x.MissingAttestationArchives.ToString());d.AddHeading("Esportazioni e conservazione");d.AddKeyValue("Esportazioni totali",x.Exports.ToString());d.AddKeyValue("Integre",x.ValidExports.ToString());d.AddKeyValue("Modificate",x.InvalidExports.ToString());d.AddKeyValue("File mancanti",x.MissingExports.ToString());d.AddKeyValue("Conservazioni in scadenza",x.RetentionDue.ToString());d.AddKeyValue("Conservazioni scadute",x.RetentionOverdue.ToString());d.AddSignaturePair("Responsabile qualita","Responsabile processo");var folder=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),"Accyourate Enterprise X","Governance CAPA");return new PdfExportService().Export(d,folder,$"Dashboard-Governance-CAPA-{DateTime.Now:yyyyMMdd-HHmmss}");}
 private static void Brand(SimplePdfDocument d,ApplicationSettings s,DocumentTemplateSettings t,string code){d.Branding.CompanyName=string.IsNullOrWhiteSpace(s.Company.LegalName)?s.Company.CompanyName:s.Company.LegalName;d.Branding.CompanyDetailLines.AddRange(new[]{s.Company.Address,string.Join(" ",new[]{s.Company.City,s.Company.Province}.Where(v=>!string.IsNullOrWhiteSpace(v))),string.Join(" - ",new[]{s.Company.Phone,s.Company.Email}.Where(v=>!string.IsNullOrWhiteSpace(v))),string.Join(" - ",new[]{s.Company.VatNumber,s.Company.FiscalCode}.Where(v=>!string.IsNullOrWhiteSpace(v)))}.Where(v=>!string.IsNullOrWhiteSpace(v)));d.Branding.HeaderLayout=t.HeaderLayout;d.Branding.LogoPath=s.Company.LogoPath;d.Branding.LogoSize=t.LogoSize;d.Branding.LogoPosition=t.LogoPosition;d.Branding.PrimaryColor=t.PrimaryColor;d.Branding.DocumentLabel="DASHBOARD GOVERNANCE CAPA";d.Branding.DocumentCode=code;d.Branding.DocumentVersion=t.DocumentVersion;d.Branding.FooterText=t.FooterText;d.Branding.ConfidentialityText=t.ConfidentialityText;d.Branding.ShowLogo=t.ShowLogo;d.Branding.ShowCompanyDetails=t.ShowCompanyDetails;d.Branding.ShowDocumentMetadata=t.ShowDocumentMetadata;d.Branding.ShowFooter=t.ShowFooter;d.Branding.ShowPageNumber=t.ShowPageNumber;d.Branding.ShowPrintTimestamp=t.ShowPrintTimestamp;}
}
