using System.IO.Compression;
using System.Text;
using Accyourate.App.AssetManagement.Models;
using Accyourate.App.Platform.Pdf;

namespace Accyourate.App.AssetManagement.Services;

public sealed class SupplierRmaDossierService
{
    private readonly SupplierRmaPortalRepository _portal=new();private readonly SparePartRmaAnalyticsService _analytics=new();
    public string Generate(SparePartRmaCase rma,SparePartInventoryItem item,MaintenanceSupplier? supplier)
    {
        var supplierName=supplier?.Name??$"Fornitore #{rma.SupplierId}";var communications=_portal.GetAllCommunications().Where(x=>x.RmaId==rma.Id).OrderBy(x=>x.CreatedAt).ToList();var attachments=_portal.GetAttachments(rma.SupplierId).Where(x=>x.RmaId==rma.Id).ToList();var contacts=_portal.GetContacts(rma.SupplierId);var performance=_analytics.GetPerformance().FirstOrDefault(x=>x.SupplierId==rma.SupplierId);
        var document=new SimplePdfDocument{Title="Fascicolo completo pratica RMA"};document.Branding.DocumentLabel="FASCICOLO RMA";document.Branding.DocumentCode=rma.CaseNumber;document.AddTitle("Fascicolo completo pratica RMA");document.AddStatus("Stato pratica",rma.Status);document.AddKeyValue("Numero pratica",rma.CaseNumber);document.AddKeyValue("Generato il",DateTime.Now.ToString("dd/MM/yyyy HH:mm"));
        document.AddHeading("Pratica e materiale");document.AddKeyValue("Ricambio",$"{item.PartCode} - {item.Description}");document.AddKeyValue("Quantità",rma.Quantity.ToString("N2"));document.AddKeyValue("Autorizzazione",Dash(rma.AuthorizationNumber));document.AddKeyValue("Apertura",Date(rma.CreatedAt));document.AddKeyValue("Scadenza",Date(rma.DueDate));document.AddKeyValue("Spedizione",$"{Dash(rma.Courier)} - {Dash(rma.TrackingNumber)}");document.AddKeyValue("Esito",Dash(rma.Outcome));document.AddKeyValue("Costi",$"EUR {rma.ShippingCost+rma.ResolutionCost:N2}");document.AddKeyValue("Note",Dash(rma.Notes));
        document.AddHeading("Fornitore");document.AddKeyValue("Ragione sociale",supplierName);document.AddKeyValue("E-mail",Dash(supplier?.Email??""));document.AddKeyValue("Telefono",Dash(supplier?.Phone??""));document.AddKeyValue("Referente",contacts.FirstOrDefault(x=>x.IsPrimary)?.Name??contacts.FirstOrDefault()?.Name??"—");
        document.AddHeading("Riepilogo SLA fornitore");document.AddKeyValue("Pratiche complessive",performance?.TotalCases.ToString()??"—");document.AddKeyValue("Pratiche scadute",performance?.OverdueCases.ToString()??"—");document.AddKeyValue("Conformità SLA",performance is null||performance.EvaluatedSlaCases==0?"—":$"{performance.SlaCompliancePercent:N0}%");document.AddKeyValue("Tempo medio risoluzione",performance is null||performance.ClosedCases==0?"—":$"{performance.AverageResolutionDays:N1} giorni");document.AddKeyValue("Affidabilità",performance is null?"—":$"{performance.ReliabilityScore:N0}/100");
        document.AddHeading("Evidenze del fascicolo");document.AddKeyValue("Comunicazioni",communications.Count.ToString());document.AddKeyValue("Solleciti",communications.Count(x=>x.Type=="Sollecito").ToString());document.AddKeyValue("Risposte ricevute",communications.Count(x=>x.Direction=="In entrata").ToString());document.AddKeyValue("Allegati",attachments.Count.ToString());document.AddKeyValue("File mancanti",attachments.Count(x=>!x.IsAvailable).ToString());
        if(communications.Count>0){document.AddHeading("Cronologia sintetica");foreach(var x in communications.TakeLast(12))document.AddText($"{Date(x.CreatedAt)} - {x.Direction} - {x.Type} - {x.Subject} ({x.CommunicationStatus})",9);}
        document.AddQrCode($"AXRMA:{rma.CaseNumber}","Pratica RMA");
        var root=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),"Accyourate Enterprise X","Fascicoli RMA");Directory.CreateDirectory(root);var pdf=new PdfExportService().Export(document,root,$"Indice-{rma.CaseNumber}");var zipPath=Path.Combine(root,$"Fascicolo-{rma.CaseNumber}.zip");if(File.Exists(zipPath))File.Delete(zipPath);using var archive=ZipFile.Open(zipPath,ZipArchiveMode.Create);archive.CreateEntryFromFile(pdf,$"Indice-{rma.CaseNumber}.pdf",CompressionLevel.Optimal);Write(archive,"indice.csv",IndexCsv(rma,item,supplierName,communications,attachments));Write(archive,"comunicazioni.csv",CommunicationsCsv(communications));Write(archive,"cronologia-solleciti.csv",AuditCsv(communications));foreach(var file in attachments.Where(x=>x.IsAvailable).GroupBy(x=>x.StoredPath,StringComparer.OrdinalIgnoreCase).Select(x=>x.First()))archive.CreateEntryFromFile(file.StoredPath,$"Allegati/{file.Id}-{Safe(file.FileName)}",CompressionLevel.Optimal);return zipPath;
    }
    private string AuditCsv(IEnumerable<SupplierPortalInteraction> communications){var sb=new StringBuilder("Comunicazione;Data;Azione;Valore precedente;Nuovo valore;Note;Utente\r\n");foreach(var interaction in communications)foreach(var x in _portal.GetFollowUpAudit(interaction.Id))sb.AppendLine(Join(interaction.Subject,x.CreatedAt,x.Action,x.OldValue,x.NewValue,x.Notes,x.CreatedBy));return sb.ToString();}
    private static string CommunicationsCsv(IEnumerable<SupplierPortalInteraction> values){var sb=new StringBuilder("Data;Tipo;Direzione;Oggetto;Stato;Messaggio;Autore\r\n");foreach(var x in values)sb.AppendLine(Join(x.CreatedAt,x.Type,x.Direction,x.Subject,x.CommunicationStatus,x.Message,x.CreatedBy));return sb.ToString();}
    private static string IndexCsv(SparePartRmaCase rma,SparePartInventoryItem item,string supplier,int communications,int attachments)=>Join("Pratica","Ricambio","Fornitore","Stato","Comunicazioni","Allegati")+Environment.NewLine+Join(rma.CaseNumber,$"{item.PartCode} - {item.Description}",supplier,rma.Status,communications.ToString(),attachments.ToString());
    private static string IndexCsv(SparePartRmaCase rma,SparePartInventoryItem item,string supplier,IReadOnlyCollection<SupplierPortalInteraction> communications,IReadOnlyCollection<SupplierPortalAttachment> attachments)=>IndexCsv(rma,item,supplier,communications.Count,attachments.Count);
    private static void Write(ZipArchive archive,string name,string content){var entry=archive.CreateEntry(name);using var writer=new StreamWriter(entry.Open(),new UTF8Encoding(true));writer.Write(content);}
    private static string Join(params string[] values)=>string.Join(";",values.Select(Csv));private static string Csv(string value)=>$"\"{value.Replace("\"","\"\"").Replace("\r"," ").Replace("\n"," ")}\"";private static string Safe(string value)=>string.Concat(value.Select(c=>Path.GetInvalidFileNameChars().Contains(c)?'_':c));private static string Date(string value)=>DateTime.TryParse(value,out var d)?d.ToString("dd/MM/yyyy HH:mm"):"—";private static string Dash(string value)=>string.IsNullOrWhiteSpace(value)?"—":value;
}
