using Avalonia;using Avalonia.Controls;using Avalonia.Media;using Accyourate.App.UIFramework.Tokens;using System.Diagnostics;
namespace Accyourate.App.Platform.Backup;
public sealed class BackupCenterView:UserControl
{
 private readonly BackupService _backup=new();private readonly RestoreService _restore=new();private readonly StackPanel _rows=new();private readonly TextBlock _message=new();private IReadOnlyList<BackupHistoryRecord> _history=Array.Empty<BackupHistoryRecord>();
 public BackupCenterView(){Background=UiTokens.Brush(UiTokens.Background);Content=Build();Load();}
 private Control Build(){var root=new DockPanel();var header=new Grid{Margin=new Thickness(24,20,24,16),ColumnDefinitions=new ColumnDefinitions("*,150,130,150")};var title=new StackPanel{Spacing=6};title.Children.Add(new TextBlock{Text="Backup Center",FontSize=34,FontWeight=FontWeight.Bold,Foreground=UiTokens.Brush(UiTokens.TextPrimary)});title.Children.Add(new TextBlock{Text="Backup e ripristino dei database e delle impostazioni.",Foreground=UiTokens.Brush(UiTokens.TextSecondary),TextWrapping=TextWrapping.Wrap});Add(header,title,0,0);Add(header,Btn("Nuovo backup",Create,true),1,0);Add(header,Btn("↻ Aggiorna",Load,false),2,0);Add(header,Btn("Apri cartella",OpenFolder,false),3,0);DockPanel.SetDock(header,Dock.Top);root.Children.Add(header);_message.Margin=new Thickness(24,0,24,12);_message.Foreground=UiTokens.Brush(UiTokens.BrandBlue);DockPanel.SetDock(_message,Dock.Top);root.Children.Add(_message);root.Children.Add(new ScrollViewer{Content=_rows,Margin=new Thickness(24,0,24,24),VerticalScrollBarVisibility=Avalonia.Controls.Primitives.ScrollBarVisibility.Auto});return root;}
 private void Load(){try{_history=_backup.GetHistory(200);Draw();Msg($"Caricati {_history.Count} backup.");}catch(Exception ex){Msg($"Errore: {ex.Message}",true);}}private void Draw(){_rows.Children.Clear();_rows.Spacing=8;if(_history.Count==0){_rows.Children.Add(Card(new TextBlock{Text="Nessun backup presente.",Foreground=UiTokens.Brush(UiTokens.TextSecondary)}));return;}foreach(var r in _history)_rows.Children.Add(Row(r));}
 private Control Row(BackupHistoryRecord r){var s=new StackPanel{Spacing=8};s.Children.Add(new TextBlock{Text=r.FileName,FontSize=18,FontWeight=FontWeight.Bold,Foreground=UiTokens.Brush(UiTokens.TextPrimary),TextWrapping=TextWrapping.Wrap});s.Children.Add(new TextBlock{Text=$"{r.Status} · {Size(r.SizeBytes)} · {Date(r.CreatedAt)}",Foreground=UiTokens.Brush(UiTokens.TextSecondary)});s.Children.Add(new TextBlock{Text=r.FilePath,Foreground=UiTokens.Brush(UiTokens.TextSecondary),TextWrapping=TextWrapping.Wrap});var actions=new StackPanel{Orientation=Avalonia.Layout.Orientation.Horizontal,Spacing=8};actions.Children.Add(Btn("Verifica",()=>Verify(r),true));actions.Children.Add(Btn("Ripristina",()=>Restore(r),false));s.Children.Add(actions);return Card(s);}private void Create(){try{var r=_backup.CreateFullBackup("Backup Center");Msg($"Backup creato: {r.FileName}");Load();}catch(Exception ex){Msg($"Errore backup: {ex.Message}",true);}}private void Verify(BackupHistoryRecord r){var ok=_backup.VerifyBackup(r.FilePath);Msg(ok?"Backup verificato correttamente.":"Verifica fallita.",!ok);}private void Restore(BackupHistoryRecord r){try{_restore.Restore(r.FilePath,"Backup Center");Msg("Ripristino completato. Riavvia l'applicazione.",true);}catch(Exception ex){Msg($"Errore ripristino: {ex.Message}",true);}}private void OpenFolder(){try{Process.Start(new ProcessStartInfo{FileName=_backup.BackupFolder,UseShellExecute=true});}catch(Exception ex){Msg($"Errore apertura cartella: {ex.Message}",true);}}
 private void Msg(string m,bool err=false){_message.Text=m;_message.Foreground=UiTokens.Brush(err?UiTokens.Danger:UiTokens.BrandBlue);}private static Button Btn(string t,Action a,bool primary){var b=new Button{Content=t,Background=UiTokens.Brush(primary?UiTokens.BrandBlue:UiTokens.Surface),Foreground=primary?Brushes.White:UiTokens.Brush(UiTokens.TextPrimary),FontWeight=FontWeight.Bold,Padding=new Thickness(10,8),CornerRadius=new CornerRadius(12),Margin=new Thickness(4)};b.Click+=(_,_)=>a();return b;}private static Border Card(Control c)=>new(){Background=UiTokens.Brush(UiTokens.Surface),CornerRadius=new CornerRadius(18),Padding=new Thickness(16),Child=c};private static string Date(string v)=>DateTime.TryParse(v,out var d)?d.ToString("dd/MM/yyyy HH:mm"):v;private static string Size(long b)=>b<1024?$"{b} B":b<1024*1024?$"{b/1024.0:0.0} KB":$"{b/1024.0/1024.0:0.0} MB";private static void Add(Grid g,Control c,int col,int row){Grid.SetColumn(c,col);Grid.SetRow(c,row);g.Children.Add(c);}
}
