using Microsoft.Data.Sqlite;
namespace Accyourate.App.Platform.Backup;
public sealed class BackupHistoryRepository
{
 private readonly string _databasePath;
 public BackupHistoryRepository(string? databasePath=null){var folder=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),"AccyourateEnterpriseX");Directory.CreateDirectory(folder);_databasePath=databasePath??Path.Combine(folder,"accyourate-platform.db");Initialize();}
 private string ConnectionString=>$"Data Source={_databasePath}";
 public void Initialize(){using var c=OpenConnection();Exec(c,"""CREATE TABLE IF NOT EXISTS BackupHistory(Id INTEGER PRIMARY KEY AUTOINCREMENT,FileName TEXT NOT NULL,FilePath TEXT NOT NULL,BackupType TEXT NOT NULL,Status TEXT NOT NULL,SizeBytes INTEGER NOT NULL DEFAULT 0,Checksum TEXT,CreatedAt TEXT NOT NULL,CreatedBy TEXT,Notes TEXT);""");Exec(c,"CREATE INDEX IF NOT EXISTS IX_BackupHistory_CreatedAt ON BackupHistory(CreatedAt);");}
 public int Add(BackupHistoryRecord r){using var c=OpenConnection();using var cmd=c.CreateCommand();cmd.CommandText="""INSERT INTO BackupHistory(FileName,FilePath,BackupType,Status,SizeBytes,Checksum,CreatedAt,CreatedBy,Notes) VALUES($FileName,$FilePath,$BackupType,$Status,$SizeBytes,$Checksum,$CreatedAt,$CreatedBy,$Notes);SELECT last_insert_rowid();""";cmd.Parameters.AddWithValue("$FileName",r.FileName);cmd.Parameters.AddWithValue("$FilePath",r.FilePath);cmd.Parameters.AddWithValue("$BackupType",r.BackupType);cmd.Parameters.AddWithValue("$Status",r.Status);cmd.Parameters.AddWithValue("$SizeBytes",r.SizeBytes);cmd.Parameters.AddWithValue("$Checksum",r.Checksum);cmd.Parameters.AddWithValue("$CreatedAt",r.CreatedAt);cmd.Parameters.AddWithValue("$CreatedBy",r.CreatedBy);cmd.Parameters.AddWithValue("$Notes",r.Notes);return Convert.ToInt32(cmd.ExecuteScalar());}
 public IReadOnlyList<BackupHistoryRecord> GetLatest(int limit=100){using var c=OpenConnection();using var cmd=c.CreateCommand();cmd.CommandText="SELECT Id,FileName,FilePath,BackupType,Status,SizeBytes,Checksum,CreatedAt,CreatedBy,Notes FROM BackupHistory ORDER BY CreatedAt DESC LIMIT $Limit;";cmd.Parameters.AddWithValue("$Limit",Math.Max(1,limit));using var r=cmd.ExecuteReader();var list=new List<BackupHistoryRecord>();while(r.Read())list.Add(new BackupHistoryRecord{Id=r.GetInt32(0),FileName=S(r,1),FilePath=S(r,2),BackupType=S(r,3),Status=S(r,4),SizeBytes=r.GetInt64(5),Checksum=S(r,6),CreatedAt=S(r,7),CreatedBy=S(r,8),Notes=S(r,9)});return list;}
 private SqliteConnection OpenConnection(){var c=new SqliteConnection(ConnectionString);c.Open();return c;}private static void Exec(SqliteConnection c,string sql){using var cmd=c.CreateCommand();cmd.CommandText=sql;cmd.ExecuteNonQuery();}private static string S(SqliteDataReader r,int i)=>r.IsDBNull(i)?string.Empty:r.GetString(i);
}
