using System.IO.Compression;using System.Security.Cryptography;using System.Text;using System.Text.Json;using Accyourate.App.Platform.Audit;using Accyourate.App.Platform.Notifications;using Accyourate.App.Platform.Settings;
namespace Accyourate.App.Platform.Backup;
public sealed class BackupService
{
 private readonly SettingsService _settings=new();private readonly BackupHistoryRepository _history=new();private readonly AuditService _audit=new();private readonly NotificationService _notifications=new();
 public string BackupFolder{get{var s=_settings.Load();var root=string.IsNullOrWhiteSpace(s.Documents.DocumentRootPath)?Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),"Accyourate Enterprise X"):s.Documents.DocumentRootPath;var f=Path.Combine(root,"Backup");Directory.CreateDirectory(f);return f;}}
 public BackupHistoryRecord CreateFullBackup(string createdBy="System"){var app=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),"AccyourateEnterpriseX");var temp=Path.Combine(Path.GetTempPath(),$"AccyourateBackup_{Guid.NewGuid():N}");Directory.CreateDirectory(temp);var m=new BackupManifest{CreatedBy=createdBy,Notes="Database e impostazioni"};try{var db=Path.Combine(temp,"databases");var set=Path.Combine(temp,"settings");Directory.CreateDirectory(db);Directory.CreateDirectory(set);Copy(Path.Combine(app,"accyourate-hr.db"),Path.Combine(db,"accyourate-hr.db"),m);Copy(Path.Combine(app,"accyourate-assets.db"),Path.Combine(db,"accyourate-assets.db"),m);Copy(Path.Combine(app,"accyourate-platform.db"),Path.Combine(db,"accyourate-platform.db"),m);Copy(Path.Combine(app,"settings.json"),Path.Combine(set,"settings.json"),m);File.WriteAllText(Path.Combine(temp,"version.txt"),m.Version,Encoding.UTF8);File.WriteAllText(Path.Combine(temp,"manifest.json"),JsonSerializer.Serialize(m,new JsonSerializerOptions{WriteIndented=true}),Encoding.UTF8);var path=Path.Combine(BackupFolder,$"Accyourate_Backup_{DateTime.Now:yyyyMMdd_HHmmss}.zip");if(File.Exists(path))File.Delete(path);ZipFile.CreateFromDirectory(temp,path,CompressionLevel.Optimal,false);var checksum=Sha(path);File.WriteAllText($"{path}.sha256",checksum,Encoding.UTF8);var r=new BackupHistoryRecord{FileName=Path.GetFileName(path),FilePath=path,SizeBytes=new FileInfo(path).Length,Checksum=checksum,CreatedBy=createdBy,Notes=m.Notes};r.Id=_history.Add(r);_audit.Track(AuditAction.Created,$"Creato backup {r.FileName}","Backup",r.Id.ToString(),r.FileName,createdBy,AuditSeverity.Info,"BackupCenter");_notifications.Publish("Backup completato",$"Creato backup {r.FileName}.",NotificationCategory.System,NotificationPriority.Info,createdBy,"open-backup",r.Id.ToString());return r;}finally{if(Directory.Exists(temp))Directory.Delete(temp,true);}}
 public bool VerifyBackup(string path){var c=$"{path}.sha256";return File.Exists(path)&&File.Exists(c)&&string.Equals(File.ReadAllText(c).Trim(),Sha(path),StringComparison.OrdinalIgnoreCase);}public IReadOnlyList<BackupHistoryRecord> GetHistory(int limit=100)=>_history.GetLatest(limit);
 private static void Copy(string source,string dest,BackupManifest m){if(!File.Exists(source))return;Directory.CreateDirectory(Path.GetDirectoryName(dest)??".");File.Copy(source,dest,true);m.Files.Add(Path.GetFileName(dest));}private static string Sha(string path){using var s=File.OpenRead(path);using var sha=SHA256.Create();return Convert.ToHexString(sha.ComputeHash(s));}
}
