<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Accyourate.Core\Accyourate.Core.csproj" />
    <ProjectReference Include="..\Accyourate.Domain\Accyourate.Domain.csproj" />
    <ProjectReference Include="..\Accyourate.Shared\Accyourate.Shared.csproj" />
  </ItemGroup>

</Project>
